// Theme-specific explanations for all 120 themes
// Each explains what the theme means, not what to do with it
export const themeExplanations: Record<string, string> = {
  "Receiving Without Defending": "You are valued simply for being who you are, not for what you accomplish. You can be imperfect, ordinary, and still be wanted here.",
  "Letting Yourself Be Known": "To be seen as you are means dropping the curated version and letting people know the real you—your doubts, your desires, your mess.",
  "The Courage to Ask": "Asking for what you need is not weakness or burden. It's an act of trust that gives others the gift of knowing how to support you.",
  "What Your Body Has Been Holding": "Your body carries memory and emotion that your mind hasn't processed. Tension, numbness, or sensation often holds wisdom about what you really feel.",
  "Friendship Without Performance": "Real friendship is what happens when you stop trying to impress and start being honest. It's the freedom to show up tired or struggling and feel welcomed.",
  "Desire Without Shame": "Your desire—for connection, pleasure, rest, growth—is not selfish. It's information about what makes you feel alive.",
  "Touch Without Obligation": "Touch as medicine means receiving affection, closeness, or presence not as transaction but as nourishment.",
  "Resting the Armor": "You don't have to be strong right now. The independence, control, and stoicism you've built can come off for a while. It's safe to be soft.",
  "The Difference Between Privacy and Hiding": "Privacy is a healthy boundary. Hiding is protection from connection. One keeps you safe; the other keeps you alone.",
  "Making Room for Wanting": "Beneath what you think you should want is what you actually want. That desire is legitimate and worth listening to.",
  "Presence as a Practice": "Presence isn't about achieving something. It's about showing up fully to what's actually happening right now.",
  "The Body as a Home": "Your body is not a machine to optimize or a problem to fix. It's a home—a place to inhabit, to listen to, to befriend.",
  "Listening Without Fixing": "Sometimes people don't need advice or solutions. They need to be truly heard—not judged, not interrupted, just received.",
  "Permission to Feel": "Your feelings are not too big, too messy, or too much. They're not wrong or selfish. They're information that deserves space.",
  "Slow Down. You're Safe Here.": "You can stop rushing. There's nowhere you need to be but here. This moment is safe enough to slow down into.",
  "Softness as Strength": "The deepest strength is gentleness—with yourself, with others. Softness allows flow instead of resistance.",
  "The Courage of Honesty": "Your truth matters, even if it's uncomfortable. Speaking it is an act of courage that creates space for real connection.",
  "What It Means to Belong": "Belonging isn't about fitting in or being like everyone else. It's about being known—fully seen and still chosen.",
  "Release What You've Been Protecting": "We protect ourselves from pain, but that protection often keeps us from living. What would be possible if you let some of those walls down?",
  "The Language Your Body Speaks": "Your body tells the truth before your mind catches up—through tension, warmth, openness, or shutdown.",
  "Being Wanted, Not Needed": "There's a difference between being wanted for who you are and being needed for what you provide. Real intimacy is based on choice, not necessity.",
  "The Gift of Asking for Help": "Asking for help is not admitting defeat. It's admitting you're human and allowing others the privilege of mattering to you.",
  "Desire as Information": "Your desire is a messenger. It tells you where your aliveness lives, what your body needs, what your heart is reaching toward.",
  "What Happens When You Stop Performing": "When you stop performing, something true emerges. The people who stay are the ones worth keeping.",
  "Breath as Home": "Your breath is always available as an anchor. Coming back to it is coming back to yourself.",
  "The Bravery in Being Ordinary": "There's profound bravery in being ordinary—in not trying to be exceptional, just real.",
  "Touch Across Boundaries": "Touch can happen across all kinds of boundaries—professional, familial, spiritual. It all matters.",
  "Speaking Your Truth Softly": "You don't have to shout to be heard. Your truth can be spoken gently and still be powerful.",
  "The Body's Wisdom": "Your body knows things your rational mind doesn't. Learning to trust it is learning to trust yourself.",
  "Longing is Information": "What you long for tells you something about what's missing, what matters, what you're reaching toward.",
  "Invitation and Consent": "Real connection starts with clear invitation and genuine consent. Both people choosing, both people wanting.",
  "What Real Support Looks Like": "Real support isn't about fixing or saving. It's about showing up, believing in someone's capacity to find their own way.",
  "The Courage to Be Seen": "Being seen is terrifying because it means you can't hide. But it's also where real intimacy begins.",
  "Intimacy Without Urgency": "True intimacy doesn't rush. It deepens over time, with presence and patience.",
  "The Quiet Strength of Presence": "Sometimes the most powerful thing you can offer is your calm, grounded presence.",
  "Healing the Abandonment Inside": "We all carry some wound of abandonment. Healing it means learning to show up for ourselves.",
  "When Defenses Are Love": "Sometimes our defenses are the best love we knew how to give ourselves at the time. You can honor them and release them.",
  "The Truth in Your Hesitation": "When you hesitate, there's usually truth there. Your body knows before your mind does.",
  "Belonging to Yourself First": "Before you can belong to anyone else, you have to belong to yourself. That's the foundation.",
  "The Grace of Slowing Down": "The deepest things happen slowly. Slowing down is how you access them.",
  "Noticing Without Judgment": "You can observe your thoughts, feelings, and body without judging them as right or wrong.",
  "The Intimacy of Being Heard": "Being truly heard is one of the most intimate experiences possible.",
  "What Softening Teaches Us": "When you soften, you learn what was underneath the hardness. You learn what you're truly made of.",
  "The Body Never Lies": "Your body's signals—tension, ease, attraction, revulsion—are always truthful.",
  "Permission to Grieve": "Grief is the price of love. It's sacred and deserves your full attention.",
  "Asking Without Shame": "You can ask for what you want without shame. Your needs are legitimate.",
  "The Space Between Souls": "There's a sacred space between two people who are truly present with each other.",
  "What It Means to Come Home": "Coming home isn't just about location. It's about arriving at a place where you can finally rest.",
  "Desire as Prayer": "Your deepest desires are a form of prayer—a reaching toward what matters most.",
  "The Bravery of Vulnerability": "Vulnerability looks like weakness from the outside, but it takes the most strength.",
  "Tenderness as a Way of Being": "You can live from tenderness. It's not weakness; it's a complete way of moving through the world.",
  "The Gift of Attention": "Your attention is one of the most precious gifts you can offer someone.",
  "Breaking the Silence Inside": "Sometimes the deepest healing comes from speaking the things you've kept silent about.",
  "The Courage to Rest": "Resting is not laziness. It's an act of resistance against a world that demands constant productivity.",
  "What You're Really Asking For": "Beneath most requests is a deeper need. Learning to recognize it is key to real connection.",
  "The Sacred in the Ordinary": "There's nothing more sacred than a moment of real connection over a cup of tea.",
  "When Vulnerability Is Revolutionary": "In a world that demands armor, vulnerability is a radical act.",
  "The Language of the Body": "Your body speaks fluently in sensations, temperature, movement. Learning its language is learning to understand yourself.",
  "Connection as Medicine": "Real connection has healing power. It's not optional; it's essential.",
  "The Truth of Your Longing": "What you long for reveals what you value, what you've lost, what you're becoming.",
  "Permission to Be Whole": "You don't have to choose between strength and softness. You can be whole—both at once.",
  "The Wisdom of Boundaries": "Boundaries aren't walls. They're how you take care of yourself so you can show up for others.",
  "Being Known, Being Loved": "The deepest wish is to be known fully and loved anyway. That's what belonging feels like.",
  "The Courage to Start Again": "Every moment is a chance to start again. The past doesn't define what happens next.",
  "Presence as an Act of Love": "Showing up fully present is the highest form of love you can offer.",
  "The Sacred Pause": "A pause is not nothing. It's where clarity lives.",
  "What Shame Wants You to Know": "Shame speaks in silence and hiding. Healing comes when you speak its truth out loud.",
  "The Intimacy of Trust": "Trust is intimacy. To trust someone is to let them matter.",
  "Your Body as Guidance": "Your body knows the way. You don't have to figure it all out with your mind.",
  "The Grace of Asking": "Asking is how vulnerability becomes connection.",
  "Belonging Without Performing": "You are complete as you are. Nothing you do adds to your belonging.",
  "The Bravery in Gentleness": "Gentleness is not weakness. It's the courage to soften in a world that demands hardness.",
  "Deepening Your Breath": "Your breath can take you deeper into presence, into your body, into connection.",
  "The Medicine of Being Seen": "There's healing power in being truly seen—not judged, not fixed, just witnessed.",
  "Desire Without Desperation": "You can want something without needing it to complete you. That's the freedom.",
  "The Courage to Be Still": "In stillness, you hear yourself. In stillness, you find peace.",
  "What It Means to Be Held": "To be held is to be safe. To be held is to know you matter.",
  "The Truth in Silence": "Silence isn't empty. It's full of meaning if you listen.",
  "Permission to Want": "What you want matters. Your wanting is information about your aliveness.",
  "The Wisdom in Your Hesitation": "Your hesitation is wisdom. It's your deeper self speaking.",
  "Softening the Hard Places": "The places where you're hard are the places that need the most gentleness.",
  "The Gift of Being Chosen": "When someone chooses you—when you choose yourself—that's everything.",
  "Coming Back to Your Body": "Your body is always waiting for you. You can come home to it anytime.",
  "The Intimacy of Saying No": "Saying no to what you don't want is how you say yes to what you do.",
  "What Presence Really Is": "Presence is not about doing anything. It's about being here, fully, as you are.",
  "Permission to Thaw": "If you've frozen yourself to stay safe, you can thaw. It's possible to come back to life.",
  "The Courage to Connect": "Connection requires vulnerability. It requires showing up even when it's scary.",
  "Your Body Deserves Attention": "Your body has been carrying you. It deserves your care and attention.",
  "The Grace of Being Imperfect": "Your imperfections are not flaws. They're what make you real, relatable, human.",
  "Desire as a Teacher": "What you desire teaches you about yourself. Pay attention.",
  "The Sacred in Sexual Connection": "Sex can be sacred. It's a profound form of intimacy and presence.",
  "Belonging to the Body": "Your body is not separate from you. Belonging to it is belonging to yourself.",
  "The Truth Your Touch Speaks": "Touch communicates what words cannot. It speaks in presence, in care, in wanting.",
  "Permission to Soften": "You can let your defenses down. The world won't fall apart.",
  "What It Means to Be Held": "Being held means you don't have to hold everything alone.",
  "The Courage of Tenderness": "Tenderness is not soft. It's fiercely strong and deeply brave.",
  "Coming Home to Yourself": "All the seeking outside is pointing you back to yourself.",
  "The Wisdom of Your Body": "Your body is wise. It knows what you need before you understand it.",
  "Desire Without Apology": "You can want what you want without explaining or justifying it.",
  "The Gift of Simple Presence": "Just being here, together, is enough.",
  "Permission to Be Alive": "You get to be alive. Not just surviving, but fully alive.",
};

export function getThemeExplanation(title: string): string {
  return themeExplanations[title] || "This theme invites you to notice something true about yourself today.";
}
