/**
 * Daily Companion Content Seed Data - FULLY UPDATED
 *
 * This file seeds the database with 120 sets of perfectly aligned content.
 * All content is seeded in Trevor James' voice:
 * warm, grounded, compassionate, mature, slightly poetic but clear.
 */

export const dailyThemes = [
  { index: 0, title: "The Honest Starting Point", category: "authenticity" },
  { index: 1, title: "Noticing Without Fixing", category: "awareness" },
  { index: 2, title: "The Loving Edge", category: "boundaries" },
  { index: 3, title: "The Brave First Sentence", category: "communication" },
  { index: 4, title: "A Place to Belong", category: "community" },
  { index: 5, title: "The Small Reach", category: "connection" },
  { index: 6, title: "One Brave Inch", category: "courage" },
  { index: 7, title: "Letting Want Be Welcome", category: "desire" },
  { index: 8, title: "Coming Back to Sensation", category: "embodiment" },
  { index: 9, title: "Feeling Without Becoming", category: "emotion" },
  { index: 10, title: "The Pace of Repair", category: "healing" },
  { index: 11, title: "Closer Without Collapsing", category: "intimacy" },
  { index: 12, title: "The Quiet Knowing", category: "intuition" },
  { index: 13, title: "Here, Not Elsewhere", category: "presence" },
  { index: 14, title: "Meeting the Protective Part", category: "psychology" },
  { index: 15, title: "Sexuality Without Performance", category: "sexuality" },
  { index: 16, title: "The Larger Thread", category: "spirituality" },
  { index: 17, title: "Soft Strength", category: "strength" },
  { index: 18, title: "The Truth With a Soft Belly", category: "vulnerability" },
  { index: 19, title: "Unperforming the Self", category: "authenticity" },
  { index: 20, title: "The Pause Before Reaction", category: "awareness" },
  { index: 21, title: "Enough Is Information", category: "boundaries" },
  { index: 22, title: "Listening for What Is Underneath", category: "communication" },
  { index: 23, title: "Contributing Without Overgiving", category: "community" },
  { index: 24, title: "Being Met, Not Managed", category: "connection" },
  { index: 25, title: "Telling the Truth Kindly", category: "courage" },
  { index: 26, title: "The Desire Under the Desire", category: "desire" },
  { index: 27, title: "The Wisdom of Slowness", category: "embodiment" },
  { index: 28, title: "The Honest Mood", category: "emotion" },
  { index: 29, title: "Reclaiming What Was Exiled", category: "healing" },
  { index: 30, title: "The Pace of Closeness", category: "intimacy" },
  { index: 31, title: "Body Yes, Body No", category: "intuition" },
  { index: 32, title: "The Unrushed Moment", category: "presence" },
  { index: 33, title: "Old Maps, New Roads", category: "psychology" },
  { index: 34, title: "Desire With Consent", category: "sexuality" },
  { index: 35, title: "Reverence for the Ordinary", category: "spirituality" },
  { index: 36, title: "Staying With Yourself", category: "strength" },
  { index: 37, title: "Letting Yourself Be Impacted", category: "vulnerability" },
  { index: 38, title: "Permission to Be Specific", category: "authenticity" },
  { index: 39, title: "Witnessing the Inner Weather", category: "awareness" },
  { index: 40, title: "Consent With Yourself", category: "boundaries" },
  { index: 41, title: "Asking for What You Need", category: "communication" },
  { index: 42, title: "Making Room for Others", category: "community" },
  { index: 43, title: "Connection Without Performance", category: "connection" },
  { index: 44, title: "Facing the Tender Fear", category: "courage" },
  { index: 45, title: "Longing Without Shame", category: "desire" },
  { index: 46, title: "Feet on the Ground", category: "embodiment" },
  { index: 47, title: "Grief in Small Doses", category: "emotion" },
  { index: 48, title: "Repairing the Inner Voice", category: "healing" },
  { index: 49, title: "Being Known in Layers", category: "intimacy" },
  { index: 50, title: "Following the Signal", category: "intuition" },
  { index: 51, title: "One Thing at a Time", category: "presence" },
  { index: 52, title: "Triggers as Time Travel", category: "psychology" },
  { index: 53, title: "Pleasure as Information", category: "sexuality" },
  { index: 54, title: "Body as Sacred Ground", category: "spirituality" },
  { index: 55, title: "Endurance With Care", category: "strength" },
  { index: 56, title: "The Risk of Asking", category: "vulnerability" },
  { index: 57, title: "The Unedited Yes", category: "authenticity" },
  { index: 58, title: "The Story Under the Story", category: "awareness" },
  { index: 59, title: "The Kind Decline", category: "boundaries" },
  { index: 60, title: "Repair Over Winning", category: "communication" },
  { index: 61, title: "The Courage to Participate", category: "community" },
  { index: 62, title: "The Thread Between Us", category: "connection" },
  { index: 63, title: "Beginning Before Ready", category: "courage" },
  { index: 64, title: "The Clean Ask", category: "desire" },
  { index: 65, title: "Softening the Armor", category: "embodiment" },
  { index: 66, title: "Anger as Information", category: "emotion" },
  { index: 67, title: "Trust After Hurt", category: "healing" },
  { index: 68, title: "Tender Attention", category: "intimacy" },
  { index: 69, title: "Discernment, Not Impulse", category: "intuition" },
  { index: 70, title: "Arriving in Conversation", category: "presence" },
  { index: 71, title: "The Inner Contract", category: "psychology" },
  { index: 72, title: "Shame and the Body", category: "sexuality" },
  { index: 73, title: "Mystery Without Control", category: "spirituality" },
  { index: 74, title: "The Strength to Receive", category: "strength" },
  { index: 75, title: "Being Seen in Process", category: "vulnerability" },
  { index: 76, title: "The Gentle No", category: "authenticity" },
  { index: 77, title: "Curiosity Over Judgment", category: "awareness" },
  { index: 78, title: "Room to Choose", category: "boundaries" },
  { index: 79, title: "Clear Is Kind", category: "communication" },
  { index: 80, title: "Shared Rituals", category: "community" },
  { index: 81, title: "Mutual Curiosity", category: "connection" },
  { index: 82, title: "Staying Present in Discomfort", category: "courage" },
  { index: 83, title: "Desire and Patience", category: "desire" },
  { index: 84, title: "Breath as Belonging", category: "embodiment" },
  { index: 85, title: "Joy Without Apology", category: "emotion" },
  { index: 86, title: "The Medicine of Gentleness", category: "healing" },
  { index: 87, title: "Mutual Safety", category: "intimacy" },
  { index: 88, title: "Trusting the Inner No", category: "intuition" },
  { index: 89, title: "Letting the Moment Touch You", category: "presence" },
  { index: 90, title: "Attachment in Everyday Life", category: "psychology" },
  { index: 91, title: "Erotic Honesty", category: "sexuality" },
  { index: 92, title: "Devotion in Practice", category: "spirituality" },
  { index: 93, title: "Protecting What Matters", category: "strength" },
  { index: 94, title: "Tender Honesty", category: "vulnerability" },
  { index: 95, title: "Becoming Less Available for Pretending", category: "authenticity" },
  { index: 96, title: "Tracking Patterns Kindly", category: "awareness" },
  { index: 97, title: "Boundaries After Contact", category: "boundaries" },
  { index: 98, title: "The Invitation, Not the Demand", category: "communication" },
  { index: 99, title: "Belonging With Difference", category: "community" },
  { index: 100, title: "Letting Contact Land", category: "connection" },
  { index: 101, title: "Risking Being Seen", category: "courage" },
  { index: 102, title: "Permission to Want More", category: "desire" },
  { index: 103, title: "Moving What Is Stuck", category: "embodiment" },
  { index: 104, title: "Making Room for Mixed Feelings", category: "emotion" },
  { index: 105, title: "Honoring the Scar", category: "healing" },
  { index: 106, title: "Receiving Closeness", category: "intimacy" },
  { index: 107, title: "The Wisdom Beneath Words", category: "intuition" },
  { index: 108, title: "Resting in Enough", category: "presence" },
  { index: 109, title: "Rehearsing a New Response", category: "psychology" },
  { index: 110, title: "Integration, Not Splitting", category: "sexuality" },
  { index: 111, title: "Blessing the Becoming", category: "spirituality" },
  { index: 112, title: "Steady After the Storm", category: "strength" },
  { index: 113, title: "Letting Care Reach You", category: "vulnerability" },
  { index: 114, title: "The Self That Stays", category: "authenticity" },
  { index: 115, title: "The Body as Messenger", category: "awareness" },
  { index: 116, title: "The Boundary That Protects Joy", category: "boundaries" },
  { index: 117, title: "Naming the Tender Part", category: "communication" },
  { index: 118, title: "Returning to the Circle", category: "community" },
  { index: 119, title: "The Connection That Includes Silence", category: "connection" },
];

export const reflectionPrompts = [
  { index: 0, prompt: "What part of you has been asking to be seen without being improved first?" },
  { index: 1, prompt: "What are you aware of today that does not need to be solved immediately?" },
  { index: 2, prompt: "Where is love asking you for a clearer edge today?" },
  { index: 3, prompt: "What is the first honest sentence you have been avoiding?" },
  { index: 4, prompt: "What kind of belonging are you hungry for, and what kind are you no longer willing to fake?" },
  { index: 5, prompt: "What small reach for connection feels honest today?" },
  { index: 6, prompt: "What is one brave inch you can move today, without demanding a heroic leap?" },
  { index: 7, prompt: "What desire is present today before you judge whether it is practical, noble, or convenient?" },
  { index: 8, prompt: "What sensation is most obvious in your body right now?" },
  { index: 9, prompt: "What feeling is here today, and how can you feel it without becoming only that feeling?" },
  { index: 10, prompt: "What part of you needs a slower pace to trust repair?" },
  { index: 11, prompt: "What helps you come closer while still staying connected to yourself?" },
  { index: 12, prompt: "What quiet knowing have you been talking yourself out of?" },
  { index: 13, prompt: "What part of you is already somewhere else, and what helps you return?" },
  { index: 14, prompt: "What part of you is trying to protect you, even if its methods are clumsy?" },
  { index: 15, prompt: "What would your sexuality feel like if it did not have to prove anything?" },
  { index: 16, prompt: "What helps you feel connected to something larger than your own thoughts?" },
  { index: 17, prompt: "Where is your strength becoming softer, wiser, or less performative?" },
  { index: 18, prompt: "What truth could you share with a little less armor today?" },
  { index: 19, prompt: "Where do you notice yourself performing, even subtly, instead of simply being here?" },
  { index: 20, prompt: "What happens inside you in the half-second before you react?" },
  { index: 21, prompt: "Where have you had enough, and what would honoring that look like?" },
  { index: 22, prompt: "What might someone be trying to say beneath the words they are using?" },
  { index: 23, prompt: "What is one way you can contribute today without abandoning your limits?" },
  { index: 24, prompt: "Where do you want to be met rather than fixed, advised, or managed?" },
  { index: 25, prompt: "What truth are you ready to tell with care, even if your voice shakes a little?" },
  { index: 26, prompt: "What might your desire be asking for beneath the obvious object of wanting?" },
  { index: 27, prompt: "What changes when you move, speak, or decide ten percent more slowly?" },
  { index: 28, prompt: "What mood are you actually in, before you make it more socially convenient?" },
  { index: 29, prompt: "What part of you was once pushed away that may be ready for a kinder welcome?" },
  { index: 30, prompt: "What pace of closeness feels honest for your body today?" },
  { index: 31, prompt: "How does your body communicate yes, no, and maybe?" },
  { index: 32, prompt: "What changes when this moment is not treated as a hallway to the next one?" },
  { index: 33, prompt: "What old map are you using for a present-day relationship?" },
  { index: 34, prompt: "How can desire stay alive while making room for clear consent?" },
  { index: 35, prompt: "What ordinary moment today could become sacred if you gave it reverent attention?" },
  { index: 36, prompt: "What helps you stay with yourself when someone else is disappointed, distant, or intense?" },
  { index: 37, prompt: "What has affected you more than you have admitted?" },
  { index: 38, prompt: "What specific quality, preference, or quirk have you been smoothing over to seem easier to love?" },
  { index: 39, prompt: "What emotional weather is moving through you today, and what name would you give it?" },
  { index: 40, prompt: "What are you saying yes to externally that feels like a no internally?" },
  { index: 41, prompt: "What need would become clearer if you stopped disguising it as a complaint?" },
  { index: 42, prompt: "Who gets more room when you listen, slow down, or stop needing to be central?" },
  { index: 43, prompt: "What would connection look like if you did not have to entertain, seduce, impress, or be useful?" },
  { index: 44, prompt: "What fear are you ready to look at without letting it run the meeting?" },
  { index: 45, prompt: "What longing have you made wrong simply because it feels vulnerable?" },
  { index: 46, prompt: "What becomes easier when you feel your feet before you respond?" },
  { index: 47, prompt: "What small grief might need tenderness today?" },
  { index: 48, prompt: "What would your inner voice sound like if it were on your side?" },
  { index: 49, prompt: "What layer of yourself are you ready to reveal, and what layer still needs privacy?" },
  { index: 50, prompt: "What small signal are you willing to follow today?" },
  { index: 51, prompt: "What would receive better attention if you stopped splitting yourself today?" },
  { index: 52, prompt: "When you are triggered, what younger or earlier experience might be entering the room?" },
  { index: 53, prompt: "What does pleasure teach you about what feels nourishing, enlivening, or true?" },
  { index: 54, prompt: "What changes when you treat your body as a place of dignity rather than a problem to manage?" },
  { index: 55, prompt: "Where have you been enduring without enough care?" },
  { index: 56, prompt: "What are you afraid might happen if you ask directly for care, clarity, or closeness?" },
  { index: 57, prompt: "What feels like a clean yes in you today, before you explain it or negotiate it away?" },
  { index: 58, prompt: "What story are you telling yourself today, and what else might also be true?" },
  { index: 59, prompt: "What could you decline without making yourself wrong or making the other person bad?" },
  { index: 60, prompt: "What would repair look like if being right were not the main goal?" },
  { index: 61, prompt: "Where are you watching from the edge when part of you wants to join?" },
  { index: 62, prompt: "What thread of care already exists between you and someone else?" },
  { index: 63, prompt: "What are you waiting to feel ready for, and what tiny beginning is available now?" },
  { index: 64, prompt: "What desire could become clearer if you asked for it simply?" },
  { index: 65, prompt: "Where is your body wearing armor that it no longer needs right now?" },
  { index: 66, prompt: "What might your anger be protecting, valuing, or trying to restore?" },
  { index: 67, prompt: "What helps you trust again without pretending the hurt did not matter?" },
  { index: 68, prompt: "What kind of attention helps you feel cherished rather than inspected?" },
  { index: 69, prompt: "How can you tell the difference between intuition and urgency?" },
  { index: 70, prompt: "What helps you arrive before you speak?" },
  { index: 71, prompt: "What silent contract have you made with yourself about love, touch, or belonging?" },
  { index: 72, prompt: "What sexual or sensual shame are you ready to meet with less cruelty?" },
  { index: 73, prompt: "Where can you allow mystery instead of forcing certainty?" },
  { index: 74, prompt: "Where would receiving support actually be a sign of strength?" },
  { index: 75, prompt: "What are you still figuring out that you usually hide until it looks tidy?" },
  { index: 76, prompt: "What truth becomes clearer when you stop forcing yourself to be agreeable?" },
  { index: 77, prompt: "Where could you replace self-judgment with one honest question?" },
  { index: 78, prompt: "Where do you need more time, space, or information before you choose?" },
  { index: 79, prompt: "Where could you be more clear, not colder?" },
  { index: 80, prompt: "What ritual, habit, or recurring moment helps turn strangers into a community?" },
  { index: 81, prompt: "What question would help you know someone more honestly?" },
  { index: 82, prompt: "What discomfort could you stay with for ten more seconds today?" },
  { index: 83, prompt: "How can you honor desire without rushing the pace of trust?" },
  { index: 84, prompt: "What happens when you let your breath remind you that you are here?" },
  { index: 85, prompt: "What joy is available today, even if everything is not fixed?" },
  { index: 86, prompt: "Where would gentleness be more effective than force today?" },
  { index: 87, prompt: "What helps intimacy feel mutual, not one-sided, rushed, or assumed?" },
  { index: 88, prompt: "Where is your inner no asking for respect?" },
  { index: 89, prompt: "What experience today are you willing to let actually touch you?" },
  { index: 90, prompt: "What do you do when closeness feels uncertain: pursue, withdraw, freeze, please, or protest?" },
  { index: 91, prompt: "What honest erotic truth can you acknowledge privately before sharing it with anyone else?" },
  { index: 92, prompt: "What are you devoted to in the way you live, love, touch, or speak?" },
  { index: 93, prompt: "What value, relationship, practice, or dream needs your protection today?" },
  { index: 94, prompt: "What honest feeling could you name gently, without using it as a weapon?" },
  { index: 95, prompt: "What version of you are you less willing to pretend to be now?" },
  { index: 96, prompt: "What pattern keeps showing up in your connections, and how can you study it without attacking yourself?" },
  { index: 97, prompt: "What boundary helps you stay connected after an intense conversation, date, session, or gathering?" },
  { index: 98, prompt: "Where can you invite connection instead of demanding reassurance?" },
  { index: 99, prompt: "What difference in someone else could you meet with curiosity instead of distance?" },
  { index: 100, prompt: "When someone offers care, appreciation, or attention, how much of it do you actually let in?" },
  { index: 101, prompt: "What part of you would like to be seen more clearly, even if it feels risky?" },
  { index: 102, prompt: "Where have you settled for less because wanting more felt risky or impolite?" },
  { index: 103, prompt: "What feeling or energy wants movement instead of more analysis?" },
  { index: 104, prompt: "Where are two truths or two feelings living in you at the same time?" },
  { index: 105, prompt: "What scar, visible or invisible, deserves respect rather than shame?" },
  { index: 106, prompt: "What makes it hard for you to receive closeness when it is offered?" },
  { index: 107, prompt: "What do you know beneath the explanation?" },
  { index: 108, prompt: "What would it feel like for this breath, this body, this moment to be enough for now?" },
  { index: 109, prompt: "What new response would you like to practice before the old pattern takes over?" },
  { index: 110, prompt: "What would it mean to let your sexuality belong with your heart, spirit, values, and body?" },
  { index: 111, prompt: "What part of your becoming could use blessing instead of pressure?" },
  { index: 112, prompt: "What helps you find steadiness after an emotional storm?" },
  { index: 113, prompt: "What care are you resisting because receiving it feels exposed?" },
  { index: 114, prompt: "What remains true about you even when your mood, confidence, or circumstances change?" },
  { index: 115, prompt: "What has your body been trying to tell you before your mind catches up?" },
  { index: 116, prompt: "What boundary would protect not just your peace, but your joy?" },
  { index: 117, prompt: "What tender feeling could you name before it turns into sarcasm, withdrawal, or control?" },
  { index: 118, prompt: "Where have you pulled away from community, and what kind of return would feel possible?" },
  { index: 119, prompt: "Where can silence become part of connection instead of a sign that something is wrong?" },
];

export const embodimentPractices = [
  { index: 0, practice: "Place one hand on your chest and say quietly, \"This is where I begin.\" Breathe slowly for one minute." },
  { index: 1, content: "Look around and name five things you see, four you feel, three you hear, two you smell, one you taste." },
  { index: 2, content: "Stand with feet hip-width apart and imagine a warm circle of space around you." },
  { index: 3, content: "Put one hand on your throat and hum softly for five breaths." },
  { index: 4, content: "Take three breaths while imagining a circle of people who do not need you to perform." },
  { index: 5, content: "Extend one hand slowly, then bring it back to your heart. Feel both reaching and returning." },
  { index: 6, content: "Step forward slowly and say, \"This much is enough for today.\"" },
  { index: 7, content: "Place a hand on your lower belly and breathe into the word \"want.\"" },
  { index: 8, content: "Scan your body for one sensation, then describe it with texture, temperature, and movement." },
  { index: 9, content: "Name the feeling, locate it in your body, and breathe around it for one minute." },
  { index: 10, content: "Place one hand over the area of your body that feels most protective and breathe gently." },
  { index: 11, content: "Imagine leaning toward someone while keeping your feet grounded and your breath steady." },
  { index: 12, content: "Sit quietly with one hand on your belly and ask, \"What do I already know?\"" },
  { index: 13, content: "Name three things in the room and feel one point of contact with your body." },
  { index: 14, content: "Place a hand where you feel guarded and thank that part for trying to help." },
  { index: 15, content: "Place one hand on your heart and one on your lower belly, breathing with respect for both." },
  { index: 16, content: "Look up, soften your chest, and take five slow breaths into a sense of spaciousness." },
  { index: 17, content: "Stand tall, relax your shoulders, and breathe into a grounded spine." },
  { index: 18, content: "Relax your belly and exhale before speaking something true." },
  { index: 19, content: "Sit with your feet grounded and relax your face, jaw, and belly. Let your body stop auditioning for thirty seconds." },
  { index: 20, content: "Take three slow breaths before answering the next message or request you receive." },
  { index: 21, content: "Place both hands low on your ribs and breathe into the word \"enough\" for ten breaths." },
  { index: 22, content: "Relax your jaw and soften your gaze while listening today." },
  { index: 23, content: "Feel your feet and ask, \"What can I offer from overflow, not depletion?\"" },
  { index: 24, content: "Sit with your palms facing up and breathe into the feeling of being received." },
  { index: 25, content: "Feel your feet, soften your jaw, and say one honest sentence out loud." },
  { index: 26, content: "Close your eyes and let one desire become an image. Notice what feeling lives inside it." },
  { index: 27, content: "Walk across the room as slowly as feels comfortable, noticing each shift of weight." },
  { index: 28, content: "Let your face make the expression it wants to make for ten seconds." },
  { index: 29, content: "Imagine welcoming back a younger or hidden part of yourself. Offer it one kind sentence." },
  { index: 30, content: "Bring your hands slowly toward your heart, stopping when the distance feels right." },
  { index: 31, content: "Think of a clear yes, then a clear no. Notice the difference in posture, breath, and sensation." },
  { index: 32, content: "Drink water slowly, noticing temperature, texture, swallowing, and breath." },
  { index: 33, content: "Draw a slow line with your finger on your palm, imagining a new path." },
  { index: 34, content: "Practice saying yes, no, and maybe out loud, noticing the body's response to each." },
  { index: 35, content: "Do one simple task, like washing your hands, with full reverence and attention." },
  { index: 36, content: "Press one hand into the other and feel your own steady contact." },
  { index: 37, content: "Place one hand on your chest and notice any emotion that rises without explaining it away." },
  { index: 38, content: "Name three things your body likes today, then let your shoulders drop after each one." },
  { index: 39, content: "Close your eyes and imagine your current mood as weather. Let it move without needing to stop it." },
  { index: 40, content: "Before your next yes, pause and feel your feet. Let your body vote too." },
  { index: 41, content: "Take a breath into your belly before naming one need out loud." },
  { index: 42, content: "Sit back slightly and notice what happens when you do not rush to fill silence." },
  { index: 43, content: "Let your belly soften and your breathing become visible for one minute." },
  { index: 44, content: "Put a hand where fear lives in your body and breathe as if making room around it." },
  { index: 45, content: "Let your arms hang open by your sides and breathe into the exposed feeling of wanting." },
  { index: 46, content: "Press your feet into the floor for ten breaths and notice the support under you." },
  { index: 47, content: "Place a hand on your heart and breathe as if comforting a dear friend." },
  { index: 48, content: "Put your hand on your heart and repeat, \"I can learn without attacking myself.\"" },
  { index: 49, content: "Place one hand over your heart and one over your belly. Ask each what it is ready to share." },
  { index: 50, content: "Take a slow walk and let your body choose the pace or direction for five minutes." },
  { index: 51, content: "Put away distractions and do one simple action slowly for two minutes." },
  { index: 52, content: "Look around and name the current year, your age, and where you are." },
  { index: 53, content: "Notice one pleasant sensation for thirty seconds without chasing more of it." },
  { index: 54, content: "Place both hands on your body and offer one sentence of gratitude." },
  { index: 55, content: "Place your hands on your thighs, feel their weight, and let yourself be supported." },
  { index: 56, content: "Open your palms and say, \"I can ask without controlling the answer.\"" },
  { index: 57, content: "Stand tall, inhale, and gently nod yes five times. Notice where your body participates." },
  { index: 58, content: "Place a hand on your forehead, then on your heart. Ask both places what they know." },
  { index: 59, content: "Press your palms together for ten breaths, feeling your own edges without pushing anyone away." },
  { index: 60, content: "Lean back in your chair and feel the support beneath you. Let your next decision slow down." },
  { index: 61, content: "Stand or sit tall and speak one clear sentence slowly, without apologizing for having a preference." },
  { index: 62, content: "Take one minute to breathe while imagining a daily thread connecting you to others." },
  { index: 63, content: "Lean slightly forward while keeping your breath slow and your body relaxed." },
  { index: 64, content: "Open and close your hands slowly while naming one thing you would like." },
  { index: 65, content: "Slowly relax your forehead, jaw, shoulders, hands, belly, and thighs." },
  { index: 66, content: "Press your feet into the floor and exhale through your mouth three times." },
  { index: 67, content: "Feel your back against a chair or wall and let support register through your body." },
  { index: 68, content: "Rest your gaze softly on one object for a minute, practicing gentle attention." },
  { index: 69, content: "Slow your exhale and wait ninety seconds before acting on a strong impulse." },
  { index: 70, content: "Pause before speaking and feel your seat, feet, and breath." },
  { index: 71, content: "Write one old rule in the air with your finger, then wipe it away." },
  { index: 72, content: "Wrap your arms around yourself and breathe into the sentence, \"Nothing human in me is outside compassion.\"" },
  { index: 73, content: "Open your hands and breathe with the phrase, \"I do not have to hold it all.\"" },
  { index: 74, content: "Lean back into a chair or wall and let yourself feel held by something outside you." },
  { index: 75, content: "Stand or sit with one hand on your heart and say, \"I am allowed to be in process.\"" },
  { index: 76, content: "Press your palms together for ten breaths, feeling your own edges without pushing anyone away." },
  { index: 77, content: "When you notice tension, whisper, \"Interesting.\" Then breathe into the area for five cycles." },
  { index: 78, content: "Lean back in your chair and feel the support beneath you. Let your next decision slow down." },
  { index: 79, content: "Stand or sit tall and speak one clear sentence slowly, without apologizing for having a preference." },
  { index: 80, content: "Take one minute to breathe while imagining a daily thread connecting you to others." },
  { index: 81, content: "Lean slightly forward while keeping your breath slow and your body relaxed." },
  { index: 82, content: "Set a timer for one minute and breathe into a mildly uncomfortable sensation without changing it." },
  { index: 83, content: "Feel your breath move slowly through your belly while imagining desire with patience." },
  { index: 84, content: "Inhale for four counts, exhale for six counts, repeating for two minutes." },
  { index: 85, content: "Let yourself smile for twenty seconds and notice whether your body permits it." },
  { index: 86, content: "Stroke your forearm slowly for thirty seconds, noticing the quality of contact." },
  { index: 87, content: "Take turns with a partner or friend naming one yes, one no, and one maybe." },
  { index: 88, content: "Shake your head no gently, then breathe and notice what settles." },
  { index: 89, content: "Place your hand on a surface nearby and notice texture for thirty seconds." },
  { index: 90, content: "During a moment of uncertainty, breathe low into your belly before acting." },
  { index: 91, content: "Write one private sentence beginning with, \"The truth is…\" Then breathe before deciding what to do with it." },
  { index: 92, content: "Choose one small act and do it as an offering, slowly and sincerely." },
  { index: 93, content: "Make a firm fist, then slowly open it. Notice the shift from force to care." },
  { index: 94, content: "Touch your throat and breathe before naming a feeling." },
  { index: 95, content: "Exhale with a soft sigh three times. Let each sigh release one role you no longer need today." },
  { index: 96, content: "Trace a slow circle over your heart or belly while naming one pattern you are ready to understand." },
  { index: 97, content: "Wrap your arms around yourself for thirty seconds and notice what kind of closure your body wants." },
  { index: 98, content: "Open your palms on your lap and breathe with the feeling of offering rather than grabbing." },
  { index: 99, content: "Place one hand on your heart and one outward, sensing both self and other." },
  { index: 100, content: "Inhale as if receiving warmth through the chest. Exhale without pushing it out." },
  { index: 101, content: "Stand in front of a mirror, soften your gaze, and say, \"I am allowed to be seen.\"" },
  { index: 102, content: "Stretch your arms overhead, then let them fall slowly as you exhale." },
  { index: 103, content: "Shake your hands, arms, shoulders, and legs for sixty seconds, then stand still." },
  { index: 104, content: "Hold one palm up for each feeling and breathe while letting both be present." },
  { index: 105, content: "Trace a small circle on your chest or palm while acknowledging one thing you have survived." },
  { index: 106, content: "Place both hands over your heart and inhale as if receiving warmth." },
  { index: 107, content: "Close your eyes and notice the first bodily response to a decision you are considering." },
  { index: 108, content: "Exhale slowly and say, \"Enough for this breath.\" Repeat five times." },
  { index: 109, content: "Act out the old response in your posture, then shift into the new one slowly." },
  { index: 110, content: "Stand tall and breathe from belly to chest, imagining your sexuality integrated with your whole body." },
  { index: 111, content: "Place a hand on your head or heart and offer yourself a quiet blessing." },
  { index: 112, content: "Rock gently from heel to toe until your weight settles evenly." },
  { index: 113, content: "Imagine warmth entering through your back, heart, or hands as you inhale." },
  { index: 114, content: "Sit still for two minutes and track your breath without changing it. Notice the part of you that stays with yourself." },
  { index: 115, content: "Scan from forehead to feet, pausing at each area that wants attention." },
  { index: 116, content: "Smile gently, even if it feels awkward, and breathe into the space around your heart." },
  { index: 117, content: "Put both feet on the floor and imagine stepping back into a circle at your own pace." },
  { index: 118, content: "Sit quietly for two minutes and listen to the sounds around you without naming them all." },
  { index: 119, content: "Sit quietly for two minutes and listen to the sounds around you without naming them all." },
];

export const bodyCheckIns = [
  { index: 0, prompt: "Where do I feel most like myself today, and where do I feel slightly edited?" },
  { index: 1, prompt: "What can I notice today without turning it into a project?" },
  { index: 2, prompt: "What boundary would help my body soften, not harden?" },
  { index: 3, prompt: "What wants to be said before I make it polished?" },
  { index: 4, prompt: "Where do I feel more myself in community, and where do I disappear?" },
  { index: 5, prompt: "What kind of reach feels possible without forcing myself?" },
  { index: 6, prompt: "What brave action feels possible, not performative?" },
  { index: 7, prompt: "Where do I feel wanting in my body today?" },
  { index: 8, prompt: "What sensation is asking for my attention, gently but clearly?" },
  { index: 9, prompt: "Where is this feeling in my body, and what shape does it have?" },
  { index: 10, prompt: "What pace would help my system trust today?" },
  { index: 11, prompt: "Can I feel myself and another person at the same time?" },
  { index: 12, prompt: "What answer appears before I start arguing with it?" },
  { index: 13, prompt: "What helps me return when I drift into past or future?" },
  { index: 14, prompt: "What is this protective part afraid would happen without it?" },
  { index: 15, prompt: "Where do I feel pressure to perform, and where do I feel curiosity?" },
  { index: 16, prompt: "Where do I feel supported by something beyond effort?" },
  { index: 17, prompt: "What kind of strength helps my body feel safe, not armored?" },
  { index: 18, prompt: "What softens when I stop bracing around this truth?" },
  { index: 19, prompt: "What tightens when I imagine being seen without performing?" },
  { index: 20, prompt: "What sensation tells me I am about to react instead of respond?" },
  { index: 21, prompt: "Where does my body say, \"That is enough for now\"?" },
  { index: 22, prompt: "Can I feel the difference between listening to answer and listening to understand?" },
  { index: 23, prompt: "Does my giving feel alive, pressured, resentful, or clean?" },
  { index: 24, prompt: "What part of me wants witness more than solutions?" },
  { index: 25, prompt: "Where does courage live in my body today?" },
  { index: 26, prompt: "What is the deeper need inside this desire?" },
  { index: 27, prompt: "Where does my body ask me to slow down today?" },
  { index: 28, prompt: "What expression has my body been holding back?" },
  { index: 29, prompt: "What part of me wants to come home?" },
  { index: 30, prompt: "What tells me my system feels ready for more closeness?" },
  { index: 31, prompt: "What does my body's yes feel like today?" },
  { index: 32, prompt: "What am I missing because I am already leaving?" },
  { index: 33, prompt: "What old expectation is shaping my response today?" },
  { index: 34, prompt: "Does my desire feel connected to choice, respect, and presence?" },
  { index: 35, prompt: "What ordinary thing feels more alive when I slow down?" },
  { index: 36, prompt: "What helps me remain with myself today?" },
  { index: 37, prompt: "What has touched me that I have not let myself feel fully?" },
  { index: 38, prompt: "What do I want that I usually make vague?" },
  { index: 39, prompt: "What is passing through me, and what is actually me?" },
  { index: 40, prompt: "Does this yes feel open, tight, rushed, or resigned?" },
  { index: 41, prompt: "Where do I feel the need in my body before I explain it?" },
  { index: 42, prompt: "Can I feel my body stay present while someone else takes up space?" },
  { index: 43, prompt: "Where do I perform to earn closeness, and what happens when I stop?" },
  { index: 44, prompt: "What does this fear need from me besides obedience?" },
  { index: 45, prompt: "What do I long for when I stop mocking myself?" },
  { index: 46, prompt: "Do I feel lifted, scattered, planted, braced, or steady?" },
  { index: 47, prompt: "What tenderness does this grief need from me?" },
  { index: 48, prompt: "What tone does my body relax around?" },
  { index: 49, prompt: "What layer of me wants witness today?" },
  { index: 50, prompt: "What nudge keeps returning when I get quiet?" },
  { index: 51, prompt: "How does my body feel when attention is divided?" },
  { index: 52, prompt: "What tells my body that this is now, not then?" },
  { index: 53, prompt: "Where is pleasure already present in a subtle way?" },
  { index: 54, prompt: "What part of my body is asking to be treated with more respect?" },
  { index: 55, prompt: "What support would make my strength sustainable?" },
  { index: 56, prompt: "Where does my body tense when I imagine asking?" },
  { index: 57, prompt: "What happens in my chest, belly, or throat when I let myself want what I want?" },
  { index: 58, prompt: "What am I assuming that my body has not confirmed?" },
  { index: 59, prompt: "What happens in my throat when I imagine saying no simply?" },
  { index: 60, prompt: "What part of me gets tense when repair matters more than winning?" },
  { index: 61, prompt: "What do I fear might happen if I let myself be included?" },
  { index: 62, prompt: "Who does my body remember with warmth today?" },
  { index: 63, prompt: "What sensation tells me I am using readiness as protection?" },
  { index: 64, prompt: "Does my desire feel clean, hidden, urgent, shy, or tangled?" },
  { index: 65, prompt: "What part of my body is ready to soften by five percent?" },
  { index: 66, prompt: "What boundary, value, or hurt is underneath this anger?" },
  { index: 67, prompt: "What kind of consistency would help me feel safer?" },
  { index: 68, prompt: "What kind of attention does my body trust?" },
  { index: 69, prompt: "Does this feel calm, rushed, grounded, or gripping?" },
  { index: 70, prompt: "Am I here, performing here, or thinking about being elsewhere?" },
  { index: 71, prompt: "What rule am I ready to question?" },
  { index: 72, prompt: "What happens in my body when shame is met with warmth?" },
  { index: 73, prompt: "Where does my body grip when I cannot know the answer yet?" },
  { index: 74, prompt: "What happens in my body when I let support in?" },
  { index: 75, prompt: "What feels exposed about being unfinished?" },
  { index: 76, prompt: "Where does my body already know something is not for me?" },
  { index: 77, prompt: "What becomes possible when I get curious instead of harsh?" },
  { index: 78, prompt: "Where am I rushing because I am afraid to disappoint someone?" },
  { index: 79, prompt: "What would my body do if I trusted clarity to be kind?" },
  { index: 80, prompt: "What simple ritual would help me feel less alone?" },
  { index: 81, prompt: "Do I feel curious, anxious, eager, or guarded as I move toward someone?" },
  { index: 82, prompt: "Can I stay with this sensation without making it an emergency?" },
  { index: 83, prompt: "Can I feel wanting without leaning forward too hard?" },
  { index: 84, prompt: "What does my breath reveal about my sense of safety today?" },
  { index: 85, prompt: "Where does joy show up physically when I let it?" },
  { index: 86, prompt: "What softens when I stop trying to force change?" },
  { index: 87, prompt: "Do I feel safe, stretched, pressured, curious, or shut down?" },
  { index: 88, prompt: "What happens when I let my no be enough?" },
  { index: 89, prompt: "What am I letting in today?" },
  { index: 90, prompt: "What does uncertainty make me want to do automatically?" },
  { index: 91, prompt: "What truth feels alive, tender, and deserving of care?" },
  { index: 92, prompt: "What does my body feel when I act from devotion instead of obligation?" },
  { index: 93, prompt: "What am I protecting, and am I protecting it with love?" },
  { index: 94, prompt: "What feeling wants to be spoken without sharp edges?" },
  { index: 95, prompt: "What part of me feels relieved when I stop pretending?" },
  { index: 96, prompt: "What does this pattern protect, and what might it be asking for now?" },
  { index: 97, prompt: "What do I need after connection so I do not abandon myself?" },
  { index: 98, prompt: "Does my request feel spacious, urgent, open, or gripping?" },
  { index: 99, prompt: "Can my body stay open when someone is not a mirror of me?" },
  { index: 100, prompt: "What blocks me from letting care land?" },
  { index: 101, prompt: "What happens in my body when I imagine being known more fully?" },
  { index: 102, prompt: "What expands in me when I admit I want more?" },
  { index: 103, prompt: "What changes after I let my body move first?" },
  { index: 104, prompt: "Can my body make room for more than one truth today?" },
  { index: 105, prompt: "What does this scar need: privacy, witness, gratitude, or rest?" },
  { index: 106, prompt: "What part of me resists being cared for?" },
  { index: 107, prompt: "What does my body know before my mind begins its presentation?" },
  { index: 108, prompt: "What part of me relaxes when I stop chasing the next moment?" },
  { index: 109, prompt: "What new response feels awkward but right?" },
  { index: 110, prompt: "Where do I split sexuality off from the rest of who I am?" },
  { index: 111, prompt: "What part of my becoming feels tender today?" },
  { index: 112, prompt: "What remains steady in me after intensity passes?" },
  { index: 113, prompt: "What part of me wants care but fears needing it?" },
  { index: 114, prompt: "What steadiness can I feel beneath today's noise?" },
  { index: 115, prompt: "What message is my body sending without using language?" },
  { index: 116, prompt: "What joy needs protection from overgiving, overthinking, or overaccess?" },
  { index: 117, prompt: "What soft feeling is hiding under my sharper reaction?" },
  { index: 118, prompt: "What would make returning feel safe enough today?" },
  { index: 119, prompt: "Can my body stay connected when nothing is being said?" },
];

export const conversationInvitations = [
  { index: 0, prompt: "Share one small truth about yourself that feels simple, real, and not polished for approval." },
  { index: 1, prompt: "Invite someone to share one thing they are noticing about themselves, without asking them to make it better." },
  { index: 2, prompt: "Share one boundary that helps you stay open instead of resentful." },
  { index: 3, prompt: "Share one conversation you want to begin more honestly, even if you do not have the whole speech yet." },
  { index: 4, prompt: "Share one quality that helps you feel safe in a community." },
  { index: 5, prompt: "Send a message that says something simple and real, like \"I thought of you today.\"" },
  { index: 6, prompt: "Share one small courageous action you are willing to take this week." },
  { index: 7, prompt: "Share one thing you want, without immediately apologizing for wanting it." },
  { index: 8, prompt: "Invite someone to answer with a body sensation instead of a concept." },
  { index: 9, prompt: "Share one emotion you are willing to name without making it your whole identity." },
  { index: 10, prompt: "Share one area where you are learning not to rush your own healing." },
  { index: 11, prompt: "Share one way you practice closeness without losing your own center." },
  { index: 12, prompt: "Share one inner signal you are learning to trust more." },
  { index: 13, prompt: "Invite someone to name one thing they can see, feel, or hear right now." },
  { index: 14, prompt: "Share one protective pattern with compassion rather than embarrassment." },
  { index: 15, prompt: "Share one way performance pressure has shaped how people relate to desire or pleasure." },
  { index: 16, prompt: "Share one practice, place, or moment that helps you feel part of a larger whole." },
  { index: 17, prompt: "Share one example of strength that does not look like domination or control." },
  { index: 18, prompt: "Share one honest sentence that feels vulnerable but not unsafe." },
  { index: 19, prompt: "Tell someone one place where you often feel tempted to perform confidence, ease, or certainty." },
  { index: 20, prompt: "Share one situation where you are practicing pausing before responding." },
  { index: 21, prompt: "Invite someone to name one place where \"enough\" is becoming clear." },
  { index: 22, prompt: "Invite someone to listen without interrupting or advising for two minutes." },
  { index: 23, prompt: "Invite someone to name one small gift they bring to a group simply by being themselves." },
  { index: 24, prompt: "Tell someone one thing you are sharing simply because you want to be heard." },
  { index: 25, prompt: "Tell someone one honest thing with warmth, not blame." },
  { index: 26, prompt: "Ask someone: \"What do you think you are really longing for underneath that?\"" },
  { index: 27, prompt: "Ask someone what they notice when they slow down instead of pushing through." },
  { index: 28, prompt: "Invite someone to answer honestly: \"What is your real mood today?\"" },
  { index: 29, prompt: "Invite someone to name one quality they are learning to reclaim." },
  { index: 30, prompt: "Ask someone how they know when closeness is moving too fast, too slow, or just right." },
  { index: 31, prompt: "Ask someone where they feel yes or no in their body." },
  { index: 32, prompt: "Share one ordinary moment you can experience without multitasking." },
  { index: 33, prompt: "Ask someone what they are learning to update about how connection works." },
  { index: 34, prompt: "Invite a conversation about how consent can feel warm, mutual, and human." },
  { index: 35, prompt: "Invite someone to name a small daily act that feels quietly meaningful." },
  { index: 36, prompt: "Invite someone to share one practice that helps them remain self-connected under pressure." },
  { index: 37, prompt: "Invite someone to share one thing that moved them recently." },
  { index: 38, prompt: "Share a preference you usually minimize, even if it feels small or inconvenient." },
  { index: 39, prompt: "Ask someone: \"What is the weather like inside you today?\" Receive the answer with curiosity." },
  { index: 40, prompt: "Share one way you are practicing getting your own consent before agreeing." },
  { index: 41, prompt: "Share one need directly, using \"I would appreciate\" or \"I am needing.\"" },
  { index: 42, prompt: "Ask someone a question that gives them space to share more of themselves." },
  { index: 43, prompt: "Invite someone into an ordinary moment, not a polished one." },
  { index: 44, prompt: "Invite someone to share one fear they are learning to face slowly." },
  { index: 45, prompt: "Share one longing in language that feels dignified, not dramatic." },
  { index: 46, prompt: "Invite someone to pause and feel their feet before answering a meaningful question." },
  { index: 47, prompt: "Share one loss, disappointment, or change you are honoring in a gentle way." },
  { index: 48, prompt: "Share one self-critical thought and rewrite it as something firm but kind." },
  { index: 49, prompt: "Share something true but appropriately sized, not your entire autobiography in one dramatic sitting." },
  { index: 50, prompt: "Share one intuitive nudge you can honor without needing dramatic certainty." },
  { index: 51, prompt: "Invite someone to choose one thing to do with full attention for five minutes." },
  { index: 52, prompt: "Share one sign that tells you that you have left the present and entered an old story." },
  { index: 53, prompt: "Share one non-explicit pleasure that helps you feel more alive in your body." },
  { index: 54, prompt: "Share one way you can relate to your body with more reverence today." },
  { index: 55, prompt: "Share one place where resilience needs rest, support, or tenderness." },
  { index: 56, prompt: "Share one ask that would feel vulnerable and respectful." },
  { index: 57, prompt: "Invite someone to name one honest yes they are noticing in their life right now." },
  { index: 58, prompt: "Share one interpretation you are holding lightly, instead of treating it as fact." },
  { index: 59, prompt: "Practice saying: \"I can't do that, but I appreciate you asking.\" Notice how it lands." },
  { index: 60, prompt: "Ask someone: \"Is there anything between us that wants a little care?\"" },
  { index: 61, prompt: "Share one small way you are willing to participate more fully today." },
  { index: 62, prompt: "Name one thing you appreciate about someone, specifically and without making it dramatic." },
  { index: 63, prompt: "Share one thing you can start imperfectly." },
  { index: 64, prompt: "Practice saying, \"I would like…\" and stop before the long legal disclaimer." },
  { index: 65, prompt: "Share one area of your body that tends to hold protection." },
  { index: 66, prompt: "Ask someone to talk about anger as information rather than danger." },
  { index: 67, prompt: "Ask someone what builds trust for them slowly and specifically." },
  { index: 68, prompt: "Invite someone to describe what kind of attention feels good to them." },
  { index: 69, prompt: "Invite someone to discuss how intuition feels different from anxiety in their body." },
  { index: 70, prompt: "Before your next conversation, take one breath and feel your body in the room." },
  { index: 71, prompt: "Invite someone to name one rule they learned that may no longer serve them." },
  { index: 72, prompt: "Invite someone to reflect on how shame affects connection without requiring personal disclosure." },
  { index: 73, prompt: "Ask someone what they are learning to trust even without full clarity." },
  { index: 74, prompt: "Ask someone for one small form of help, feedback, or encouragement." },
  { index: 75, prompt: "Share something you are learning, not something you have mastered." },
  { index: 76, prompt: "Share one gentle no you are practicing, or one place you are learning not to override yourself." },
  { index: 77, prompt: "Invite someone to share a habit they are trying to understand, not shame." },
  { index: 78, prompt: "Ask someone: \"Can I take a little time and come back to you?\" Then honor the pause." },
  { index: 79, prompt: "Share one expectation or preference with simple, respectful language." },
  { index: 80, prompt: "Invite someone to join you in a small repeated practice, like a check-in, walk, or weekly question." },
  { index: 81, prompt: "Ask a question that invites depth without forcing disclosure." },
  { index: 82, prompt: "Ask someone how they stay kind to themselves when a moment gets uncomfortable." },
  { index: 83, prompt: "Invite someone to talk about the difference between wanting and pressuring." },
  { index: 84, prompt: "Invite someone to take three shared breaths with you, in person or virtually." },
  { index: 85, prompt: "Share one ordinary thing that gave you a little spark of pleasure." },
  { index: 86, prompt: "Share one place where you are practicing a softer approach with yourself." },
  { index: 87, prompt: "Invite someone to discuss what makes closeness feel mutual, not assumed." },
  { index: 88, prompt: "Invite someone to discuss one area where their no does not need to be justified to be valid." },
  { index: 89, prompt: "Share one detail from your day that moved you, even slightly." },
  { index: 90, prompt: "Share one attachment move you notice in yourself, without shaming it." },
  { index: 91, prompt: "Invite someone to share a general reflection on what makes erotic honesty feel safe." },
  { index: 92, prompt: "Invite someone to name one devotion that shapes their daily choices." },
  { index: 93, prompt: "Share one thing you are willing to protect with action, not just intention." },
  { index: 94, prompt: "Share a feeling using the format, \"I feel…, and I am not blaming you for it.\"" },
  { index: 95, prompt: "Ask someone: \"What is one role you are tired of playing?\" Then listen without fixing it." },
  { index: 96, prompt: "Share one relational pattern you are beginning to recognize with more compassion." },
  { index: 97, prompt: "Offer someone a low-pressure invitation to connect, talk, walk, or check in." },
  { index: 98, prompt: "Offer someone a low-pressure invitation to connect, talk, walk, or check in." },
  { index: 99, prompt: "Ask someone about an experience or perspective different from yours, and listen without comparing." },
  { index: 100, prompt: "Practice receiving a compliment with only \"Thank you\" and a breath." },
  { index: 101, prompt: "Share something meaningful that you usually keep hidden because it feels \"too much.\"" },
  { index: 102, prompt: "Share one place where you are allowing yourself to want more truth, touch, care, or aliveness." },
  { index: 103, prompt: "Share one way your body likes to move when words are not enough." },
  { index: 104, prompt: "Share a sentence that begins, \"Part of me feels…, and part of me feels…\"" },
  { index: 105, prompt: "Share one thing you survived that you are learning to hold with more dignity." },
  { index: 106, prompt: "Practice letting one kind word, touch, or gesture land before deflecting it." },
  { index: 107, prompt: "Ask someone: \"What do you know beneath the explanation?\"" },
  { index: 108, prompt: "Invite someone to complete the sentence, \"For this moment, enough is…\"" },
  { index: 109, prompt: "Ask someone what response they are practicing in relationships right now." },
  { index: 110, prompt: "Invite someone to discuss what integrated sexuality means to them in a grounded way." },
  { index: 111, prompt: "Share one change you are moving through that you want to honor gently." },
  { index: 112, prompt: "Invite someone to name one way they return to center after intensity." },
  { index: 113, prompt: "Practice letting someone's kindness matter for a full breath before minimizing it." },
  { index: 114, prompt: "Share one steady thing about yourself that you are learning to trust." },
  { index: 115, prompt: "Ask someone: \"Where do you notice your body speaking before you have words?\"" },
  { index: 116, prompt: "Invite someone to name one pleasure, routine, or relationship they want to protect with better boundaries." },
  { index: 117, prompt: "Share one sentence that begins, \"The tender part for me is…\"" },
  { index: 118, prompt: "Share one small way you might reconnect with a group, friend, or practice you miss." },
  { index: 119, prompt: "Spend a few quiet minutes with someone without rushing to fill the space." },
];

export const quotes = [
  { index: 0, text: "Your truth does not need a costume. Let it arrive in regular clothes.", author: "Trevor James" },
  { index: 1, text: "Awareness is not a repair shop. Sometimes the most honest medicine is simply turning the lights on.", author: "Trevor James" },
  { index: 2, text: "A boundary is not a wall against connection. It is the doorway that tells love how to enter respectfully.", author: "Trevor James" },
  { index: 3, text: "The first sentence does not have to be perfect. It only has to open the room where truth can breathe.", author: "Trevor James" },
  { index: 4, text: "Belonging is not fitting into a room by shrinking. It is finding the rooms where your full breath is welcome.", author: "Trevor James" },
  { index: 5, text: "Connection is often built from tiny bridges. The small reach counts, even when it does not come with fireworks.", author: "Trevor James" },
  { index: 6, text: "Courage usually arrives in inches, not cinematic speeches. Take the inch and let it count.", author: "Trevor James" },
  { index: 7, text: "Desire is not a problem just because it has a pulse. Sometimes wanting is the body remembering it is alive.", author: "Trevor James" },
  { index: 8, text: "The body is always happening now. That is why it is such a useful place to return.", author: "Trevor James" },
  { index: 9, text: "Feelings are visitors with information. They do not need to move in and redecorate the entire house.", author: "Trevor James" },
  { index: 10, text: "Healing is not a productivity sprint with incense nearby. It moves at the speed of safety.", author: "Trevor James" },
  { index: 11, text: "Intimacy is not fusion. The most beautiful closeness still leaves room for two nervous systems.", author: "Trevor James" },
  { index: 12, text: "Intuition is rarely the loudest voice in the room. It is often the one still speaking after the noise leaves.", author: "Trevor James" },
  { index: 13, text: "Presence is not a personality trait. It is a repeated return to the life actually happening.", author: "Trevor James" },
  { index: 14, text: "Every defense has a biography. Before you fire it, learn what job it thought it was doing.", author: "Trevor James" },
  { index: 15, text: "Sexuality is not an audition. The body does not need applause to deserve tenderness.", author: "Trevor James" },
  { index: 16, text: "Spirituality does not always arrive wearing robes. Sometimes it is the quiet sense that you are not carrying everything alone.", author: "Trevor James" },
  { index: 17, text: "Real strength does not always clench. Sometimes it exhales, listens, and stays.", author: "Trevor James" },
  { index: 18, text: "Vulnerability is not spilling everything. It is letting one true thing breathe where it can be respected.", author: "Trevor James" },
  { index: 19, text: "Performance can get applause, but it rarely gets held. The self underneath is the one connection can actually meet.", author: "Trevor James" },
  { index: 20, text: "The pause is small, but it is not weak. It is where your wiser self gets a word in.", author: "Trevor James" },
  { index: 21, text: "Enough is not a failure of generosity. It is often your body telling the truth before your politeness catches up.", author: "Trevor James" },
  { index: 22, text: "Listening is not waiting for your turn to be impressive. It is letting another person become more real in your presence.", author: "Trevor James" },
  { index: 23, text: "Community does not require you to become the emergency generator. Your presence can matter without draining the whole battery.", author: "Trevor James" },
  { index: 24, text: "Being met is different from being handled. One makes room for your humanity, the other tries to tidy it away.", author: "Trevor James" },
  { index: 25, text: "A shaking voice can still be a true voice. Courage does not require perfect lighting.", author: "Trevor James" },
  { index: 26, text: "Desire often points beyond the thing. Follow it gently, and it may show you a deeper hunger.", author: "Trevor James" },
  { index: 27, text: "Slowness is not laziness. Sometimes it is the doorway where wisdom finally catches up with the schedule.", author: "Trevor James" },
  { index: 28, text: "Your real mood is allowed in the room. It does not have to be charming to deserve care.", author: "Trevor James" },
  { index: 29, text: "The parts we exile do not disappear. They wait for a safer home inside us.", author: "Trevor James" },
  { index: 30, text: "Intimacy has a pace, and the body usually knows it before the calendar does.", author: "Trevor James" },
  { index: 31, text: "The body has its own language. Learning it may save you from several unnecessary committee meetings in your head.", author: "Trevor James" },
  { index: 32, text: "The present is not always exciting. It is, however, where your life keeps insisting on meeting you.", author: "Trevor James" },
  { index: 33, text: "The nervous system loves old maps. Healing asks whether the road has changed since the map was drawn.", author: "Trevor James" },
  { index: 34, text: "Consent does not kill desire. It gives desire somewhere trustworthy to land.", author: "Trevor James" },
  { index: 35, text: "The sacred is not always elsewhere. It is often hiding in plain sight, waiting for us to stop rushing past it.", author: "Trevor James" },
  { index: 36, text: "Strength is not never wobbling. It is learning how to come back without leaving yourself behind.", author: "Trevor James" },
  { index: 37, text: "Being impacted does not make you fragile. It means your heart has not been laminated.", author: "Trevor James" },
  { index: 38, text: "Specificity is not a problem to solve. It is the doorway where real people can find you.", author: "Trevor James" },
  { index: 39, text: "You are not the weather. You are the sky learning not to panic every time clouds gather.", author: "Trevor James" },
  { index: 40, text: "Consent is not only something we offer others. It is also something we owe ourselves.", author: "Trevor James" },
  { index: 41, text: "A need spoken cleanly is less heavy than a resentment carried beautifully. Say the thing before it grows teeth.", author: "Trevor James" },
  { index: 42, text: "A generous room is not quiet because people are small. It is spacious because people are allowed to arrive at their own pace.", author: "Trevor James" },
  { index: 43, text: "The ordinary self is wildly underrated. It is usually the one most capable of being loved.", author: "Trevor James" },
  { index: 44, text: "Fear can sit at the table, but it does not get to hold the only microphone.", author: "Trevor James" },
  { index: 45, text: "Longing is not neediness wearing a bad outfit. It is the heart reaching toward what matters.", author: "Trevor James" },
  { index: 46, text: "Grounding is not glamorous, which is rude of it. It is also one of the most reliable forms of magic we have.", author: "Trevor James" },
  { index: 47, text: "Grief does not always arrive with a dramatic soundtrack. Sometimes it just quietly asks for a chair.", author: "Trevor James" },
  { index: 48, text: "An inner critic can be very committed and terribly underqualified. You are allowed to hire a kinder manager.", author: "Trevor James" },
  { index: 49, text: "Intimacy is not dumping the whole attic on the lawn. It is opening doors with care.", author: "Trevor James" },
  { index: 50, text: "You do not need a thunderclap to trust a signal. Sometimes the next right step is a whisper with good timing.", author: "Trevor James" },
  { index: 51, text: "Multitasking often makes us feel powerful and secretly scattered. One thing at a time is humble medicine.", author: "Trevor James" },
  { index: 52, text: "A trigger is not proof that you are broken. It is time travel without consent, and it needs grounding.", author: "Trevor James" },
  { index: 53, text: "Pleasure is information, not a character flaw. Listen carefully and it may tell you where life is trying to return.", author: "Trevor James" },
  { index: 54, text: "The body is not an obstacle to spirit. It is one of the places spirit keeps showing up.", author: "Trevor James" },
  { index: 55, text: "Endurance without care becomes depletion with better branding. Strength needs replenishment too.", author: "Trevor James" },
  { index: 56, text: "Asking is vulnerable because it lets reality answer. It is also how hidden needs become human-sized.", author: "Trevor James" },
  { index: 57, text: "A true yes has a different sound in the body. It does not need to shout, it simply does not leave.", author: "Trevor James" },
  { index: 58, text: "The mind loves a dramatic narrator. Awareness lets us check whether the script is actually true.", author: "Trevor James" },
  { index: 59, text: "A kind no does not need a courtroom defense. It can be brief, warm, and complete.", author: "Trevor James" },
  { index: 60, text: "Winning can leave two people lonely. Repair asks a better question: how do we return without pretending nothing happened?", author: "Trevor James" },
  { index: 61, text: "Participation is not a personality type. Sometimes it is one shy step toward the fire.", author: "Trevor James" },
  { index: 62, text: "Connection does not always begin from zero. Sometimes it is already there, waiting for a little attention.", author: "Trevor James" },
  { index: 63, text: "Readiness is lovely when it arrives. It is also a terrible gatekeeper when your life is waiting outside.", author: "Trevor James" },
  { index: 64, text: "A clean ask gives desire a chance to meet reality. It is kinder than hoping someone reads the invisible memo.", author: "Trevor James" },
  { index: 65, text: "Armor once helped you survive. You can thank it without wearing it to breakfast forever.", author: "Trevor James" },
  { index: 66, text: "Anger is not automatically wisdom, but it is rarely random. Listen before you hand it the steering wheel.", author: "Trevor James" },
  { index: 67, text: "Trust does not return because we demand it. It returns when care becomes consistent enough to believe.", author: "Trevor James" },
  { index: 68, text: "Attention can be a spotlight or a warm lamp. Intimacy usually prefers the lamp.", author: "Trevor James" },
  { index: 69, text: "Intuition usually has breath in it. Urgency often comes with a tiny marching band and a clipboard.", author: "Trevor James" },
  { index: 70, text: "A conversation changes when we actually arrive for it. Half-presence is still a kind of absence.", author: "Trevor James" },
  { index: 71, text: "Many of us are living by contracts we never consciously signed. You are allowed to renegotiate.", author: "Trevor James" },
  { index: 72, text: "Shame thrives in secrecy and harsh lighting. Bring warmth, and it starts losing its dramatic flair.", author: "Trevor James" },
  { index: 73, text: "Not knowing is uncomfortable, but it is not empty. Mystery has its own kind of company.", author: "Trevor James" },
  { index: 74, text: "Receiving is not weakness. It is the part of strength that remembers we are not appliances.", author: "Trevor James" },
  { index: 75, text: "You do not have to arrive fully edited. Some connections are built in the honest middle.", author: "Trevor James" },
  { index: 76, text: "You do not have to arrive fully edited. Some connections are built in the honest middle.", author: "Trevor James" },
  { index: 77, text: "Judgment slams the door. Curiosity leaves it cracked open enough for change to enter.", author: "Trevor James" },
  { index: 78, text: "Pressure makes the nervous system perform certainty. Space lets real choice come forward.", author: "Trevor James" },
  { index: 79, text: "Clarity does not have to wear armor. It can be direct, warm, and mercifully free of riddles.", author: "Trevor James" },
  { index: 80, text: "Community grows through repetition. Not dramatic repetition, just the sacred little again and again.", author: "Trevor James" },
  { index: 81, text: "Curiosity says, \"I do not already know you.\" That is one of the kindest things we can offer another person.", author: "Trevor James" },
  { index: 82, text: "Courage is not the absence of discomfort. It is the decision not to abandon yourself the moment discomfort enters.", author: "Trevor James" },
  { index: 83, text: "Desire does not have to become a bulldozer. It can be warm, alive, and still deeply respectful.", author: "Trevor James" },
  { index: 84, text: "Breath is the body's quiet vote for staying. Each inhale says, \"Still here.\"", author: "Trevor James" },
  { index: 85, text: "Joy does not need perfect conditions. It is stubborn, thank God, and sometimes shows up in sweatpants.", author: "Trevor James" },
  { index: 86, text: "Gentleness is not weak. It is often what finally reaches the places force could only frighten.", author: "Trevor James" },
  { index: 87, text: "Safety is not the opposite of desire. It is often the ground where desire can finally stop clenching.", author: "Trevor James" },
  { index: 88, text: "A no does not become real only after everyone understands it. Your body's boundary is already data.", author: "Trevor James" },
  { index: 89, text: "Presence lets the world leave fingerprints on us. That is not weakness, it is participation.", author: "Trevor James" },
  { index: 90, text: "Attachment patterns are not moral failures. They are nervous system strategies looking for safer options.", author: "Trevor James" },
  { index: 91, text: "Erotic honesty begins with not lying to yourself. Disclosure can wait until respect and readiness are in the room.", author: "Trevor James" },
  { index: 92, text: "Devotion is love with a calendar. It is what we return to when feelings wander.", author: "Trevor James" },
  { index: 93, text: "Strength becomes meaningful when it protects what is tender, true, and worth keeping alive.", author: "Trevor James" },
  { index: 94, text: "Tender honesty is truth with its shoes off. It enters carefully because it wants connection, not conquest.", author: "Trevor James" },
  { index: 95, text: "Pretending is expensive, even when nobody notices the bill. Your nervous system keeps the receipts.", author: "Trevor James" },
  { index: 96, text: "A pattern is not a life sentence. It is a clue that has been waiting for gentler attention.", author: "Trevor James" },
  { index: 97, text: "Boundaries are not only for beginnings. Sometimes the most loving boundary is how we come back home afterward.", author: "Trevor James" },
  { index: 98, text: "An invitation leaves room for another person's freedom. That is why a real yes can find it.", author: "Trevor James" },
  { index: 99, text: "A mature community does not require sameness. It asks whether we can stay human while being different.", author: "Trevor James" },
  { index: 100, text: "Many of us are better at chasing connection than receiving it. Let the good thing arrive before you explain it away.", author: "Trevor James" },
  { index: 101, text: "Being seen is risky because it ends the fantasy of total control. It also begins the possibility of real contact.", author: "Trevor James" },
  { index: 102, text: "Wanting more does not make you ungrateful. Sometimes it means your soul has stopped living on crumbs.", author: "Trevor James" },
  { index: 103, text: "The mind can explain stuckness beautifully. The body often prefers that we shake, stretch, walk, or dance it loose.", author: "Trevor James" },
  { index: 104, text: "Mixed feelings are not a lack of clarity. Sometimes they are proof that you are telling the whole truth.", author: "Trevor James" },
  { index: 105, text: "A scar is not proof that you are broken. It is evidence that something in you kept going.", author: "Trevor James" },
  { index: 106, text: "Receiving is an intimacy skill. Many of us need practice not swatting away the very care we asked for.", author: "Trevor James" },
  { index: 107, text: "The mind explains. The body reveals. We need both, but not always in that order.", author: "Trevor James" },
  { index: 108, text: "Enough for now is not giving up. It is giving your nervous system a place to sit down.", author: "Trevor James" },
  { index: 109, text: "Change often begins as rehearsal. The new self needs practice before opening night.", author: "Trevor James" },
  { index: 110, text: "Sexuality does not have to live in the basement of the self. It can come upstairs and sit with the rest of your life.", author: "Trevor James" },
  { index: 111, text: "You are not only a project under construction. You are a becoming worthy of blessing along the way.", author: "Trevor James" },
  { index: 112, text: "Steadiness is not pretending the storm did not happen. It is finding your feet in the wet grass afterward.", author: "Trevor James" },
  { index: 113, text: "Care can feel risky when you are used to surviving without it. Let it approach at the speed your body can trust.", author: "Trevor James" },
  { index: 114, text: "Authenticity is not a perfect mood. It is the part of you that keeps quietly returning.", author: "Trevor James" },
  { index: 115, text: "The body rarely speaks in paragraphs. It speaks in tightening, softening, heat, breath, and the sudden need to leave.", author: "Trevor James" },
  { index: 116, text: "Boundaries are not only built around wounds. They can also guard the tender places where joy is growing.", author: "Trevor James" },
  { index: 117, text: "Tenderness often arrives wearing terrible disguises. Communication helps it take off the fake mustache.", author: "Trevor James" },
  { index: 118, text: "You do not have to return with a grand speech. Sometimes belonging begins again with hello.", author: "Trevor James" },
  { index: 119, text: "Silence is not always absence. Sometimes it is the room two nervous systems need to recognize each other.", author: "Trevor James" },
];

export const weeklyTrevorNotes = [
  {
    week: 1,
    title: "Week One: Welcome",
    body: "Welcome to the journey. What you're about to experience is not a program—it's an invitation to remember what you already know. The Connection Room was built because I believe that the deepest part of human experience happens in moments of genuine connection, vulnerable honesty, and embodied presence. Over the next weeks, you'll be met with reflections, practices, and conversations designed to wake you up to what's already alive in you. Trust the process. Trust yourself.",
    prompt_snapshot: "Receiving Without Defending",
    space_suggestion: "Find a safe person to share one true thing.",
  },
  {
    week: 2,
    title: "Week Two: Softening",
    body: "By now you might notice something: the walls you built to keep you safe are also keeping you lonely. There's nothing wrong with that. Those walls protected you when you needed them. But what if they're no longer necessary? This week is about gently lowering them—not all at once, but slowly, with kindness. Notice what happens when you soften. Watch who shows up differently. Feel what becomes possible.",
    prompt_snapshot: "Softness as Strength",
    space_suggestion: "Connect with someone you trust about what protecting yourself has cost.",
  },
  {
    week: 3,
    title: "Week Three: Desire",
    body: "We've learned to be ashamed of wanting. We're taught that desire is dangerous, that hunger is greed, that need is weakness. But your desire is your truth. It's the compass pointing toward what matters most. This week, stop apologizing for wanting. Ask yourself what you really want—not what you think you should want, but what actually calls to you. The answer might surprise you.",
    prompt_snapshot: "Desire Without Shame",
    space_suggestion: "Share one desire with someone you trust.",
  },
  {
    week: 4,
    title: "Week Four: Presence",
    body: "In a world that prizes productivity, presence is radical. Presence means being here, now, fully. Not thinking about what comes next or what you should be doing. Just here. With yourself, with others, with this moment. This week, practice being present. Notice how rare it is. Notice how everything changes when you are.",
    prompt_snapshot: "Presence as a Practice",
    space_suggestion: "Sit with someone for 15 minutes with no phones or distractions.",
  },
  {
    week: 5,
    title: "Week Five: Vulnerability",
    body: "Vulnerability is not weakness. It's the only path to real connection. This week, tell someone the truth. Show someone the part of you that you've been keeping hidden. You don't need permission. You don't need to be perfect. You just need to be real. Watch what happens when you risk being seen.",
    prompt_snapshot: "The Courage to Be Seen",
    space_suggestion: "Share something vulnerable and notice who can hold it.",
  },
  {
    week: 6,
    title: "Week Six: Embodiment",
    body: "You live in your body, but do you inhabit it? This week, come home to your physical self. Feel your breath, your heartbeat, your aliveness. Your body has been trying to tell you things your mind hasn't listened to. Maybe it's time to pay attention. What is your body trying to teach you?",
    prompt_snapshot: "The Body as a Home",
    space_suggestion: "Move your body in a way that feels good and notice what it reveals.",
  },
  {
    week: 7,
    title: "Week Seven: Touch",
    body: "Touch is how we remember we're not alone. In a world that sometimes feels isolating, a hand on your shoulder, a hug, the closeness of another person—these are medicine. This week, give and receive touch with intention. Let it be an act of connection, of presence, of being seen. Notice what healing is possible through this simple act.",
    prompt_snapshot: "Touch Without Obligation",
    space_suggestion: "Give or receive one intentional hug—be present in it.",
  },
  {
    week: 8,
    title: "Week Eight: Authenticity",
    body: "There is an exhaustion that comes from being inauthentic. You know it. The moment you stop pretending is the moment you finally arrive. This week, be yourself. Just yourself, fully, without apology. The people worth keeping will stay. The ones who leave are making space for people who love your actual self. That's not a loss. That's freedom.",
    prompt_snapshot: "What Happens When You Stop Performing",
    space_suggestion: "Be fully yourself around someone and notice what shifts.",
  },
  {
    week: 9,
    title: "Week Nine: Receiving",
    body: "We've been taught that giving is better than receiving. But receiving is the other half of connection. This week, let someone help you. Let someone care for you. Let yourself be wanted, not needed, but wanted for exactly who you are. Notice the discomfort. Notice what happens when you let it pass.",
    prompt_snapshot: "Receiving Without Defending",
    space_suggestion: "Ask someone for help and let them say yes.",
  },
  {
    week: 10,
    title: "Week Ten: Communication",
    body: "Real communication is terrifying. You have to risk being misunderstood. You have to be clear about what you want and need. You have to ask. But ask you must. This week, say something you've been afraid to say. Ask for something you've been afraid to ask for. The courage is in the asking itself.",
    prompt_snapshot: "The Courage to Ask",
    space_suggestion: "Have a conversation where you ask for what you really need.",
  },
  {
    week: 11,
    title: "Week Eleven: Intimacy",
    body: "Intimacy is not always sexual, but it is always vulnerable. It's knowing and being known. It's the moment when the walls finally come down and you realize you're safe. This week, create a moment of real intimacy—with yourself, with a partner, with a friend. Notice how rare these moments are. Cherish them. Make them more common.",
    prompt_snapshot: "Intimacy Without Urgency",
    space_suggestion: "Create one moment where there's nowhere to be but here.",
  },
  {
    week: 12,
    title: "Week Twelve: Belonging",
    body: "You belong. Not because you've earned it, not because you're perfect, but because you exist. This week, find the people and places where you feel that to be true. Cherish them. And when you don't feel that sense of belonging, remember: the work is not to change yourself to fit in, but to find your actual tribe. They're looking for you too.",
    prompt_snapshot: "What It Means to Belong",
    space_suggestion: "Spend time with people who make you feel like you belong.",
  },
  {
    week: 13,
    title: "Week Thirteen: Integration",
    body: "By now you've done real work. You've softened, wanted, spoken truth, felt desire, been present. But these are not destinations—they're practices. This week is about integration. How do you take what you've discovered and make it real in your actual life? How do you stay awake to connection and presence and vulnerability even when the world pushes back?",
    prompt_snapshot: "When Vulnerability Is Revolutionary",
    space_suggestion: "Notice where you're still performing—and choose one place to stop.",
  },
  {
    week: 14,
    title: "Week Fourteen: Renewal",
    body: "The journey doesn't end. But this cycle does. And renewal is the opportunity to ask: what have I learned? What do I want to keep? What do I want to change? Use this week to reflect. Use this week to recommit. Use this week to remember that this is not about being perfect. It's about being honest.",
    prompt_snapshot: "Permission to Be Whole",
    space_suggestion: "Reflect on what's changed—and share it with someone.",
  },
  {
    week: 15,
    title: "Week Fifteen: Onward",
    body: "You are not the same person who started. You've been cracked open, and the light came in. Now the real work begins—the work of staying open, of choosing vulnerability even when fear shows up, of deepening your presence, of building real connection. You have everything you need. Trust yourself. And know that in choosing connection, you are choosing to be fully alive.",
    prompt_snapshot: "The Courage of Showing Up",
    space_suggestion: "Commit to one way you'll stay open moving forward.",
  },
  {
    week: 16,
    title: "Week Sixteen: Return",
    body: "The journey comes full circle. You return to the beginning, but you are different now. The Receiving Without Defending looks different when you've done this work. Notice what's changed. Notice what you see now that you couldn't see before. And remember: this is the beginning of something. Not the end. Welcome home.",
    prompt_snapshot: "The Gift of Returning",
    space_suggestion: "Begin again, knowing what you know now.",
  },
];
