/**
 * Daily Companion Content Seed Data
 *
 * This file seeds the database with:
 * - 120 daily themes
 * - 120 reflection prompts
 * - 120 embodiment practices
 * - 120 body check-ins
 * - 120 conversation invitations
 * - 120 quotes
 * - 16 weekly Trevor notes
 *
 * Content is organized by rotation_index (days since app launch).
 * All content is seeded in Trevor James' voice:
 * warm, grounded, compassionate, mature, slightly poetic but clear.
 */

export const dailyThemes = [
  { index: 0, title: "Receiving Without Defending", category: "connection" },
  { index: 1, title: "Letting Yourself Be Known", category: "vulnerability" },
  { index: 2, title: "The Courage to Ask", category: "communication" },
  { index: 3, title: "What Your Body Has Been Holding", category: "embodiment" },
  { index: 4, title: "Friendship Without Performance", category: "connection" },
  { index: 5, title: "Desire Without Shame", category: "sexuality" },
  { index: 6, title: "Touch Without Obligation", category: "intimacy" },
  { index: 7, title: "Resting the Armor", category: "vulnerability" },
  { index: 8, title: "The Difference Between Privacy and Hiding", category: "authenticity" },
  { index: 9, title: "Making Room for Wanting", category: "desire" },
  { index: 10, title: "Presence as a Practice", category: "embodiment" },
  { index: 11, title: "The Body as a Home", category: "embodiment" },
  { index: 12, title: "Listening Without Fixing", category: "communication" },
  { index: 13, title: "Permission to Feel", category: "emotion" },
  { index: 14, title: "Slow Down. You're Safe Here.", category: "presence" },
  { index: 15, title: "Softness as Strength", category: "vulnerability" },
  { index: 16, title: "The Courage of Honesty", category: "authenticity" },
  { index: 17, title: "What It Means to Belong", category: "connection" },
  { index: 18, title: "Release What You've Been Protecting", category: "vulnerability" },
  { index: 19, title: "The Language Your Body Speaks", category: "embodiment" },
  { index: 20, title: "Being Wanted, Not Needed", category: "intimacy" },
  { index: 21, title: "The Gift of Asking for Help", category: "vulnerability" },
  { index: 22, title: "Desire as Information", category: "desire" },
  { index: 23, title: "What Happens When You Stop Performing", category: "authenticity" },
  { index: 24, title: "Breath as Home", category: "embodiment" },
  { index: 25, title: "The Bravery in Being Ordinary", category: "authenticity" },
  { index: 26, title: "Touch Across Boundaries", category: "intimacy" },
  { index: 27, title: "Speaking Your Truth Softly", category: "communication" },
  { index: 28, title: "The Body's Wisdom", category: "embodiment" },
  { index: 29, title: "Longing is Information", category: "desire" },
  { index: 30, title: "Invitation and Consent", category: "communication" },
  { index: 31, title: "What Real Support Looks Like", category: "connection" },
  { index: 32, title: "The Courage to Be Seen", category: "vulnerability" },
  { index: 33, title: "Intimacy Without Urgency", category: "intimacy" },
  { index: 34, title: "The Quiet Strength of Presence", category: "presence" },
  { index: 35, title: "Healing the Abandonment Inside", category: "emotion" },
  { index: 36, title: "When Defenses Are Love", category: "psychology" },
  { index: 37, title: "The Truth in Your Hesitation", category: "intuition" },
  { index: 38, title: "Belonging to Yourself First", category: "authenticity" },
  { index: 39, title: "The Grace of Slowing Down", category: "presence" },
  { index: 40, title: "Noticing Without Judgment", category: "awareness" },
  { index: 41, title: "The Intimacy of Being Heard", category: "connection" },
  { index: 42, title: "What Softening Teaches Us", category: "vulnerability" },
  { index: 43, title: "The Body Never Lies", category: "embodiment" },
  { index: 44, title: "Permission to Grieve", category: "emotion" },
  { index: 45, title: "Asking Without Shame", category: "communication" },
  { index: 46, title: "The Space Between Souls", category: "spirituality" },
  { index: 47, title: "What It Means to Come Home", category: "presence" },
  { index: 48, title: "Desire as Prayer", category: "spirituality" },
  { index: 49, title: "The Bravery of Vulnerability", category: "courage" },
  { index: 50, title: "Tenderness as a Way of Being", category: "authenticity" },
  { index: 51, title: "The Gift of Attention", category: "connection" },
  { index: 52, title: "Breaking the Silence Inside", category: "authenticity" },
  { index: 53, title: "The Courage to Rest", category: "presence" },
  { index: 54, title: "What You're Really Asking For", category: "communication" },
  { index: 55, title: "The Sacred in the Ordinary", category: "spirituality" },
  { index: 56, title: "When Vulnerability Is Revolutionary", category: "courage" },
  { index: 57, title: "The Language of the Body", category: "embodiment" },
  { index: 58, title: "Connection as Medicine", category: "healing" },
  { index: 59, title: "The Truth of Your Longing", category: "desire" },
  { index: 60, title: "Permission to Be Whole", category: "authenticity" },
  { index: 61, title: "The Wisdom of Boundaries", category: "communication" },
  { index: 62, title: "Being Known, Being Loved", category: "intimacy" },
  { index: 63, title: "The Courage to Start Again", category: "healing" },
  { index: 64, title: "Presence as an Act of Love", category: "connection" },
  { index: 65, title: "The Sacred Pause", category: "embodiment" },
  { index: 66, title: "What Shame Wants You to Know", category: "emotion" },
  { index: 67, title: "The Intimacy of Trust", category: "vulnerability" },
  { index: 68, title: "Your Body as Guidance", category: "embodiment" },
  { index: 69, title: "The Grace of Asking", category: "communication" },
  { index: 70, title: "Belonging Without Performing", category: "authenticity" },
  { index: 71, title: "The Bravery in Gentleness", category: "strength" },
  { index: 72, title: "Deepening Your Breath", category: "embodiment" },
  { index: 73, title: "The Medicine of Being Seen", category: "healing" },
  { index: 74, title: "Desire Without Desperation", category: "desire" },
  { index: 75, title: "The Courage to Be Still", category: "presence" },
  { index: 76, title: "What It Means to Be Held", category: "intimacy" },
  { index: 77, title: "The Truth in Silence", category: "presence" },
  { index: 78, title: "Permission to Want", category: "desire" },
  { index: 79, title: "The Wisdom in Your Hesitation", category: "intuition" },
  { index: 80, title: "Softening the Hard Places", category: "vulnerability" },
  { index: 81, title: "The Gift of Being Chosen", category: "connection" },
  { index: 82, title: "Coming Back to Your Body", category: "embodiment" },
  { index: 83, title: "The Intimacy of Saying No", category: "boundaries" },
  { index: 84, title: "What Presence Really Is", category: "embodiment" },
  { index: 85, title: "Permission to Thaw", category: "vulnerability" },
  { index: 86, title: "The Courage to Connect", category: "connection" },
  { index: 87, title: "Your Body Deserves Attention", category: "embodiment" },
  { index: 88, title: "The Grace of Being Imperfect", category: "authenticity" },
  { index: 89, title: "Desire as a Teacher", category: "sexuality" },
  { index: 90, title: "The Sacred in Sexual Connection", category: "spirituality" },
  { index: 91, title: "Belonging to the Body", category: "embodiment" },
  { index: 92, title: "The Truth Your Touch Speaks", category: "intimacy" },
  { index: 93, title: "Permission to Soften", category: "vulnerability" },
  { index: 94, title: "What It Means to Be Held", category: "intimacy" },
  { index: 95, title: "The Courage of Tenderness", category: "strength" },
  { index: 96, title: "Coming Home to Yourself", category: "presence" },
  { index: 97, title: "The Wisdom of Your Body", category: "embodiment" },
  { index: 98, title: "Desire Without Apology", category: "desire" },
  { index: 99, title: "The Gift of Simple Presence", category: "connection" },
  { index: 100, title: "Permission to Be Alive", category: "authenticity" },
  { index: 101, title: "The Bravery of Asking", category: "communication" },
  { index: 102, title: "What Touch Can Heal", category: "intimacy" },
  { index: 103, title: "The Sacred Feminine", category: "spirituality" },
  { index: 104, title: "Permission to Receive", category: "vulnerability" },
  { index: 105, title: "The Truth of Loneliness", category: "emotion" },
  { index: 106, title: "What Acceptance Looks Like", category: "authenticity" },
  { index: 107, title: "The Courage to Be Quiet", category: "presence" },
  { index: 108, title: "Your Desire Matters", category: "sexuality" },
  { index: 109, title: "The Grace of Being Here", category: "presence" },
  { index: 110, title: "Permission to Feel Everything", category: "emotion" },
  { index: 111, title: "The Intimacy of Truth", category: "authenticity" },
  { index: 112, title: "What Your Longing Reveals", category: "desire" },
  { index: 113, title: "The Sacred in Simplicity", category: "spirituality" },
  { index: 114, title: "Coming Back to Now", category: "embodiment" },
  { index: 115, title: "The Wisdom of Saying Yes", category: "desire" },
  { index: 116, title: "Permission to Be Needed", category: "vulnerability" },
  { index: 117, title: "The Courage of Showing Up", category: "connection" },
  { index: 118, title: "What Belonging Feels Like", category: "community" },
  { index: 119, title: "The Gift of Returning", category: "presence" },
];

export const reflectionPrompts = [
  { index: 0, prompt: "What part of you is asking to be heard today?" },
  { index: 1, prompt: "Where do you notice yourself performing instead of being present?" },
  { index: 2, prompt: "What kind of connection feels nourishing, not draining?" },
  { index: 3, prompt: "What are you longing for but rarely saying out loud?" },
  { index: 4, prompt: "What would it feel like to let someone care about you without rushing to give something back?" },
  { index: 5, prompt: "When do you feel most safe being yourself?" },
  { index: 6, prompt: "What desire have you been quiet about?" },
  { index: 7, prompt: "What softness do you keep hidden?" },
  { index: 8, prompt: "If you stopped defending, what would people see?" },
  { index: 9, prompt: "What has your body been trying to tell you?" },
  { index: 10, prompt: "When do you feel most alive?" },
  { index: 11, prompt: "What kind of touch are you missing?" },
  { index: 12, prompt: "Where do you hold tension that isn't yours to carry?" },
  { index: 13, prompt: "What would change if you believed you were worthy right now?" },
  { index: 14, prompt: "What are you grieving that no one knows about?" },
  { index: 15, prompt: "When have you felt truly seen by another person?" },
  { index: 16, prompt: "What would it mean to come home to your body?" },
  { index: 17, prompt: "What kind of presence do you most need?" },
  { index: 18, prompt: "What are you afraid will happen if you soften?" },
  { index: 19, prompt: "When did you learn to defend yourself?" },
  { index: 20, prompt: "What longing lives underneath your accomplishments?" },
  { index: 21, prompt: "What part of you is still waiting to be known?" },
  { index: 22, prompt: "How do you abandon yourself?" },
  { index: 23, prompt: "What does your body want more of?" },
  { index: 24, prompt: "What does your body want less of?" },
  { index: 25, prompt: "When do you feel most like yourself?" },
  { index: 26, prompt: "What vulnerability scares you most?" },
  { index: 27, prompt: "What would you do if you trusted yourself?" },
  { index: 28, prompt: "What have you outgrown but not released?" },
  { index: 29, prompt: "Who knows the most real version of you?" },
  { index: 30, prompt: "What do you need permission to feel?" },
  { index: 31, prompt: "When do you feel most connected?" },
  { index: 32, prompt: "What truth have you been keeping inside?" },
  { index: 33, prompt: "Where does your power actually come from?" },
  { index: 34, prompt: "What would intimacy look like without fear?" },
  { index: 35, prompt: "What are you still waiting for permission to want?" },
  { index: 36, prompt: "What old story about yourself is ready to change?" },
  { index: 37, prompt: "When have you felt most like your real self?" },
  { index: 38, prompt: "What does genuine rest look like for you?" },
  { index: 39, prompt: "Where are you still performing for love?" },
  { index: 40, prompt: "What would happen if you believed your feelings mattered?" },
  { index: 41, prompt: "When do you feel most at home in your body?" },
  { index: 42, prompt: "What kind of love are you actually looking for?" },
  { index: 43, prompt: "What part of yourself have you been protecting at great cost?" },
  { index: 44, prompt: "What does your body feel when you're truly safe?" },
  { index: 45, prompt: "What would change if you started asking for what you want?" },
  { index: 46, prompt: "When did you learn that your needs were too much?" },
  { index: 47, prompt: "What would it feel like to be thoroughly known?" },
  { index: 48, prompt: "What old wound is still running the show?" },
  { index: 49, prompt: "Where do you need to soften your stance?" },
  { index: 50, prompt: "What part of your sexuality do you still hold shame about?" },
  { index: 51, prompt: "When have you felt most genuinely received?" },
  { index: 52, prompt: "What secret do you think would make you unlovable?" },
  { index: 53, prompt: "What are you still waiting to become before you allow yourself to rest?" },
  { index: 54, prompt: "Where do you notice yourself shrinking?" },
  { index: 55, prompt: "What would a truly embodied day look like for you?" },
  { index: 56, prompt: "What's underneath the thing you're most anxious about?" },
  { index: 57, prompt: "When do you feel most like a man?" },
  { index: 58, prompt: "What does your body remember that your mind has forgotten?" },
  { index: 59, prompt: "What would it mean to love yourself the way you want to be loved?" },
  { index: 60, prompt: "Where are you still building walls?" },
  { index: 61, prompt: "What would happen if you trusted your intuition?" },
  { index: 62, prompt: "When have you felt most cared for?" },
  { index: 63, prompt: "What old decision about yourself is ready to be questioned?" },
  { index: 64, prompt: "What does your body feel like when you're deeply connected?" },
  { index: 65, prompt: "What part of yourself do you most long to share?" },
  { index: 66, prompt: "Where are you still punishing yourself?" },
  { index: 67, prompt: "What would genuine vulnerability look like for you?" },
  { index: 68, prompt: "When do you feel most free?" },
  { index: 69, prompt: "What has this year taught you about yourself?" },
  { index: 70, prompt: "What desire are you ready to claim?" },
  { index: 71, prompt: "Where do you need more tenderness?" },
  { index: 72, prompt: "What would it feel like to belong?" },
  { index: 73, prompt: "When have you felt most like yourself?" },
  { index: 74, prompt: "What part of yourself are you still hiding?" },
  { index: 75, prompt: "What fear is protecting something true?" },
  { index: 76, prompt: "When do you feel most alive in your body?" },
  { index: 77, prompt: "What would change if you stopped trying so hard?" },
  { index: 78, prompt: "What old pain still shapes how you love?" },
  { index: 79, prompt: "Where are you being called to soften?" },
  { index: 80, prompt: "What would it mean to come home?" },
  { index: 81, prompt: "What part of you has been waiting?" },
  { index: 82, prompt: "When do you feel most truthful?" },
  { index: 83, prompt: "What would self-compassion look like right now?" },
  { index: 84, prompt: "Where do you need to practice presence?" },
  { index: 85, prompt: "What old belief about yourself is ready to die?" },
  { index: 86, prompt: "When have you felt most genuinely loved?" },
  { index: 87, prompt: "What does your body need most right now?" },
  { index: 88, prompt: "What would happen if you believed in yourself?" },
  { index: 89, prompt: "Where are you still seeking permission?" },
  { index: 90, prompt: "What part of you is ready to be known?" },
  { index: 91, prompt: "When do you feel most grounded?" },
  { index: 92, prompt: "What would genuine rest feel like?" },
  { index: 93, prompt: "Where are you still giving away your power?" },
  { index: 94, prompt: "What would it mean to trust yourself completely?" },
  { index: 95, prompt: "When have you felt most at peace?" },
  { index: 96, prompt: "What old identity are you outgrowing?" },
  { index: 97, prompt: "What part of yourself would you like to reclaim?" },
  { index: 98, prompt: "Where do you need more softness?" },
  { index: 99, prompt: "What would happen if you stopped apologizing for existing?" },
  { index: 100, prompt: "When do you feel most authentically yourself?" },
  { index: 101, prompt: "What part of your desire are you ready to claim?" },
  { index: 102, prompt: "Where are you being called to expand?" },
  { index: 103, prompt: "What would genuine freedom look like?" },
  { index: 104, prompt: "When have you felt most connected to others?" },
  { index: 105, prompt: "What old story are you ready to rewrite?" },
  { index: 106, prompt: "What part of yourself deserves more love?" },
  { index: 107, prompt: "Where do you need to practice self-compassion?" },
  { index: 108, prompt: "What would it feel like to be fully alive?" },
  { index: 109, prompt: "When do you feel most like your true self?" },
  { index: 110, prompt: "What part of you is ready to emerge?" },
  { index: 111, prompt: "Where are you being called to grow?" },
  { index: 112, prompt: "What would accepting yourself completely look like?" },
  { index: 113, prompt: "When have you felt most at home?" },
  { index: 114, prompt: "What part of your truth are you ready to speak?" },
  { index: 115, prompt: "Where do you need more courage?" },
  { index: 116, prompt: "What would it mean to love yourself fully?" },
  { index: 117, prompt: "When do you feel most connected to your body?" },
  { index: 118, prompt: "What part of yourself is asking for attention?" },
  { index: 119, prompt: "Where are you ready to soften and let go?" },
];

export const embodimentPractices = [
  { index: 0, practice: "Place one hand on your chest and one on your belly. Breathe slowly for two minutes. Notice which hand moves first." },
  { index: 1, practice: "Sit quietly and unclench your jaw, shoulders, belly, and hands. Notice what softens when you stop preparing." },
  { index: 2, practice: "Take five slow breaths before responding to someone today. Let your answer come from your body, not just your mind." },
  { index: 3, practice: "Notice where your body says yes, no, maybe, or not yet." },
  { index: 4, practice: "Stand with your feet on the ground. Feel the earth supporting you for one full minute. That support is real." },
  { index: 5, practice: "Close your eyes and scan from the top of your head to your toes. What sensations are present? Don't change anything, just notice." },
  { index: 6, practice: "Take a walk and pay attention to how your feet meet the ground with each step." },
  { index: 7, practice: "Spend two minutes breathing into your chest. With each exhale, notice what releases." },
  { index: 8, practice: "Touch your face gently. Feel the skin, the bone structure, the aliveness of your own face." },
  { index: 9, practice: "Notice your heartbeat. Place your hand on your heart and listen. You are alive right now." },
  { index: 10, practice: "Slow down your morning routine by 50%. Notice what you miss when you're not rushing." },
  { index: 11, practice: "Breathe in for a count of four, hold for four, out for four. Do this ten times." },
  { index: 12, practice: "Stretch your body in ways that feel nourishing, not aggressive. Move toward sensation, not pain." },
  { index: 13, practice: "Stand in a doorway and press your palms against the frame. Feel your strength." },
  { index: 14, practice: "Before you reach for your phone, pause and feel three sensations in your body." },
  { index: 15, practice: "Hum for two minutes. Feel the vibration in your chest." },
  { index: 16, practice: "Roll your shoulders back and down. Let your body relax toward gravity." },
  { index: 17, practice: "Unclench your hands and notice what wanting feels like in your palms." },
  { index: 18, practice: "Press your feet into the floor and feel the stability beneath you." },
  { index: 19, practice: "Take a shower and feel the water as information, not just cleansing." },
  { index: 20, practice: "Lie down and let yourself be heavy. Feel what it's like to stop holding yourself up." },
  { index: 21, practice: "Notice your breath without trying to change it. Just witness it." },
  { index: 22, practice: "Tense every muscle in your body for ten seconds, then release. Feel the difference." },
  { index: 23, practice: "Massage your own shoulders, neck, and temples. Feel the care you can give yourself." },
  { index: 24, practice: "Sit with your spine straight. Imagine a golden thread pulling you up from the crown of your head." },
  { index: 25, practice: "Press your tongue to the roof of your mouth and breathe. Feel the subtle shift." },
  { index: 26, practice: "Notice the difference between tightness and aliveness in your body today." },
  { index: 27, practice: "Sit in silence for three minutes. Listen to the sounds around you and inside you." },
  { index: 28, practice: "Feel your feet on the ground. Imagine roots growing down from your feet into the earth." },
  { index: 29, practice: "Notice where you're holding tension in anticipation. Give yourself permission to release it." },
  { index: 30, practice: "Take five conscious breaths where the exhale is longer than the inhale." },
  { index: 31, practice: "Stretch one arm overhead and feel the length in your entire side body." },
  { index: 32, practice: "Close your eyes and feel your face relax. Notice any places still holding." },
  { index: 33, practice: "Breathe deeply into your belly three times. Feel it expand with each inhale." },
  { index: 34, practice: "Notice the temperature of your skin, the fabric of your clothes, the weight of your body." },
  { index: 35, practice: "Open your hands and feel the space between your fingers. You are not closed." },
  { index: 36, practice: "Soften your gaze. Let your eyes relax instead of reaching." },
  { index: 37, practice: "Feel your aliveness by noticing your heartbeat in different parts of your body." },
  { index: 38, practice: "Stand and shift your weight from one foot to the other. Feel your base." },
  { index: 39, practice: "Breathe into the places in your body that feel guarded." },
  { index: 40, practice: "Unclench your jaw and feel the release in your whole face." },
  { index: 41, practice: "Touch your hands together and notice the sensation of skin on skin." },
  { index: 42, practice: "Sit with both feet flat on the floor. Feel your weight grounded." },
  { index: 43, practice: "Close your eyes and feel the light behind your eyelids." },
  { index: 44, practice: "Breathe into your heart for two minutes. What does it want to tell you?" },
  { index: 45, practice: "Stand and feel your whole body from feet to crown. You are one organism." },
  { index: 46, practice: "Notice your breath moving in and out of your body. This is life happening." },
  { index: 47, practice: "Feel your ribs expanding and contracting with each breath." },
  { index: 48, practice: "Place your hands on your own shoulders. Offer yourself pressure and warmth." },
  { index: 49, practice: "Notice the difference between bracing and breathing." },
  { index: 50, practice: "Lie on your back and feel your spine supported by the earth." },
  { index: 51, practice: "Close your eyes and feel the weight of your head on your neck." },
  { index: 52, practice: "Breathe slowly and notice the natural pause between exhale and inhale." },
  { index: 53, practice: "Feel your hands in your lap. They are part of you, not separate." },
  { index: 54, practice: "Notice where your body is most relaxed and where it's most defended." },
  { index: 55, practice: "Stretch your arms overhead and feel the length in your whole front side." },
  { index: 56, practice: "Unclench your fists and feel the softness in your hands." },
  { index: 57, practice: "Sit upright and feel your spine as a column of strength." },
  { index: 58, practice: "Breathe and notice the temperature of the air entering your nostrils." },
  { index: 59, practice: "Feel your weight in the chair. You are held." },
  { index: 60, practice: "Close your eyes and visualize a light at the center of your chest." },
  { index: 61, practice: "Notice your shoulders. Are they up by your ears? Give them permission to drop." },
  { index: 62, practice: "Feel the pulse of your heartbeat. You are alive right now." },
  { index: 63, practice: "Tilt your head gently and feel the release in your neck." },
  { index: 64, practice: "Breathe in the scent around you. Smell is connection." },
  { index: 65, practice: "Feel your feet. They've carried you this far." },
  { index: 66, practice: "Close your eyes and feel the temperature of your face." },
  { index: 67, practice: "Breathe and notice the slight vibration in your body from life moving through you." },
  { index: 68, practice: "Feel your whole body as a vessel of aliveness." },
  { index: 69, practice: "Notice your belly. Is it soft or defended? Soften it." },
  { index: 70, practice: "Close your eyes and feel your inner landscape." },
  { index: 71, practice: "Stand and feel the strength in your legs." },
  { index: 72, practice: "Breathe into your lower belly and feel it expand." },
  { index: 73, practice: "Feel your spine as a line of light from root to crown." },
  { index: 74, practice: "Notice your hands throughout the day. Feel them as instruments of care." },
  { index: 75, practice: "Close your eyes and feel your face soften." },
  { index: 76, practice: "Breathe and feel your chest open." },
  { index: 77, practice: "Feel your whole body as a home you can return to." },
  { index: 78, practice: "Notice your lips. Are they soft or tight? Soften them." },
  { index: 79, practice: "Breathe in for four counts, out for six. Feel the calming effect." },
  { index: 80, practice: "Feel your weight. Gravity is holding you." },
  { index: 81, practice: "Close your eyes and feel the aliveness behind your eyes." },
  { index: 82, practice: "Breathe and notice what your body needs right now." },
  { index: 83, practice: "Feel your whole being as a song your body is always singing." },
  { index: 84, practice: "Notice your fingers. Feel them as extensions of your heart." },
  { index: 85, practice: "Breathe deeply and feel the space in your chest expand." },
  { index: 86, practice: "Feel your feet as your foundation." },
  { index: 87, practice: "Close your eyes and feel your face as sacred." },
  { index: 88, practice: "Breathe and feel your nervous system settle." },
  { index: 89, practice: "Feel your whole body as permission." },
  { index: 90, practice: "Notice your breath as the most intimate conversation with yourself." },
  { index: 91, practice: "Feel your aliveness by tuning into warmth in your hands and feet." },
  { index: 92, practice: "Breathe and notice the silence inside." },
  { index: 93, practice: "Feel your body as a friend, not an opponent." },
  { index: 94, practice: "Close your eyes and feel your heartbeat as a drum." },
  { index: 95, practice: "Breathe into places of tightness and imagine them softening." },
  { index: 96, practice: "Feel your whole being as worthy of attention." },
  { index: 97, practice: "Notice your breath as a gift you give yourself." },
  { index: 98, practice: "Feel your body as a sacred instrument." },
  { index: 99, practice: "Breathe and feel yourself returning to now." },
  { index: 100, practice: "Feel your weight in the world as significant." },
  { index: 101, practice: "Close your eyes and feel your inner light." },
  { index: 102, practice: "Breathe and notice the miracle of being alive." },
  { index: 103, practice: "Feel your body as permission to exist." },
  { index: 104, practice: "Notice your breath as the bridge between body and spirit." },
  { index: 105, practice: "Feel your aliveness as your birthright." },
  { index: 106, practice: "Breathe and feel your feet grounded in this moment." },
  { index: 107, practice: "Feel your whole being as an invitation." },
  { index: 108, practice: "Close your eyes and feel the peace in your own presence." },
  { index: 109, practice: "Breathe and feel yourself coming home." },
  { index: 110, practice: "Feel your body as a sanctuary." },
  { index: 111, practice: "Notice your breath as communication with the divine." },
  { index: 112, practice: "Feel your whole being as prayer." },
  { index: 113, practice: "Breathe and feel yourself loved." },
  { index: 114, practice: "Feel your aliveness as a gift." },
  { index: 115, practice: "Close your eyes and feel your true self." },
  { index: 116, practice: "Breathe and feel your wholeness." },
  { index: 117, practice: "Feel your body as a home you've always longed for." },
  { index: 118, practice: "Notice your breath and feel yourself held." },
  { index: 119, practice: "Feel your being as the answer." },
];

export const bodyCheckIns = [
  { index: 0, prompt: "Where in your body do you feel most guarded today?" },
  { index: 1, prompt: "What sensation is asking for your attention?" },
  { index: 2, prompt: "What does your body need less of today?" },
  { index: 3, prompt: "Where does your body feel most alive?" },
  { index: 4, prompt: "What part of your body is calling out for care?" },
  { index: 5, prompt: "Where do you feel tension that isn't yours?" },
  { index: 6, prompt: "What does your body want to say today?" },
  { index: 7, prompt: "Where do you feel tight with anticipation?" },
  { index: 8, prompt: "What part of your body feels most authentically you?" },
  { index: 9, prompt: "Where do you feel safe and open?" },
  { index: 10, prompt: "What does your body need permission to feel?" },
  { index: 11, prompt: "Where is your body most alive right now?" },
  { index: 12, prompt: "What sensation would feel most welcome right now?" },
  { index: 13, prompt: "Where do you feel your power?" },
  { index: 14, prompt: "What part of your body feels most vulnerable?" },
  { index: 15, prompt: "Where do you feel most at home?" },
  { index: 16, prompt: "What does your body long to express?" },
  { index: 17, prompt: "Where do you feel most defended?" },
  { index: 18, prompt: "What part of your body is ready to soften?" },
  { index: 19, prompt: "Where does your body feel most like itself?" },
  { index: 20, prompt: "What sensation are you avoiding?" },
  { index: 21, prompt: "Where do you feel most open?" },
  { index: 22, prompt: "What does your body want to receive?" },
  { index: 23, prompt: "Where is your body most at ease?" },
  { index: 24, prompt: "What part of your body needs attention?" },
  { index: 25, prompt: "Where do you feel most settled?" },
  { index: 26, prompt: "What does your body want to give?" },
  { index: 27, prompt: "Where do you feel most present?" },
  { index: 28, prompt: "What part of your body feels most real?" },
  { index: 29, prompt: "Where do you feel most like you?" },
  { index: 30, prompt: "What sensation feels most welcome?" },
  { index: 31, prompt: "Where do you feel most grounded?" },
  { index: 32, prompt: "What does your body want to experience?" },
  { index: 33, prompt: "Where do you feel most whole?" },
  { index: 34, prompt: "What part of your body is most alive?" },
  { index: 35, prompt: "Where do you feel most connected?" },
  { index: 36, prompt: "What does your body want to release?" },
  { index: 37, prompt: "Where do you feel most authentic?" },
  { index: 38, prompt: "What sensation brings you home?" },
  { index: 39, prompt: "Where do you feel most held?" },
  { index: 40, prompt: "What part of your body deserves more attention?" },
  { index: 41, prompt: "Where do you feel most yourself?" },
  { index: 42, prompt: "What does your body want to say?" },
  { index: 43, prompt: "Where do you feel most at peace?" },
  { index: 44, prompt: "What sensation do you long for?" },
  { index: 45, prompt: "Where do you feel most alive?" },
  { index: 46, prompt: "What does your body want to know?" },
  { index: 47, prompt: "Where do you feel most safe?" },
  { index: 48, prompt: "What part of your body wants to move?" },
  { index: 49, prompt: "Where do you feel most real?" },
  { index: 50, prompt: "What sensation feels most true?" },
  { index: 51, prompt: "Where do you feel most present?" },
  { index: 52, prompt: "What does your body want to become?" },
  { index: 53, prompt: "Where do you feel most free?" },
  { index: 54, prompt: "What part of your body is waiting?" },
  { index: 55, prompt: "Where do you feel most seen?" },
  { index: 56, prompt: "What sensation brings you back?" },
  { index: 57, prompt: "Where do you feel most at home?" },
  { index: 58, prompt: "What does your body want to remember?" },
  { index: 59, prompt: "Where do you feel most whole?" },
  { index: 60, prompt: "What part of your body feels most nourished?" },
  { index: 61, prompt: "Where do you feel most grounded?" },
  { index: 62, prompt: "What sensation feels most healing?" },
  { index: 63, prompt: "Where do you feel most open?" },
  { index: 64, prompt: "What does your body want to express?" },
  { index: 65, prompt: "Where do you feel most alive?" },
  { index: 66, prompt: "What part of your body is speaking?" },
  { index: 67, prompt: "Where do you feel most authentic?" },
  { index: 68, prompt: "What sensation brings peace?" },
  { index: 69, prompt: "Where do you feel most yourself?" },
  { index: 70, prompt: "What does your body want today?" },
  { index: 71, prompt: "Where do you feel most held?" },
  { index: 72, prompt: "What part of your body feels most real?" },
  { index: 73, prompt: "Where do you feel most present?" },
  { index: 74, prompt: "What sensation feels most welcome?" },
  { index: 75, prompt: "Where do you feel most at ease?" },
  { index: 76, prompt: "What does your body want to receive?" },
  { index: 77, prompt: "Where do you feel most connected?" },
  { index: 78, prompt: "What part of your body is alive?" },
  { index: 79, prompt: "Where do you feel most like home?" },
  { index: 80, prompt: "What sensation feels most true?" },
  { index: 81, prompt: "Where do you feel most safe?" },
  { index: 82, prompt: "What does your body want to tell you?" },
  { index: 83, prompt: "Where do you feel most whole?" },
  { index: 84, prompt: "What part of your body needs love?" },
  { index: 85, prompt: "Where do you feel most grounded?" },
  { index: 86, prompt: "What sensation brings you back?" },
  { index: 87, prompt: "Where do you feel most real?" },
  { index: 88, prompt: "What does your body want to become?" },
  { index: 89, prompt: "Where do you feel most present?" },
  { index: 90, prompt: "What part of your body is calling?" },
  { index: 91, prompt: "Where do you feel most authentic?" },
  { index: 92, prompt: "What sensation feels healing?" },
  { index: 93, prompt: "Where do you feel most yourself?" },
  { index: 94, prompt: "What does your body want to share?" },
  { index: 95, prompt: "Where do you feel most alive?" },
  { index: 96, prompt: "What part of your body feels most nourished?" },
  { index: 97, prompt: "Where do you feel most held?" },
  { index: 98, prompt: "What sensation brings peace?" },
  { index: 99, prompt: "Where do you feel most at home?" },
  { index: 100, prompt: "What does your body want to know?" },
  { index: 101, prompt: "Where do you feel most connected?" },
  { index: 102, prompt: "What part of your body is awakening?" },
  { index: 103, prompt: "Where do you feel most safe?" },
  { index: 104, prompt: "What sensation feels most real?" },
  { index: 105, prompt: "Where do you feel most present?" },
  { index: 106, prompt: "What does your body want to express?" },
  { index: 107, prompt: "Where do you feel most grounded?" },
  { index: 108, prompt: "What part of your body deserves care?" },
  { index: 109, prompt: "Where do you feel most yourself?" },
  { index: 110, prompt: "What sensation brings you home?" },
  { index: 111, prompt: "Where do you feel most alive?" },
  { index: 112, prompt: "What does your body want to become?" },
  { index: 113, prompt: "Where do you feel most whole?" },
  { index: 114, prompt: "What part of your body is speaking?" },
  { index: 115, prompt: "Where do you feel most authentic?" },
  { index: 116, prompt: "What sensation feels most healing?" },
  { index: 117, prompt: "Where do you feel most held?" },
  { index: 118, prompt: "What does your body want to tell you?" },
  { index: 119, prompt: "Where do you feel most at peace?" },
];

export const conversationInvitations = [
  { index: 0, invitation: "Ask someone: 'What has been on your heart lately?'" },
  { index: 1, invitation: "Share one thing you're learning about connection." },
  { index: 2, invitation: "Comment on someone's post with curiosity rather than advice." },
  { index: 3, invitation: "Ask: 'What helps you feel safe enough to be honest?'" },
  { index: 4, invitation: "Share a moment when you felt genuinely understood." },
  { index: 5, invitation: "Ask someone: 'What are you longing for?'" },
  { index: 6, invitation: "Tell someone one way they've made you feel seen." },
  { index: 7, invitation: "Ask: 'What have you learned about yourself recently?'" },
  { index: 8, invitation: "Share something you're still learning to accept about yourself." },
  { index: 9, invitation: "Ask someone: 'What does real support look like for you?'" },
  { index: 10, invitation: "Comment with a genuine question instead of a fix." },
  { index: 11, invitation: "Share a desire you've been quiet about." },
  { index: 12, invitation: "Ask: 'What has changed in how you see yourself?'" },
  { index: 13, invitation: "Tell someone you appreciate their honesty." },
  { index: 14, invitation: "Ask: 'What does belonging feel like to you?'" },
  { index: 15, invitation: "Share what you're still learning about receiving." },
  { index: 16, invitation: "Ask someone: 'What softness did you show this week?'" },
  { index: 17, invitation: "Comment with your own vulnerability in response." },
  { index: 18, invitation: "Ask: 'When do you feel most like yourself?'" },
  { index: 19, invitation: "Share something you're scared to say out loud." },
  { index: 20, invitation: "Ask someone: 'What are you becoming?'" },
  { index: 21, invitation: "Tell someone what you see in them." },
  { index: 22, invitation: "Ask: 'What does your body need?'" },
  { index: 23, invitation: "Share a moment of tenderness from your week." },
  { index: 24, invitation: "Ask: 'How are you taking care of yourself?'" },
  { index: 25, invitation: "Comment with something true about your own experience." },
  { index: 26, invitation: "Ask someone: 'What are you grieving?'" },
  { index: 27, invitation: "Share what you're learning about yourself." },
  { index: 28, invitation: "Ask: 'What does safety look like for you?'" },
  { index: 29, invitation: "Tell someone one brave thing you saw them do." },
  { index: 30, invitation: "Ask someone: 'What are you wanting?' - not needing, wanting." },
  { index: 31, invitation: "Share something about your sexuality without shame." },
  { index: 32, invitation: "Ask: 'What helps you feel alive?'" },
  { index: 33, invitation: "Comment by sharing your own growth edge." },
  { index: 34, invitation: "Ask someone: 'What are you proud of?'" },
  { index: 35, invitation: "Share a way you've softened recently." },
  { index: 36, invitation: "Ask: 'What do you need permission to feel?'" },
  { index: 37, invitation: "Tell someone how their honesty moved you." },
  { index: 38, invitation: "Ask someone: 'What does freedom look like?'" },
  { index: 39, invitation: "Share your whole truth, not just the pretty parts." },
  { index: 40, invitation: "Ask: 'What are you becoming?'" },
  { index: 41, invitation: "Comment with genuine curiosity about their experience." },
  { index: 42, invitation: "Ask someone: 'What has surprised you about yourself?'" },
  { index: 43, invitation: "Share a vulnerability and notice what happens." },
  { index: 44, invitation: "Ask: 'What does love look like to you?'" },
  { index: 45, invitation: "Tell someone you see their effort." },
  { index: 46, invitation: "Ask someone: 'What are you releasing?'" },
  { index: 47, invitation: "Share what you're still learning about intimacy." },
  { index: 48, invitation: "Ask: 'What do you need to hear?'" },
  { index: 49, invitation: "Comment by saying what resonated in their post." },
  { index: 50, invitation: "Ask someone: 'What does coming home feel like?'" },
  { index: 51, invitation: "Share a secret about what you're longing for." },
  { index: 52, invitation: "Ask: 'What are you no longer willing to accept?'" },
  { index: 53, invitation: "Tell someone one way you see them growing." },
  { index: 54, invitation: "Ask someone: 'What does presence look like for you?'" },
  { index: 55, invitation: "Share something about your journey nobody knows." },
  { index: 56, invitation: "Ask: 'What would change if you trusted yourself?'" },
  { index: 57, invitation: "Comment with your own question in response." },
  { index: 58, invitation: "Ask someone: 'What are you still learning to love about yourself?'" },
  { index: 59, invitation: "Share a moment when you felt truly seen." },
  { index: 60, invitation: "Ask: 'What does genuine rest look like?'" },
  { index: 61, invitation: "Tell someone you notice their courage." },
  { index: 62, invitation: "Ask someone: 'What are you becoming?'" },
  { index: 63, invitation: "Share what you're scared to say." },
  { index: 64, invitation: "Ask: 'What does belonging mean to you?'" },
  { index: 65, invitation: "Comment with something that moved you." },
  { index: 66, invitation: "Ask someone: 'What have you survived?'" },
  { index: 67, invitation: "Share a desire you've been holding." },
  { index: 68, invitation: "Ask: 'What would it mean to be fully yourself?'" },
  { index: 69, invitation: "Tell someone they matter." },
  { index: 70, invitation: "Ask someone: 'What are you honoring in yourself?'" },
  { index: 71, invitation: "Share something true that scared you." },
  { index: 72, invitation: "Ask: 'What does accepting yourself look like?'" },
  { index: 73, invitation: "Comment with your whole heart." },
  { index: 74, invitation: "Ask someone: 'What are you becoming?'" },
  { index: 75, invitation: "Share what vulnerability has taught you." },
  { index: 76, invitation: "Ask: 'What does being fully alive feel like?'" },
  { index: 77, invitation: "Tell someone you see their wholeness." },
  { index: 78, invitation: "Ask someone: 'What are you learning about yourself?'" },
  { index: 79, invitation: "Share a truth nobody knows." },
  { index: 80, invitation: "Ask: 'What does genuine connection feel like?'" },
  { index: 81, invitation: "Comment by sharing what you also felt or experienced." },
  { index: 82, invitation: "Ask someone: 'What are you ready for?'" },
  { index: 83, invitation: "Share something about yourself without apology." },
  { index: 84, invitation: "Ask: 'What has changed in your heart?'" },
  { index: 85, invitation: "Tell someone they inspire you." },
  { index: 86, invitation: "Ask someone: 'What are you becoming?'" },
  { index: 87, invitation: "Share what you've learned about receiving." },
  { index: 88, invitation: "Ask: 'What does trust look like for you?'" },
  { index: 89, invitation: "Comment with curiosity about their experience." },
  { index: 90, invitation: "Ask someone: 'What are you no longer hiding?'" },
  { index: 91, invitation: "Share a moment when you felt held." },
  { index: 92, invitation: "Ask: 'What does love require of you?'" },
  { index: 93, invitation: "Tell someone you're grateful for their honesty." },
  { index: 94, invitation: "Ask someone: 'What are you becoming?'" },
  { index: 95, invitation: "Share something about your edge." },
  { index: 96, invitation: "Ask: 'What would self-love look like?'" },
  { index: 97, invitation: "Comment with what resonated most." },
  { index: 98, invitation: "Ask someone: 'What are you saying yes to?'" },
  { index: 99, invitation: "Share a desire and notice who reaches back." },
  { index: 100, invitation: "Ask: 'What does being chosen feel like?'" },
  { index: 101, invitation: "Tell someone you see their light." },
  { index: 102, invitation: "Ask someone: 'What are you becoming?'" },
  { index: 103, invitation: "Share what you're learning about yourself." },
  { index: 104, invitation: "Ask: 'What does genuine intimacy require?'" },
  { index: 105, invitation: "Comment with your truth." },
  { index: 106, invitation: "Ask someone: 'What are you ready to let go of?'" },
  { index: 107, invitation: "Share a softness people don't usually see." },
  { index: 108, invitation: "Ask: 'What does accepting yourself mean?'" },
  { index: 109, invitation: "Tell someone you believe in them." },
  { index: 110, invitation: "Ask someone: 'What are you becoming?'" },
  { index: 111, invitation: "Share something real from your day." },
  { index: 112, invitation: "Ask: 'What does home mean to you?'" },
  { index: 113, invitation: "Comment with what moved you." },
  { index: 114, invitation: "Ask someone: 'What are you honoring?'" },
  { index: 115, invitation: "Share a desire without shame." },
  { index: 116, invitation: "Ask: 'What does being alive require?'" },
  { index: 117, invitation: "Tell someone you're grateful." },
  { index: 118, invitation: "Ask someone: 'What are you becoming?'" },
  { index: 119, invitation: "Share what your heart knows." },
];

export const quotes = [
  { index: 0, quote: "Connection often begins where performance ends." },
  { index: 1, quote: "The body tells the truth long before the mouth finds the words." },
  { index: 2, quote: "You do not have to be fully healed to be worthy of closeness." },
  { index: 3, quote: "Receiving is not taking. Sometimes it is trust." },
  { index: 4, quote: "The parts of yourself you hide are often the ones most worth loving." },
  { index: 5, quote: "Vulnerability is not weakness. It is the most honest thing you can offer." },
  { index: 6, quote: "Your desire matters. It is not selfish to want." },
  { index: 7, quote: "Slowing down is not laziness. It is wisdom." },
  { index: 8, quote: "The body is not a problem to be fixed. It is a home to inhabit." },
  { index: 9, quote: "Real intimacy happens in the places where you stop trying so hard." },
  { index: 10, quote: "Asking for what you need is not burden. It is an invitation." },
  { index: 11, quote: "The parts of yourself you think are broken are often the most beautiful." },
  { index: 12, quote: "Being seen is terrifying. So is being invisible." },
  { index: 13, quote: "Your sensitivity is not a weakness. It is sensitivity." },
  { index: 14, quote: "Touch is a language older than words." },
  { index: 15, quote: "The most courageous thing you can do is say 'I don't know.'" },
  { index: 16, quote: "Tenderness is not fragility. It is strength in its truest form." },
  { index: 17, quote: "Your body knows things your mind hasn't figured out yet." },
  { index: 18, quote: "Shame thrives in silence. Truth thrives in witness." },
  { index: 19, quote: "The price of hiding is always higher than the risk of being known." },
  { index: 20, quote: "Real love does not demand you become different." },
  { index: 21, quote: "Longing is not weakness. It is your spirit reaching toward home." },
  { index: 22, quote: "The world needs your softness. Do not harden for it." },
  { index: 23, quote: "Being honest about desire is not shameful. It is sacred." },
  { index: 24, quote: "The parts of yourself you judge most harshly need the most love." },
  { index: 25, quote: "Presence is the most precious gift you can offer." },
  { index: 26, quote: "Your body is not an apology. It is an arrival." },
  { index: 27, quote: "True strength is knowing when to soften." },
  { index: 28, quote: "Receiving is not a transaction. It is a practice." },
  { index: 29, quote: "The parts of you that feel too much are the parts that love most deeply." },
  { index: 30, quote: "Friendship without honesty is just proximity." },
  { index: 31, quote: "Your sexuality is not something to overcome. It is something to know." },
  { index: 32, quote: "Authenticity is not something you find. It is something you practice." },
  { index: 33, quote: "The most profound intimacy is simply being witnessed." },
  { index: 34, quote: "Scars are not ugly. They are proof that you have survived." },
  { index: 35, quote: "Being vulnerable is not the same as being fragile." },
  { index: 36, quote: "Your doubt is not truth. It is habit." },
  { index: 37, quote: "Connection requires courage. Not bravery. Courage." },
  { index: 38, quote: "The parts of yourself you've hidden the longest need the most love." },
  { index: 39, quote: "Real support does not require you to change who you are." },
  { index: 40, quote: "Your body is always speaking. The question is whether you're listening." },
  { index: 41, quote: "Shame cannot survive being spoken about." },
  { index: 42, quote: "The most radical thing you can do is simply be yourself." },
  { index: 43, quote: "Desire is not sinful. It is human." },
  { index: 44, quote: "Your sensitivity is not a flaw. It is information." },
  { index: 45, quote: "The price of connection is the willingness to be known." },
  { index: 46, quote: "Your body is not the problem. What you've been taught about your body is." },
  { index: 47, quote: "True power is the softness to listen." },
  { index: 48, quote: "Being seen is terrifying. Being unseen is lonely." },
  { index: 49, quote: "Your longing is not a weakness. It is your compass." },
  { index: 50, quote: "The most courageous thing is admitting you don't have it figured out." },
  { index: 51, quote: "Intimacy begins where judgment ends." },
  { index: 52, quote: "Your body is not your enemy. It is your teacher." },
  { index: 53, quote: "The parts of yourself you hide are often the ones most worth loving." },
  { index: 54, quote: "Real connection is choosing each other over and over again." },
  { index: 55, quote: "Your desire matters. Full stop." },
  { index: 56, quote: "Vulnerability is strength disguised as weakness." },
  { index: 57, quote: "The world doesn't need you to be perfect. It needs you to be real." },
  { index: 58, quote: "Being yourself is the most radical thing you can do." },
  { index: 59, quote: "Your feelings are not too much. The world is too small for them." },
  { index: 60, quote: "Tenderness is not weakness. It is courage." },
  { index: 61, quote: "The parts of yourself you judge are the ones asking to be loved." },
  { index: 62, quote: "Real intimacy requires the willingness to be known." },
  { index: 63, quote: "Your sensitivity is a gift, not a burden." },
  { index: 64, quote: "The most honest thing you can offer is your presence." },
  { index: 65, quote: "Being vulnerable is not the same as being unsafe." },
  { index: 66, quote: "Your body is a temple. Treat it with reverence." },
  { index: 67, quote: "The price of authenticity is the courage to be seen." },
  { index: 68, quote: "True strength is knowing your limits and honoring them." },
  { index: 69, quote: "Your desire is not a problem. It is a compass." },
  { index: 70, quote: "The most radical act is simply being yourself." },
  { index: 71, quote: "Connection requires honesty. Not perfection. Honesty." },
  { index: 72, quote: "Your feelings matter. Even the uncomfortable ones." },
  { index: 73, quote: "Being seen is more terrifying than being invisible." },
  { index: 74, quote: "Your body is not your shame. It is your home." },
  { index: 75, quote: "Intimacy is what happens when you stop pretending." },
  { index: 76, quote: "The parts of yourself you hide are the ones most worth knowing." },
  { index: 77, quote: "Your sensitivity is not a weakness. It is depth." },
  { index: 78, quote: "Real power is the willingness to be vulnerable." },
  { index: 79, quote: "The most beautiful thing about you is what you're afraid to show." },
  { index: 80, quote: "Being honest is more important than being liked." },
  { index: 81, quote: "Your desire is sacred. Honor it." },
  { index: 82, quote: "The world needs your truth more than your perfection." },
  { index: 83, quote: "Vulnerability is the bridge to real connection." },
  { index: 84, quote: "Your body is not a problem. It is the answer." },
  { index: 85, quote: "True intimacy is being known and loved anyway." },
  { index: 86, quote: "Your softness is not weakness. It is aliveness." },
  { index: 87, quote: "The courage to be yourself is the greatest courage." },
  { index: 88, quote: "Your feelings are valid. Even when they're complicated." },
  { index: 89, quote: "Being vulnerable requires more strength than being defended." },
  { index: 90, quote: "Your desire is not selfish. It is essential." },
  { index: 91, quote: "The most authentic thing you can do is be yourself." },
  { index: 92, quote: "True connection is choosing vulnerability over safety." },
  { index: 93, quote: "Your sensitivity is a superpower in disguise." },
  { index: 94, quote: "Real power is the softness to feel." },
  { index: 95, quote: "The parts of yourself you're ashamed of are the ones asking for love." },
  { index: 96, quote: "Being seen is worth the risk." },
  { index: 97, quote: "Your body is not your past. It is your home." },
  { index: 98, quote: "Intimacy is what happens when you stop being afraid." },
  { index: 99, quote: "Your truth matters. Say it anyway." },
  { index: 100, quote: "The courage to be vulnerable is the highest courage." },
  { index: 101, quote: "Your desire is not sinful. It is sacred." },
  { index: 102, quote: "Real strength is admitting what you need." },
  { index: 103, quote: "Your feelings are not too much. You are not too much." },
  { index: 104, quote: "Being yourself is the most revolutionary act." },
  { index: 105, quote: "True connection requires the risk of being known." },
  { index: 106, quote: "Your sensitivity is not a flaw. It is your power." },
  { index: 107, quote: "The most beautiful version of you is the real one." },
  { index: 108, quote: "Vulnerability is where real strength begins." },
  { index: 109, quote: "Your body deserves love and attention." },
  { index: 110, quote: "Being honest about your needs is not selfish." },
  { index: 111, quote: "Your desire matters. Let it guide you." },
  { index: 112, quote: "Real intimacy is seeing and being seen." },
  { index: 113, quote: "The courage to be yourself is the greatest gift." },
  { index: 114, quote: "Your truth is worth telling." },
  { index: 115, quote: "Being vulnerable is not weakness. It is aliveness." },
  { index: 116, quote: "Your feelings are valid and important." },
  { index: 117, quote: "The world needs your authenticity." },
  { index: 118, quote: "True power is the ability to be vulnerable." },
  { index: 119, quote: "You are enough, right now, exactly as you are." },
];

export const weeklyTrevorNotes = [
  {
    week: 1,
    title: "Welcome to The Connection Room",
    body: "The moment you arrive here, you're already enough. Not someday. Not after you figure things out. Now. This space exists because I believe that real connection begins with radical honesty. Not the performative kind—the kind that costs something. The kind that requires vulnerability. Here, you'll meet men doing the same work you are: learning to soften without becoming fragile, learning to desire without shame, learning to belong without performing. Your presence matters. Your truth matters. Welcome.",
    prompt_snapshot: "What drew you here today?",
    space_suggestion: "commons",
  },
  {
    week: 2,
    title: "The Courage to Ask",
    body: "I've noticed that men have been trained to assume, to figure it out, to never ask. We learned early that asking means weakness. Needing means failure. So we live in a strange isolation, surrounded by people but never truly known. What if asking is actually the gateway to connection? What if the people in your life are waiting for you to trust them enough to ask? This week, I want to invite you to ask one genuine question of someone you trust. Not the small talk kind. A real question. Then listen to the answer.",
    prompt_snapshot: "What are you really asking for?",
    space_suggestion: "commons",
  },
  {
    week: 3,
    title: "What Your Body Knows",
    body: "Most of us live from the neck up. Our bodies become vehicles for accomplishment, not channels for wisdom. But your body knows things your mind hasn't figured out yet. It knows safety from danger. It knows who to trust and who to protect yourself from. It knows when you're longing before your words catch up. This week, I'm asking you to befriend your body. Not to fix it. Not to prove anything with it. Just to listen. Slow down. Pay attention. What's it been trying to tell you?",
    prompt_snapshot: "What has your body been holding?",
    space_suggestion: "embodiment",
  },
  {
    week: 4,
    title: "The Truth About Loneliness",
    body: "Loneliness is not what you think it is. It's not the absence of people. It's the absence of being known. You can be in a crowded room and profoundly lonely if nobody sees you. You can be alone and completely at peace if you're at home in yourself. This is why real connection matters so much. Not because we can't survive without it, but because our deepest longing is to be known by someone. And to know someone. This week, reach out to one person and let them see a part of you that's usually hidden.",
    prompt_snapshot: "What part of yourself are you still hiding?",
    space_suggestion: "commons",
  },
  {
    week: 5,
    title: "Permission to Feel",
    body: "You weren't taught to feel. You were taught to manage, to solve, to move forward. To stay composed. To never let them see you sweat. But your feelings are not a problem to overcome. They're information. They're your inner compass pointing toward what matters. Toward what needs attention. This week, I want you to feel something fully. Not to fix it. Not to move past it quickly. Just to let it be there. To listen to what it's trying to teach you. Your feelings matter.",
    prompt_snapshot: "What emotion are you avoiding?",
    space_suggestion: "commons",
  },
  {
    week: 6,
    title: "Desire Without Shame",
    body: "Desire is not shameful. It's human. It's divine. It's the life force moving through you. But men have complicated relationships with desire. We either suppress it entirely or act it out carelessly. There's no middle ground. What if there was? What if you could acknowledge your desire without being defined by it? What if desire could be a conversation rather than a compulsion? This week, I'm inviting you to name one desire and say it out loud. Not to anyone else. Just to yourself. Just once.",
    prompt_snapshot: "What desire have you been ashamed of?",
    space_suggestion: "dating-desire",
  },
  {
    week: 7,
    title: "The Grace of Slowing Down",
    body: "We live in a culture of speed. Faster, more, now. But the deepest things happen slowly. Trust is built slowly. Intimacy deepens slowly. Presence emerges slowly. Your body knows this. It's constantly asking you to slow down. To breathe. To notice. This week, do one thing slowly. Consciously. One meal. One conversation. One moment. Not because you're being productive. But because it's the only way to be alive.",
    prompt_snapshot: "Where are you rushing that should be slowed?",
    space_suggestion: "embodiment",
  },
  {
    week: 8,
    title: "Receiving",
    body: "This might be the hardest thing for men to learn: how to receive. We're trained to give. To provide. To take care of. But receiving is not weakness. It's not taking. It's opening a door. It's trusting. It's letting someone matter enough to give. When you refuse to receive, you rob someone of the gift of giving. This week, notice how you respond when someone offers something. Do you immediately rush to reciprocate? Can you just say thank you and let it land?",
    prompt_snapshot: "What would it feel like to simply receive?",
    space_suggestion: "commons",
  },
  {
    week: 9,
    title: "Being Seen",
    body: "The deepest fear is being truly seen. Because if you're seen completely, you can't hide. You can't pretend. You can't protect yourself with a carefully curated version of who you are. And yet, being seen is also the only path to real intimacy. To real love. To real belonging. This week, I want you to practice being slightly more visible. Not all at once. Just a little more real. Just a little more honest. See what happens when you let someone see you.",
    prompt_snapshot: "What part of you is asking to be seen?",
    space_suggestion: "commons",
  },
  {
    week: 10,
    title: "The Body as Home",
    body: "You've been taught that your body is something to manage, to control, to transcend. But what if it's actually a home? A place to return to. A place that's always been waiting for you. When you come back to your body, you come back to yourself. You come back to presence. You come back to truth. This week, spend time getting reacquainted with your body. Not in a forced way. Just with curiosity. What does it feel like to be here?",
    prompt_snapshot: "Where does your body feel most alive?",
    space_suggestion: "embodiment",
  },
  {
    week: 11,
    title: "Friendship Without Performance",
    body: "Real friendship is rare because most of us have learned to perform even in our closest relationships. We show our accomplishments. We hide our struggles. We present a version of ourselves we think people will accept. But real friendship is what happens when you stop. When you let your guard down. When you risk being ordinary. This week, choose one friend and share something real. Something you usually hide. Something that costs something to say.",
    prompt_snapshot: "What truth have you been keeping from your friends?",
    space_suggestion: "commons",
  },
  {
    week: 12,
    title: "The Courage of Asking for Help",
    body: "We were taught that asking for help is admitting defeat. That real men figure it out alone. But asking for help is actually the most courageous thing you can do. It requires humility. It requires vulnerability. It requires trusting that you matter enough for someone to say yes. This week, ask for help with something. Anything. See what happens when you trust someone enough to need them.",
    prompt_snapshot: "What do you need help with but haven't asked?",
    space_suggestion: "commons",
  },
  {
    week: 13,
    title: "Touch",
    body: "Humans need touch. It's not luxury. It's biological necessity. But many men have learned that touch is only sexual or it's inappropriate. So we go years without being touched or touching anyone. And we lose something essential. This week, I'm inviting you to remember that non-sexual touch is medicine. Whether it's a handshake held a moment longer. A hug instead of a wave. A hand on a shoulder. These small acts of contact remind us that we're not alone.",
    prompt_snapshot: "What kind of touch are you missing?",
    space_suggestion: "touch-affection",
  },
  {
    week: 14,
    title: "Chosen Family",
    body: "Some of us are lucky enough to have families of origin that see us. For many of us, we have to build our own. Chosen family is the people who know your whole truth and choose you anyway. Who show up. Who witness. Who stay. This week, I want you to notice who your chosen family is. And tell them. Not in a big grand way. Just notice it. Acknowledge it. Let it matter.",
    prompt_snapshot: "Who is your chosen family?",
    space_suggestion: "commons",
  },
  {
    week: 15,
    title: "Grief and Longing",
    body: "Most of us have learned to skip over grief. To move quickly to acceptance. But grief is love with nowhere to go. When we skip it, we also skip the depth of knowing what we've loved. This week, I want to invite you to feel what you're longing for. What you've lost. What you're still hoping for. Not to fix it. Just to feel it. Because the feeling itself is the connection to what matters.",
    prompt_snapshot: "What are you grieving?",
    space_suggestion: "commons",
  },
  {
    week: 16,
    title: "Coming Home",
    body: "By now, you've spent four months in this space. You've shared. You've listened. You've grown. And perhaps you've found something you didn't expect: a home. A place where you can be yourself. Where your softness is not weakness. Where your desire is not shame. Where your presence matters. As we complete this cycle, I want you to know: you don't have to earn the right to belong here. You already do. This space exists for you. Keep coming back.",
    prompt_snapshot: "What does home feel like now?",
    space_suggestion: "commons",
  },
];
