/**
 * Daily Companion Content Seed Data
 *
 * This file seeds the database with:
 * - 120 daily themes
 * - 120 reflection prompts
 * - 120 embodiment practices
 * - 120 body check-ins
 * - 120 conversation invitations
 * - 120 quotes
 * - 16 weekly Trevor notes
 *
 * Content is organized by rotation_index (days since app launch).
 * All content is seeded in Trevor James' voice:
 * warm, grounded, compassionate, mature, slightly poetic but clear.
 */

export const dailyThemes = [
  { index: 0, title: "Receiving Without Defending", category: "connection" },
  { index: 1, title: "Letting Yourself Be Known", category: "vulnerability" },
  { index: 2, title: "The Courage to Ask", category: "communication" },
  { index: 3, title: "What Your Body Has Been Holding", category: "embodiment" },
  { index: 4, title: "Friendship Without Performance", category: "connection" },
  { index: 5, title: "Desire Without Shame", category: "sexuality" },
  { index: 6, title: "Touch Without Obligation", category: "intimacy" },
  { index: 7, title: "Resting the Armor", category: "vulnerability" },
  { index: 8, title: "The Difference Between Privacy and Hiding", category: "authenticity" },
  { index: 9, title: "Making Room for Wanting", category: "desire" },
  { index: 10, title: "Presence as a Practice", category: "embodiment" },
  { index: 11, title: "The Body as a Home", category: "embodiment" },
  { index: 12, title: "Listening Without Fixing", category: "communication" },
  { index: 13, title: "Permission to Feel", category: "emotion" },
  { index: 14, title: "Slow Down. You're Safe Here.", category: "presence" },
  { index: 15, title: "Softness as Strength", category: "vulnerability" },
  { index: 16, title: "The Courage of Honesty", category: "authenticity" },
  { index: 17, title: "What It Means to Belong", category: "connection" },
  { index: 18, title: "Release What You've Been Protecting", category: "vulnerability" },
  { index: 19, title: "The Language Your Body Speaks", category: "embodiment" },
  { index: 20, title: "Being Wanted, Not Needed", category: "intimacy" },
  { index: 21, title: "The Gift of Asking for Help", category: "vulnerability" },
  { index: 22, title: "Desire as Information", category: "desire" },
  { index: 23, title: "What Happens When You Stop Performing", category: "authenticity" },
  { index: 24, title: "Breath as Home", category: "embodiment" },
  { index: 25, title: "The Bravery in Being Ordinary", category: "authenticity" },
  { index: 26, title: "Touch Across Boundaries", category: "intimacy" },
  { index: 27, title: "Speaking Your Truth Softly", category: "communication" },
  { index: 28, title: "The Body's Wisdom", category: "embodiment" },
  { index: 29, title: "Longing is Information", category: "desire" },
  { index: 30, title: "Invitation and Consent", category: "communication" },
  { index: 31, title: "What Real Support Looks Like", category: "connection" },
  { index: 32, title: "The Courage to Be Seen", category: "vulnerability" },
  { index: 33, title: "Intimacy Without Urgency", category: "intimacy" },
  { index: 34, title: "The Quiet Strength of Presence", category: "presence" },
  { index: 35, title: "Healing the Abandonment Inside", category: "emotion" },
  { index: 36, title: "When Defenses Are Love", category: "psychology" },
  { index: 37, title: "The Truth in Your Hesitation", category: "intuition" },
  { index: 38, title: "Belonging to Yourself First", category: "authenticity" },
  { index: 39, title: "The Grace of Slowing Down", category: "presence" },
  { index: 40, title: "Noticing Without Judgment", category: "awareness" },
  { index: 41, title: "The Intimacy of Being Heard", category: "connection" },
  { index: 42, title: "What Softening Teaches Us", category: "vulnerability" },
  { index: 43, title: "The Body Never Lies", category: "embodiment" },
  { index: 44, title: "Permission to Grieve", category: "emotion" },
  { index: 45, title: "Asking Without Shame", category: "communication" },
  { index: 46, title: "The Space Between Souls", category: "spirituality" },
  { index: 47, title: "What It Means to Come Home", category: "presence" },
  { index: 48, title: "Desire as Prayer", category: "spirituality" },
  { index: 49, title: "The Bravery of Vulnerability", category: "courage" },
  { index: 50, title: "Tenderness as a Way of Being", category: "authenticity" },
  { index: 51, title: "The Gift of Attention", category: "connection" },
  { index: 52, title: "Breaking the Silence Inside", category: "authenticity" },
  { index: 53, title: "The Courage to Rest", category: "presence" },
  { index: 54, title: "What You're Really Asking For", category: "communication" },
  { index: 55, title: "The Sacred in the Ordinary", category: "spirituality" },
  { index: 56, title: "When Vulnerability Is Revolutionary", category: "courage" },
  { index: 57, title: "The Language of the Body", category: "embodiment" },
  { index: 58, title: "Connection as Medicine", category: "healing" },
  { index: 59, title: "The Truth of Your Longing", category: "desire" },
  { index: 60, title: "Permission to Be Whole", category: "authenticity" },
  { index: 61, title: "The Wisdom of Boundaries", category: "communication" },
  { index: 62, title: "Being Known, Being Loved", category: "intimacy" },
  { index: 63, title: "The Courage to Start Again", category: "healing" },
  { index: 64, title: "Presence as an Act of Love", category: "connection" },
  { index: 65, title: "The Sacred Pause", category: "embodiment" },
  { index: 66, title: "What Shame Wants You to Know", category: "emotion" },
  { index: 67, title: "The Intimacy of Trust", category: "vulnerability" },
  { index: 68, title: "Your Body as Guidance", category: "embodiment" },
  { index: 69, title: "The Grace of Asking", category: "communication" },
  { index: 70, title: "Belonging Without Performing", category: "authenticity" },
  { index: 71, title: "The Bravery in Gentleness", category: "strength" },
  { index: 72, title: "Deepening Your Breath", category: "embodiment" },
  { index: 73, title: "The Medicine of Being Seen", category: "healing" },
  { index: 74, title: "Desire Without Desperation", category: "desire" },
  { index: 75, title: "The Courage to Be Still", category: "presence" },
  { index: 76, title: "What It Means to Be Held", category: "intimacy" },
  { index: 77, title: "The Truth in Silence", category: "presence" },
  { index: 78, title: "Permission to Want", category: "desire" },
  { index: 79, title: "The Wisdom in Your Hesitation", category: "intuition" },
  { index: 80, title: "Softening the Hard Places", category: "vulnerability" },
  { index: 81, title: "The Gift of Being Chosen", category: "connection" },
  { index: 82, title: "Coming Back to Your Body", category: "embodiment" },
  { index: 83, title: "The Intimacy of Saying No", category: "boundaries" },
  { index: 84, title: "What Presence Really Is", category: "embodiment" },
  { index: 85, title: "Permission to Thaw", category: "vulnerability" },
  { index: 86, title: "The Courage to Connect", category: "connection" },
  { index: 87, title: "Your Body Deserves Attention", category: "embodiment" },
  { index: 88, title: "The Grace of Being Imperfect", category: "authenticity" },
  { index: 89, title: "Desire as a Teacher", category: "sexuality" },
  { index: 90, title: "The Sacred in Sexual Connection", category: "spirituality" },
  { index: 91, title: "Belonging to the Body", category: "embodiment" },
  { index: 92, title: "The Truth Your Touch Speaks", category: "intimacy" },
  { index: 93, title: "Permission to Soften", category: "vulnerability" },
  { index: 94, title: "What It Means to Be Held", category: "intimacy" },
  { index: 95, title: "The Courage of Tenderness", category: "strength" },
  { index: 96, title: "Coming Home to Yourself", category: "presence" },
  { index: 97, title: "The Wisdom of Your Body", category: "embodiment" },
  { index: 98, title: "Desire Without Apology", category: "desire" },
  { index: 99, title: "The Gift of Simple Presence", category: "connection" },
  { index: 100, title: "Permission to Be Alive", category: "authenticity" },
  { index: 101, title: "The Bravery of Asking", category: "communication" },
  { index: 102, title: "What Touch Can Heal", category: "intimacy" },
  { index: 103, title: "The Sacred Feminine", category: "spirituality" },
  { index: 104, title: "Permission to Receive", category: "vulnerability" },
  { index: 105, title: "The Truth of Loneliness", category: "emotion" },
  { index: 106, title: "What Acceptance Looks Like", category: "authenticity" },
  { index: 107, title: "The Courage to Be Quiet", category: "presence" },
  { index: 108, title: "Your Desire Matters", category: "sexuality" },
  { index: 109, title: "The Grace of Being Here", category: "presence" },
  { index: 110, title: "Permission to Feel Everything", category: "emotion" },
  { index: 111, title: "The Intimacy of Truth", category: "authenticity" },
  { index: 112, title: "What Your Longing Reveals", category: "desire" },
  { index: 113, title: "The Sacred in Simplicity", category: "spirituality" },
  { index: 114, title: "Coming Back to Now", category: "embodiment" },
  { index: 115, title: "The Wisdom of Saying Yes", category: "desire" },
  { index: 116, title: "Permission to Be Needed", category: "vulnerability" },
  { index: 117, title: "The Courage of Showing Up", category: "connection" },
  { index: 118, title: "What Belonging Feels Like", category: "community" },
  { index: 119, title: "The Gift of Returning", category: "presence" },
];



export const quotes = [
  { index: 0, quote: "To receive is not to surrender your strength. It is to trust that someone else's offering comes from care." },
  { index: 1, quote: "Your body speaks a language your mind has not yet learned. It knows when you are being true." },
  { index: 2, quote: "The courage to ask is not learned. It is remembered. Every time you ask, you strengthen your capacity." },
  { index: 3, quote: "Your body has been holding what your mind couldn't process. Listen to what it is trying to tell you." },
  { index: 4, quote: "Friendship without performance is friendship that breathes. The freedom to show up tired and be welcomed." },
  { index: 5, quote: "Desire without shame is desire that is alive. It tells you what feeds your soul." },
  { index: 6, quote: "Touch without obligation is touch as medicine. It is presence without expectation." },
  { index: 7, quote: "Resting the armor means taking off the weight you've been carrying. You are safe enough now." },
  { index: 8, quote: "Privacy is a healthy boundary. Hiding is protection from connection. Know the difference." },
  { index: 9, quote: "Making room for wanting means admitting what you desire. That matters." },
  { index: 10, quote: "Presence is a practice because it must be returned to constantly." },
  { index: 11, quote: "Your body is a home—not a problem to fix, but a place to inhabit." },
  { index: 12, quote: "Listening without fixing is a rare gift. It is simply staying present." },
  { index: 13, quote: "Your feelings deserve permission to exist. Not judgment, not analysis, just space." },
  { index: 14, quote: "You are safe here. You can slow down. Rest is allowed." },
  { index: 15, quote: "Softness is the courage to move without armor. That is true strength." },
  { index: 16, quote: "Your truth matters more than anyone's comfort." },
  { index: 17, quote: "To belong is to be known, fully seen and chosen anyway." },
  { index: 18, quote: "What you've been protecting has been protecting you. Release it when you're ready." },
  { index: 19, quote: "Your body speaks through sensation, impulse, knowing. Learn its language." },
  { index: 20, quote: "Being wanted—not needed, but chosen for who you are—is the deepest intimacy." },
  { index: 21, quote: "Asking for help is the gift you give others. It says they matter." },
  { index: 22, quote: "Your desire is information. It shows you what makes you feel alive." },
  { index: 23, quote: "When you stop performing, what emerges is real." },
  { index: 24, quote: "Your breath is home. When uncertain, return to your breath." },
  { index: 25, quote: "The bravery in being ordinary is being yourself without apology." },
  { index: 26, quote: "Touch is a language. Across all boundaries, it communicates belonging." },
  { index: 27, quote: "Speaking your truth quietly still means speaking your truth." },
  { index: 28, quote: "Your body never lies. What it says no to is no." },
  { index: 29, quote: "Your longing is information about your becoming." },
  { index: 30, quote: "Invitation and consent are the foundation of real connection." },
  { index: 31, quote: "Real support meets you where you are. It doesn't require you to change first." },
  { index: 32, quote: "The courage to be seen means trusting that being known won't destroy you." },
  { index: 33, quote: "Intimacy without urgency is intimacy that can breathe and deepen." },
  { index: 34, quote: "Your presence itself is powerful. The quiet strength of simply being here." },
  { index: 35, quote: "Healing comes when you show up for yourself, over and over again." },
  { index: 36, quote: "Your defenses protected you. Honor them. Then release them when ready." },
  { index: 37, quote: "Your hesitation is wisdom. It is telling you something true." },
  { index: 38, quote: "To belong to yourself first means you cannot abandon yourself for someone else." },
  { index: 39, quote: "Grace lives in slowing down. When you slow, you arrive at yourself." },
  { index: 40, quote: "Notice without judgment. Your thoughts and feelings are all welcome." },
  { index: 41, quote: "Being heard is being seen. When someone truly listens, they witness you." },
  { index: 42, quote: "Softening teaches what hardness cannot. It teaches you what you're made of." },
  { index: 43, quote: "Your body never lies. Its signals are always truthful." },
  { index: 44, quote: "Grief is the price of love. It is sacred and deserves your attention." },
  { index: 45, quote: "Asking without shame means wanting something and not apologizing for it." },
  { index: 46, quote: "The space between two souls who are fully present is sacred." },
  { index: 47, quote: "Coming home means arriving at a place where you can finally rest." },
  { index: 48, quote: "Your deepest desires are a form of prayer. Listen to what they ask for." },
  { index: 49, quote: "Vulnerability is bravery operating without armor." },
  { index: 50, quote: "Tenderness is a way of being. Gentle, open, present." },
  { index: 51, quote: "Your attention is one of the most precious gifts you can offer." },
  { index: 52, quote: "Breaking silence inside means speaking what you have kept hidden." },
  { index: 53, quote: "The courage to rest means stopping the constant doing." },
  { index: 54, quote: "Beneath your words is a deeper need. Learn to hear it." },
  { index: 55, quote: "The sacred is here—in ordinary moments, ordinary people, ordinary days." },
  { index: 56, quote: "Your willingness to be vulnerable is revolutionary." },
  { index: 57, quote: "Your body speaks through sensation, impulse, and ancient knowing." },
  { index: 58, quote: "Connection is medicine. Deep presence with another heals." },
  { index: 59, quote: "Your longing shows what your soul needs. Pay attention." },
  { index: 60, quote: "Permission to be whole means accepting all of yourself—shadow and light." },
  { index: 61, quote: "Wisdom in boundaries is knowing what is yours to carry." },
  { index: 62, quote: "To be known and loved fully is the deepest intimacy possible." },
  { index: 63, quote: "The courage to start again lives in each moment." },
  { index: 64, quote: "Your presence is love. When you show up fully, you say: you matter." },
  { index: 65, quote: "A sacred pause is a breath. It is where you arrive at yourself." },
  { index: 66, quote: "Shame whispers lies. The truth is you belong." },
  { index: 67, quote: "The intimacy of trust is built moment by moment." },
  { index: 68, quote: "Your body knows what is right for you before your mind understands." },
  { index: 69, quote: "Grace lives in asking. When you ask, you give others power to matter." },
  { index: 70, quote: "You already belong. Your place was made for you." },
  { index: 71, quote: "The bravery in gentleness is moving without hardness, without armor." },
  { index: 72, quote: "Deepen your breath and you deepen your presence." },
  { index: 73, quote: "Being seen is medicine when the witness is kind." },
  { index: 74, quote: "You can want something without needing it to complete you." },
  { index: 75, quote: "The courage to be still is radical in a world obsessed with doing." },
  { index: 76, quote: "To be held is to be safe. You don't have to carry yourself." },
  { index: 77, quote: "The truth in silence emerges when you stop filling space with words." },
  { index: 78, quote: "Permission to want means finally admitting what you desire." },
  { index: 79, quote: "Your hesitation is wisdom. It is your deeper self protecting you." },
  { index: 80, quote: "Softening the hard places means releasing protection you no longer need." },
  { index: 81, quote: "To be chosen is to be told: you matter." },
  { index: 82, quote: "Your body has been waiting. Every time you listen, you tell it: you matter." },
  { index: 83, quote: "Saying no is an act of love. It creates space for authentic yes." },
  { index: 84, quote: "Presence is not a destination. It is simply being here now." },
  { index: 85, quote: "If you have frozen yourself, you can thaw. Your warmth is waiting." },
  { index: 86, quote: "The courage to connect means showing up over and over again." },
  { index: 87, quote: "Your body deserves care—not as punishment, but as love." },
  { index: 88, quote: "Your imperfections are your humanity. They are where connection becomes possible." },
  { index: 89, quote: "Your desire teaches you about yourself. Pay attention." },
  { index: 90, quote: "Sex can be sacred—two people choosing vulnerability together." },
  { index: 91, quote: "Your body is not something you have. It is something you are." },
  { index: 92, quote: "Your touch speaks truth. It says: you matter, you're not alone, I choose you." },
  { index: 93, quote: "You can soften without losing yourself." },
  { index: 94, quote: "To be held is to know your weight is supported." },
  { index: 95, quote: "The courage of tenderness is fiercely strong." },
  { index: 96, quote: "All seeking outside points you back to yourself." },
  { index: 97, quote: "Your body's wisdom is always available when you trust it." },
  { index: 98, quote: "You want what you want. There is no need to apologize or justify it." },
  { index: 99, quote: "Simple presence is enough. Just you and another, together." },
  { index: 100, quote: "You are allowed to be alive. Not just surviving, but fully alive." },
  { index: 101, quote: "Asking for help takes bravery. It says their strength matters." },
  { index: 102, quote: "Touch is medicine. It heals what words cannot." },
  { index: 103, quote: "The sacred feminine is receptivity and strength both." },
  { index: 104, quote: "To receive is to open. It is an active choice to be vulnerable." },
  { index: 105, quote: "Loneliness teaches you what you need. Your loneliness is information." },
  { index: 106, quote: "Acceptance is not resignation. It is the freedom to work with what is." },
  { index: 107, quote: "Speaking your truth quietly still means speaking it." },
  { index: 108, quote: "Your desire matters. It is not trivial or selfish." },
  { index: 109, quote: "Grace is in simply being here. That is all that is required." },
  { index: 110, quote: "You are allowed to feel everything. All your feelings are valid." },
  { index: 111, quote: "When you speak what is true, you offer the most valuable thing: yourself." },
  { index: 112, quote: "What you long for reveals what you need. Your longing is your becoming." },
  { index: 113, quote: "The sacred is hidden in simplicity. A quiet moment, a held hand." },
  { index: 114, quote: "Coming back to now is coming home. Right here, right now." },
  { index: 115, quote: "Every yes to what matters strengthens your capacity for yes." },
  { index: 116, quote: "You are allowed to be needed. Being needed is the experience of mattering." },
  { index: 117, quote: "Showing up is enough. You don't need to be perfect." },
  { index: 118, quote: "Belonging is the feeling of being wanted for who you are." },
  { index: 119, quote: "Every time you return, you practice what matters most." },
];

export const reflectionPrompts = [
  { index: 0, prompt: "Where in your life are you guarded instead of open?" },
  { index: 1, prompt: "What part of yourself are you afraid to let be known?" },
  { index: 2, prompt: "What do you most need to ask for, and what's stopping you?" },
  { index: 3, prompt: "What has your body been storing that your mind hasn't acknowledged?" },
  { index: 4, prompt: "Where do you perform instead of letting yourself be cared for?" },
  { index: 5, prompt: "What desire do you feel shame about?" },
  { index: 6, prompt: "Where do you expect something in return for your presence or touch?" },
  { index: 7, prompt: "What armor are you wearing, and what would you feel if you took it off?" },
  { index: 8, prompt: "How do you hide, and how is that different from protecting your privacy?" },
  { index: 9, prompt: "What are you longing to want, but haven't given yourself permission to?" },
  { index: 10, prompt: "How present are you with the people and moments that matter most?" },
  { index: 11, prompt: "How would it feel to treat your body as a home instead of a project?" },
  { index: 12, prompt: "When someone is struggling, do you listen or jump to fixing them?" },
  { index: 13, prompt: "What feeling are you not allowing yourself to experience?" },
  { index: 14, prompt: "Where are you still rushing, even when it's safe to slow down?" },
  { index: 15, prompt: "Where do you think softness makes you weak?" },
  { index: 16, prompt: "What truth have you been afraid to say out loud?" },
  { index: 17, prompt: "Where do you still not believe you belong?" },
  { index: 18, prompt: "What have you been protecting at the cost of your own freedom?" },
  { index: 19, prompt: "What is your body trying to communicate right now?" },
  { index: 20, prompt: "Do you feel wanted for who you are, or needed for what you do?" },
  { index: 21, prompt: "What would you ask for if you didn't have to earn the help first?" },
  { index: 22, prompt: "What does your desire reveal about what you truly need?" },
  { index: 23, prompt: "What happens inside you when you stop trying to be impressive?" },
  { index: 24, prompt: "What does your breath know that your thinking mind hasn't figured out?" },
  { index: 25, prompt: "What is ordinary and real about you that you've been hiding?" },
  { index: 26, prompt: "Where in your life do you experience touch without transaction?" },
  { index: 27, prompt: "What truth is asking to be spoken, even if it's soft?" },
  { index: 28, prompt: "What does your body know that contradicts what you believe?" },
  { index: 29, prompt: "What are you longing for, and what does that longing reveal?" },
  { index: 30, prompt: "Where do you need to ask for explicit consent or permission?" },
  { index: 31, prompt: "What does real support look like to you?" },
  { index: 32, prompt: "What courage would it take to let yourself be fully seen?" },
  { index: 33, prompt: "Can you imagine intimacy without urgency or pressure?" },
  { index: 34, prompt: "Where does your presence naturally calm or steady others?" },
  { index: 35, prompt: "Where do you still feel abandoned, and how are you abandoning yourself?" },
  { index: 36, prompt: "How have your defenses protected you, and what did that protection cost?" },
  { index: 37, prompt: "What is your hesitation trying to protect you from?" },
  { index: 38, prompt: "How do you show up for yourself with the same care you show others?" },
  { index: 39, prompt: "Where can you afford to slow down and actually feel what's here?" },
  { index: 40, prompt: "What feelings are you judging instead of simply noticing?" },
  { index: 41, prompt: "When has someone truly heard you, and what did that make possible?" },
  { index: 42, prompt: "What has happened inside you when you stopped trying to be strong?" },
  { index: 43, prompt: "What is your body telling you that contradicts what you've been told?" },
  { index: 44, prompt: "What loss or sadness have you not allowed yourself to feel?" },
  { index: 45, prompt: "What would you ask for if shame wasn't in the way?" },
  { index: 46, prompt: "When have you felt most spiritually connected to another person?" },
  { index: 47, prompt: "Where do you finally feel at home—with yourself or in a place?" },
  { index: 48, prompt: "What desire feels sacred or spiritual to you?" },
  { index: 49, prompt: "Where is your vulnerability actually your greatest strength?" },
  { index: 50, prompt: "How do you embody tenderness as a way of being, not just an emotion?" },
  { index: 51, prompt: "When have you felt truly seen and valued just for your presence?" },
  { index: 52, prompt: "What truth inside you is still hiding in silence?" },
  { index: 53, prompt: "What are you trying to accomplish before you allow yourself to rest?" },
  { index: 54, prompt: "What are you really asking for underneath your words?" },
  { index: 55, prompt: "Where do you find the sacred in everyday moments?" },
  { index: 56, prompt: "How has your willingness to be vulnerable changed things?" },
  { index: 57, prompt: "What is your body communicating through sensations and impulses?" },
  { index: 58, prompt: "How has deep connection with someone healed you?" },
  { index: 59, prompt: "What are you longing for, and what does that reveal about your needs?" },
  { index: 60, prompt: "What would it feel like to accept all of yourself—shadow and light?" },
  { index: 61, prompt: "Where do you need boundaries, and what would honoring them look like?" },
  { index: 62, prompt: "Can you imagine being fully known and fully loved for it?" },
  { index: 63, prompt: "What old pattern about yourself are you ready to release?" },
  { index: 64, prompt: "How does your presence change when you are acting from love?" },
  { index: 65, prompt: "What happens inside you when you pause and just breathe?" },
  { index: 66, prompt: "What is shame saying about you, and is it true?" },
  { index: 67, prompt: "Where do you most trust someone, and what makes that possible?" },
  { index: 68, prompt: "How does your body guide you toward what's right for you?" },
  { index: 69, prompt: "What would be different if you asked for help without hesitation?" },
  { index: 70, prompt: "Where are you still trying to earn your place instead of simply taking it?" },
  { index: 71, prompt: "Where is gentleness actually the bravest choice you can make?" },
  { index: 72, prompt: "What happens when you deepen into your breath and slow down?" },
  { index: 73, prompt: "What becomes possible when you are truly seen?" },
  { index: 74, prompt: "Can you want something without desperation or shame?" },
  { index: 75, prompt: "What courage does it take for you to be still?" },
  { index: 76, prompt: "When do you feel most held and safe?" },
  { index: 77, prompt: "What truth lives in the silence you keep?" },
  { index: 78, prompt: "What do you genuinely want to give yourself permission to have?" },
  { index: 79, prompt: "What is your hesitation protecting you from knowing?" },
  { index: 80, prompt: "Where have you hardened, and what would softening cost you?" },
  { index: 81, prompt: "What does it feel like to be genuinely chosen?" },
  { index: 82, prompt: "How would your life change if you came back to your body fully?" },
  { index: 83, prompt: "When is it an act of love to say no?" },
  { index: 84, prompt: "What is presence, really—what does it feel like in your body?" },
  { index: 85, prompt: "What have you frozen in yourself that's ready to thaw?" },
  { index: 86, prompt: "What would it take for you to truly connect with someone?" },
  { index: 87, prompt: "What does your body want you to know about self-care?" },
  { index: 88, prompt: "Where are your imperfections actually your gifts?" },
  { index: 89, prompt: "What does your desire teach you about yourself?" },
  { index: 90, prompt: "How is sexual intimacy sacred or spiritual for you?" },
  { index: 91, prompt: "How does inhabiting your body fully change everything?" },
  { index: 92, prompt: "What truth does your touch communicate without words?" },
  { index: 93, prompt: "Where can you soften without losing yourself?" },
  { index: 94, prompt: "When do you feel most held and safe?" },
  { index: 95, prompt: "Where is tenderness an act of courage?" },
  { index: 96, prompt: "Where do you finally come home to who you actually are?" },
  { index: 97, prompt: "What wisdom from your body are you ignoring?" },
  { index: 98, prompt: "What do you want without apology or explanation?" },
  { index: 99, prompt: "What is the gift of simply being here, together?" },
  { index: 100, prompt: "What would it feel like to truly be alive in every moment?" },
  { index: 101, prompt: "What do you need the courage to ask for?" },
  { index: 102, prompt: "How can touch heal what words cannot?" },
  { index: 103, prompt: "What does sacred feminine energy mean to you?" },
  { index: 104, prompt: "What would you receive if you opened to it?" },
  { index: 105, prompt: "Where do you feel lonely, and what is that showing you?" },
  { index: 106, prompt: "What would accepting yourself completely change?" },
  { index: 107, prompt: "Where can you speak your truth more quietly?" },
  { index: 108, prompt: "What does your desire matter to you?" },
  { index: 109, prompt: "What is the grace of simply showing up?" },
  { index: 110, prompt: "What feelings are you finally ready to let yourself have?" },
  { index: 111, prompt: "What truth about yourself are you ready to speak?" },
  { index: 112, prompt: "What does your longing reveal about your deepest needs?" },
  { index: 113, prompt: "Where is the sacred hidden in simplicity?" },
  { index: 114, prompt: "What would it mean to come fully back to this moment?" },
  { index: 115, prompt: "What are you ready to say yes to?" },
  { index: 116, prompt: "Where do you want to be needed and valued?" },
  { index: 117, prompt: "What courage does it take to show up as yourself?" },
  { index: 118, prompt: "What does belonging actually feel like?" },
  { index: 119, prompt: "What becomes possible when you return to yourself?" },
];

export const embodimentPractices = [
  { index: 0, practice: "Place one hand on your chest and one on your belly. Receive support." },
  { index: 1, practice: "Notice where you're performing instead of being present." },
  { index: 2, practice: "Practice asking for one small thing today. Notice how it feels." },
  { index: 3, practice: "Place hands on your body and listen. What is it telling you?" },
  { index: 4, practice: "Spend time with someone you trust without giving anything back." },
  { index: 5, practice: "Notice one desire you've been quiet about. Say it silently." },
  { index: 6, practice: "Observe which touches feel obligatory and which feel like gift." },
  { index: 7, practice: "Stand with feet on ground. Feel the earth supporting you." },
  { index: 8, practice: "Examine how you hide and protect privacy. Notice the difference." },
  { index: 9, practice: "Write three things you want without editing." },
  { index: 10, practice: "Pause before responding. Let your answer come from your body." },
  { index: 11, practice: "Lie down and notice every point where your body touches ground." },
  { index: 12, practice: "Listen to someone without offering advice." },
  { index: 13, practice: "Identify one feeling you've suppressed. Give it five minutes." },
  { index: 14, practice: "Stop. Slow down. Notice what's actually here." },
  { index: 15, practice: "Notice where you're soft and where you're defended." },
  { index: 16, practice: "Say one true thing today, even if uncomfortable." },
  { index: 17, practice: "Notice where you belong without trying." },
  { index: 18, practice: "Examine one protection you've built. What was it protecting from?" },
  { index: 19, practice: "Close your eyes. What sensations are in your body right now?" },
  { index: 20, practice: "Ask yourself: who wants me for me, not for what I do?" },
  { index: 21, practice: "Say 'I need help' once. Feel what happens." },
  { index: 22, practice: "Notice what you desire today. Don't judge it." },
  { index: 23, practice: "Stop performing for one hour. Be yourself." },
  { index: 24, practice: "Focus on your breath. Come home to it." },
  { index: 25, practice: "Do something ordinary and notice its beauty." },
  { index: 26, practice: "Explore how touch feels different with different people." },
  { index: 27, practice: "Speak a small truth softly today." },
  { index: 28, practice: "Place your hand on your body and trust what it's telling you." },
  { index: 29, practice: "What are you reaching toward? Let yourself want it." },
  { index: 30, practice: "Ask someone for explicit consent. Notice what that creates." },
  { index: 31, practice: "Receive support without explaining or justifying." },
  { index: 32, practice: "Imagine being fully seen. What's your first response?" },
  { index: 33, practice: "Spend time with someone without rushing." },
  { index: 34, practice: "Sit in your presence without doing anything." },
  { index: 35, practice: "Notice where you abandon yourself. Show up for yourself." },
  { index: 36, practice: "Thank a defense that has protected you." },
  { index: 37, practice: "Listen to your hesitation. What is it protecting?" },
  { index: 38, practice: "Do one thing today for yourself, not for anyone else." },
  { index: 39, practice: "Pause and slow down. Feel the grace." },
  { index: 40, practice: "Notice your thoughts without judging them." },
  { index: 41, practice: "Have someone really listen to you." },
  { index: 42, practice: "Notice where you've hardened. What would softening feel like?" },
  { index: 43, practice: "Trust what your body is communicating." },
  { index: 44, practice: "Allow yourself to grieve something." },
  { index: 45, practice: "Ask for something without shame." },
  { index: 46, practice: "Sit in silence with someone." },
  { index: 47, practice: "Come home to a person or a place." },
  { index: 48, practice: "Notice your deepest desire." },
  { index: 49, practice: "Be vulnerable about something today." },
  { index: 50, practice: "Move through the world gently." },
  { index: 51, practice: "Give someone your full presence." },
  { index: 52, practice: "Speak something you've kept silent." },
  { index: 53, practice: "Rest. Do nothing." },
  { index: 54, practice: "Listen beneath someone's words." },
  { index: 55, practice: "Slow down and feel sacred in the ordinary." },
  { index: 56, practice: "Let your vulnerability be your power." },
  { index: 57, practice: "Speak your body's language." },
  { index: 58, practice: "Connect deeply with someone." },
  { index: 59, practice: "Notice what you long for." },
  { index: 60, practice: "Accept all of yourself today." },
  { index: 61, practice: "Set one boundary as an act of love." },
  { index: 62, practice: "Imagine being fully known and loved." },
  { index: 63, practice: "Let something old go." },
  { index: 64, practice: "Be present with someone with your whole being." },
  { index: 65, practice: "Pause and breathe. Feel the sacredness." },
  { index: 66, practice: "Notice shame and speak it out loud." },
  { index: 67, practice: "Trust someone a little more today." },
  { index: 68, practice: "Ask your body what it knows." },
  { index: 69, practice: "Ask for help." },
  { index: 70, practice: "Notice: do you belong without earning it?" },
  { index: 71, practice: "Approach something with gentleness instead of force." },
  { index: 72, practice: "Breathe slowly and deeply." },
  { index: 73, practice: "Let someone see you." },
  { index: 74, practice: "Want something without needing it." },
  { index: 75, practice: "Sit still and feel your strength." },
  { index: 76, practice: "Let someone hold you." },
  { index: 77, practice: "Sit in silence and listen to yourself." },
  { index: 78, practice: "Want something without apologizing." },
  { index: 79, practice: "Trust your deeper knowing." },
  { index: 80, practice: "Release hardness. Let softness emerge." },
  { index: 81, practice: "Let someone choose you." },
  { index: 82, practice: "Come home to your body." },
  { index: 83, practice: "Say no with love." },
  { index: 84, practice: "Simply be present." },
  { index: 85, practice: "Thaw from the inside out." },
  { index: 86, practice: "Show up, even scared." },
  { index: 87, practice: "Touch your body with care." },
  { index: 88, practice: "Notice your imperfections and call them beautiful." },
  { index: 89, practice: "Follow your desire." },
  { index: 90, practice: "Experience a sacred moment." },
  { index: 91, practice: "Inhabit your body fully." },
  { index: 92, practice: "Touch softly and receive touch softly." },
  { index: 93, practice: "Let your softness be your choice." },
  { index: 94, practice: "Return to yourself fully." },
  { index: 95, practice: "Trust your body's wisdom." },
  { index: 96, practice: "Want unapologetically." },
  { index: 97, practice: "Be present, together." },
  { index: 98, practice: "Be alive in every moment." },
  { index: 99, practice: "Ask for what you need." },
  { index: 100, practice: "Let touch heal you." },
  { index: 101, practice: "Embrace your full strength." },
  { index: 102, practice: "Open to receive." },
  { index: 103, practice: "Feel your loneliness and listen to it." },
  { index: 104, practice: "Accept what is." },
  { index: 105, practice: "Speak your truth, however softly." },
  { index: 106, practice: "Let your desire matter." },
  { index: 107, practice: "Just be here." },
  { index: 108, practice: "Feel all your feelings." },
  { index: 109, practice: "Speak your truth out loud." },
  { index: 110, practice: "Listen to your longing." },
  { index: 111, practice: "Find the sacred in simple moments." },
  { index: 112, practice: "Come back to now." },
  { index: 113, practice: "Say yes to what matters." },
  { index: 114, practice: "Let yourself be needed." },
  { index: 115, practice: "Show up as you are." },
  { index: 116, practice: "Feel what belonging feels like." },
  { index: 117, practice: "Return to yourself." },
];

export const bodyCheckIns = [
  { index: 0, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 1, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 2, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 3, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 4, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 5, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 6, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 7, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 8, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 9, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 10, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 11, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 12, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 13, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 14, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 15, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 16, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 17, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 18, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 19, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 20, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 21, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 22, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 23, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 24, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 25, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 26, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 27, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 28, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 29, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 30, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 31, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 32, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 33, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 34, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 35, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 36, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 37, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 38, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 39, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 40, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 41, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 42, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 43, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 44, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 45, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 46, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 47, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 48, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 49, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 50, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 51, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 52, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 53, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 54, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 55, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 56, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 57, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 58, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 59, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 60, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 61, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 62, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 63, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 64, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 65, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 66, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 67, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 68, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 69, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 70, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 71, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 72, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 73, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 74, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 75, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 76, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 77, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 78, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 79, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 80, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 81, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 82, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 83, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 84, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 85, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 86, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 87, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 88, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 89, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 90, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 91, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 92, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 93, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 94, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 95, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 96, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 97, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 98, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 99, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 100, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 101, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 102, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 103, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 104, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 105, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 106, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 107, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 108, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 109, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 110, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 111, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 112, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 113, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 114, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 115, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 116, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 117, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 118, prompt: "Where does your body feel most aligned with this theme?" },
  { index: 119, prompt: "Where does your body feel most aligned with this theme?" },
];

export const conversationInvitations = [
  { index: 0, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 1, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 2, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 3, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 4, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 5, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 6, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 7, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 8, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 9, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 10, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 11, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 12, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 13, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 14, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 15, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 16, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 17, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 18, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 19, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 20, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 21, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 22, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 23, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 24, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 25, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 26, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 27, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 28, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 29, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 30, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 31, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 32, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 33, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 34, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 35, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 36, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 37, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 38, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 39, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 40, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 41, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 42, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 43, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 44, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 45, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 46, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 47, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 48, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 49, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 50, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 51, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 52, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 53, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 54, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 55, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 56, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 57, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 58, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 59, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 60, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 61, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 62, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 63, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 64, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 65, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 66, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 67, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 68, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 69, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 70, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 71, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 72, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 73, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 74, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 75, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 76, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 77, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 78, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 79, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 80, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 81, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 82, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 83, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 84, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 85, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 86, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 87, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 88, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 89, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 90, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 91, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 92, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 93, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 94, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 95, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 96, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 97, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 98, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 99, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 100, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 101, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 102, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 103, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 104, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 105, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 106, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 107, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 108, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 109, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 110, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 111, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 112, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 113, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 114, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 115, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 116, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 117, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 118, invitation: "Ask someone: 'How does this theme show up for you?'" },
  { index: 119, invitation: "Ask someone: 'How does this theme show up for you?'" },
];

export const weeklyTrevorNotes = [
  {
    week: 1,
    title: "Welcome to The Connection Room",
    body: "The moment you arrive here, you're already enough. Not someday. Not after you figure things out. Now. This space exists because I believe that real connection begins with radical honesty. Not the performative kind—the kind that costs something. The kind that requires vulnerability. Here, you'll meet men doing the same work you are: learning to soften without becoming fragile, learning to desire without shame, learning to belong without performing. Your presence matters. Your truth matters. Welcome.",
    prompt_snapshot: "What drew you here today?",
    space_suggestion: "commons",
  },
  {
    week: 2,
    title: "The Courage to Ask",
    body: "I've noticed that men have been trained to assume, to figure it out, to never ask. We learned early that asking means weakness. Needing means failure. So we live in a strange isolation, surrounded by people but never truly known. What if asking is actually the gateway to connection? What if the people in your life are waiting for you to trust them enough to ask? This week, I want to invite you to ask one genuine question of someone you trust. Not the small talk kind. A real question. Then listen to the answer.",
    prompt_snapshot: "What are you really asking for?",
    space_suggestion: "commons",
  },
  {
    week: 3,
    title: "What Your Body Knows",
    body: "Most of us live from the neck up. Our bodies become vehicles for accomplishment, not channels for wisdom. But your body knows things your mind hasn't figured out yet. It knows safety from danger. It knows who to trust and who to protect yourself from. It knows when you're longing before your words catch up. This week, I'm asking you to befriend your body. Not to fix it. Not to prove anything with it. Just to listen. Slow down. Pay attention. What's it been trying to tell you?",
    prompt_snapshot: "What has your body been holding?",
    space_suggestion: "embodiment",
  },
  {
    week: 4,
    title: "The Truth About Loneliness",
    body: "Loneliness is not what you think it is. It's not the absence of people. It's the absence of being known. You can be in a crowded room and profoundly lonely if nobody sees you. You can be alone and completely at peace if you're at home in yourself. This is why real connection matters so much. Not because we can't survive without it, but because our deepest longing is to be known by someone. And to know someone. This week, reach out to one person and let them see a part of you that's usually hidden.",
    prompt_snapshot: "What part of yourself are you still hiding?",
    space_suggestion: "commons",
  },
  {
    week: 5,
    title: "Permission to Feel",
    body: "You weren't taught to feel. You were taught to manage, to solve, to move forward. To stay composed. To never let them see you sweat. But your feelings are not a problem to overcome. They're information. They're your inner compass pointing toward what matters. Toward what needs attention. This week, I want you to feel something fully. Not to fix it. Not to move past it quickly. Just to let it be there. To listen to what it's trying to teach you. Your feelings matter.",
    prompt_snapshot: "What emotion are you avoiding?",
    space_suggestion: "commons",
  },
  {
    week: 6,
    title: "Desire Without Shame",
    body: "Desire is not shameful. It's human. It's divine. It's the life force moving through you. But men have complicated relationships with desire. We either suppress it entirely or act it out carelessly. There's no middle ground. What if there was? What if you could acknowledge your desire without being defined by it? What if desire could be a conversation rather than a compulsion? This week, I'm inviting you to name one desire and say it out loud. Not to anyone else. Just to yourself. Just once.",
    prompt_snapshot: "What desire have you been ashamed of?",
    space_suggestion: "dating-desire",
  },
  {
    week: 7,
    title: "The Grace of Slowing Down",
    body: "We live in a culture of speed. Faster, more, now. But the deepest things happen slowly. Trust is built slowly. Intimacy deepens slowly. Presence emerges slowly. Your body knows this. It's constantly asking you to slow down. To breathe. To notice. This week, do one thing slowly. Consciously. One meal. One conversation. One moment. Not because you're being productive. But because it's the only way to be alive.",
    prompt_snapshot: "Where are you rushing that should be slowed?",
    space_suggestion: "intimacy-patterns",
  },
  {
    week: 8,
    title: "Receiving",
    body: "This might be the hardest thing for men to learn: how to receive. We're trained to give. To provide. To take care of. But receiving is not weakness. It's not taking. It's opening a door. It's trusting. It's letting someone matter enough to give. When you refuse to receive, you rob someone of the gift of giving. This week, notice how you respond when someone offers something. Do you immediately rush to reciprocate? Can you just say thank you and let it land?",
    prompt_snapshot: "What would it feel like to simply receive?",
    space_suggestion: "commons",
  },
  {
    week: 9,
    title: "Being Seen",
    body: "The deepest fear is being truly seen. Because if you're seen completely, you can't hide. You can't pretend. You can't protect yourself with a carefully curated version of who you are. And yet, being seen is also the only path to real intimacy. To real love. To real belonging. This week, I want you to practice being slightly more visible. Not all at once. Just a little more real. Just a little more honest. See what happens when you let someone see you.",
    prompt_snapshot: "What part of you is asking to be seen?",
    space_suggestion: "commons",
  },
  {
    week: 10,
    title: "The Body as Home",
    body: "You've been taught that your body is something to manage, to control, to transcend. But what if it's actually a home? A place to return to. A place that's always been waiting for you. When you come back to your body, you come back to yourself. You come back to presence. You come back to truth. This week, spend time getting reacquainted with your body. Not in a forced way. Just with curiosity. What does it feel like to be here?",
    prompt_snapshot: "Where does your body feel most alive?",
    space_suggestion: "touch-affection",
  },
  {
    week: 11,
    title: "Friendship Without Performance",
    body: "Real friendship is rare because most of us have learned to perform even in our closest relationships. We show our accomplishments. We hide our struggles. We present a version of ourselves we think people will accept. But real friendship is what happens when you stop. When you let your guard down. When you risk being ordinary. This week, choose one friend and share something real. Something you usually hide. Something that costs something to say.",
    prompt_snapshot: "What truth have you been keeping from your friends?",
    space_suggestion: "commons",
  },
  {
    week: 12,
    title: "The Courage of Asking for Help",
    body: "We were taught that asking for help is admitting defeat. That real men figure it out alone. But asking for help is actually the most courageous thing you can do. It requires humility. It requires vulnerability. It requires trusting that you matter enough for someone to say yes. This week, ask for help with something. Anything. See what happens when you trust someone enough to need them.",
    prompt_snapshot: "What do you need help with but haven't asked?",
    space_suggestion: "commons",
  },
  {
    week: 13,
    title: "Touch",
    body: "Humans need touch. It's not luxury. It's biological necessity. But many men have learned that touch is only sexual or it's inappropriate. So we go years without being touched or touching anyone. And we lose something essential. This week, I'm inviting you to remember that non-sexual touch is medicine. Whether it's a handshake held a moment longer. A hug instead of a wave. A hand on a shoulder. These small acts of contact remind us that we're not alone.",
    prompt_snapshot: "What kind of touch are you missing?",
    space_suggestion: "touch-affection",
  },
  {
    week: 14,
    title: "Chosen Family",
    body: "Some of us are lucky enough to have families of origin that see us. For many of us, we have to build our own. Chosen family is the people who know your whole truth and choose you anyway. Who show up. Who witness. Who stay. This week, I want you to notice who your chosen family is. And tell them. Not in a big grand way. Just notice it. Acknowledge it. Let it matter.",
    prompt_snapshot: "Who is your chosen family?",
    space_suggestion: "commons",
  },
  {
    week: 15,
    title: "Grief and Longing",
    body: "Most of us have learned to skip over grief. To move quickly to acceptance. But grief is love with nowhere to go. When we skip it, we also skip the depth of knowing what we've loved. This week, I want to invite you to feel what you're longing for. What you've lost. What you're still hoping for. Not to fix it. Just to feel it. Because the feeling itself is the connection to what matters.",
    prompt_snapshot: "What are you grieving?",
    space_suggestion: "commons",
  },
  {
    week: 16,
    title: "Coming Home",
    body: "By now, you've spent four months in this space. You've shared. You've listened. You've grown. And perhaps you've found something you didn't expect: a home. A place where you can be yourself. Where your softness is not weakness. Where your desire is not shame. Where your presence matters. As we complete this cycle, I want you to know: you don't have to earn the right to belong here. You already do. This space exists for you. Keep coming back.",
    prompt_snapshot: "What does home feel like now?",
    space_suggestion: "commons",
  },
];