import { Profile } from "@/lib/data/profiles";

export const demoMembers: Profile[] = [
  {
    id: "demo-marcus-h",
    displayName: "Marcus",
    pronouns: "he/him",
    location: "Los Angeles, CA",
    ageRange: "35-44",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/marcus-h.svg",
    memberType: "individual",
    profile_tagline: "Learning to be vulnerable",
    interests: ["intimacy", "spirituality", "embodiment", "community"],
    whatBroughtYouHere:
      "I was tired of surface-level connections. Wanted to find men who were actually willing to get real.",
    connectionHoping: "Deep conversations about what matters most",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Nurturer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "touch-and-affection", "intimacy-patterns"],
    joinedAt: new Date("2026-04-15"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-15"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-daniel-r",
    displayName: "Daniel",
    pronouns: "he/him",
    location: "San Francisco, CA",
    ageRange: "28-34",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/daniel-r.svg",
    memberType: "individual",
    profile_tagline: "Exploring desire with intention",
    interests: ["sexuality", "couples work", "embodiment", "dating"],
    whatBroughtYouHere:
      "My partner and I wanted to explore desire together in a safe space with other couples.",
    connectionHoping: "Honest conversations about what real connection looks like",
    pairingComfortLevel: "Somewhat comfortable",
    quizResult: "The Explorer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "couples-closeness"],
    joinedAt: new Date("2026-05-02"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-02"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-james-t",
    displayName: "James",
    pronouns: "he/him",
    location: "Portland, OR",
    ageRange: "42-50",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/james-t.svg",
    memberType: "individual",
    profile_tagline: "Looking for depth in my 40s",
    interests: ["spirituality", "masculinity", "community", "intimacy"],
    whatBroughtYouHere:
      "I felt alone even in a city full of gay men. This space felt different—like people actually care.",
    connectionHoping: "Real friendships with men who are doing their inner work",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Philosopher",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "spirituality-sexuality", "masculinity-sexuality"],
    joinedAt: new Date("2026-04-28"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-28"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-alex-m",
    displayName: "Alex",
    pronouns: "he/him",
    location: "Austin, TX",
    ageRange: "25-27",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/alex-m.svg",
    memberType: "individual",
    profile_tagline: "Just starting to understand myself",
    interests: ["embodiment", "dating", "community", "connection"],
    whatBroughtYouHere:
      "I realized I don't know who I am as a sexual being. Wanted to explore that with support.",
    connectionHoping: "To feel less alone in figuring out what I want",
    pairingComfortLevel: "New to this",
    quizResult: "The Seeker",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "embodiment"],
    joinedAt: new Date("2026-05-10"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-10"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-chris-w",
    displayName: "Chris",
    pronouns: "he/him",
    location: "Seattle, WA",
    ageRange: "38-41",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/chris-w.svg",
    memberType: "individual",
    profile_tagline: "Opening up my relationship",
    interests: ["couples work", "communication", "spirituality", "intimacy"],
    whatBroughtYouHere:
      "My partner and I opened up our relationship and needed guidance on how to do it with love.",
    connectionHoping: "To learn from other couples navigating non-traditional relationships",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Bridge Builder",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "couples-closeness", "spirituality-sexuality"],
    joinedAt: new Date("2026-04-05"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-05"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-jordan-k",
    displayName: "Jordan",
    pronouns: "he/him",
    location: "Denver, CO",
    ageRange: "31-34",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/jordan-k.svg",
    memberType: "individual",
    profile_tagline: "Healing touch and closeness",
    interests: ["touch", "intimacy", "embodiment", "spirituality"],
    whatBroughtYouHere:
      "My partner grew up with no safe touch. I wanted to learn how to support his healing.",
    connectionHoping: "To understand the spiritual side of physical intimacy",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Healer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "touch-and-affection", "couples-closeness"],
    joinedAt: new Date("2026-04-22"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-22"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-david-l",
    displayName: "David",
    pronouns: "he/him",
    location: "Boston, MA",
    ageRange: "45-50",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/david-l.svg",
    memberType: "individual",
    profile_tagline: "What does real masculinity look like?",
    interests: ["masculinity", "vulnerability", "community", "spirituality"],
    whatBroughtYouHere:
      "Spent 30 years hiding my feelings. Now I want to know what it means to be a whole man.",
    connectionHoping: "Other men exploring authentic masculinity",
    pairingComfortLevel: "Learning",
    quizResult: "The Awakening",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "masculinity-sexuality", "embodiment"],
    joinedAt: new Date("2026-05-01"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-01"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-ryan-p",
    displayName: "Ryan",
    pronouns: "he/him",
    location: "Chicago, IL",
    ageRange: "29-32",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/ryan-p.svg",
    memberType: "individual",
    profile_tagline: "Finding joy in connection",
    interests: ["dating", "community", "spirituality", "fun"],
    whatBroughtYouHere:
      "Dating feels superficial. I want to meet men who are looking for something real.",
    connectionHoping: "Authentic relationships where we can be ourselves",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Romantic",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "intimacy-patterns"],
    joinedAt: new Date("2026-04-30"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-30"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-sammy-c",
    displayName: "Sammy",
    pronouns: "he/him",
    location: "New York, NY",
    ageRange: "26-28",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/sammy-c.svg",
    memberType: "individual",
    profile_tagline: "Consent and communication matter",
    interests: ["sexuality", "communication", "community", "embodiment"],
    whatBroughtYouHere:
      "I want to be a more conscious lover. This seemed like the right place to start.",
    connectionHoping: "To understand sexuality as spiritual and relational",
    pairingComfortLevel: "Very comfortable",
    quizResult: "The Conscious",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "spirituality-sexuality"],
    joinedAt: new Date("2026-05-05"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-05"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-noah-g",
    displayName: "Noah",
    pronouns: "he/him",
    location: "Miami, FL",
    ageRange: "33-36",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/noah-g.svg",
    memberType: "individual",
    profile_tagline: "Rekindling desire with my husband",
    interests: ["couples work", "intimacy", "spirituality", "sexuality"],
    whatBroughtYouHere:
      "After 5 years together, our sex life had become predictable. We wanted to reignite things.",
    connectionHoping: "Practical advice from couples who've navigated this",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Harmonizer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "couples-closeness", "dating-desire"],
    joinedAt: new Date("2026-04-18"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-18"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-ethan-b",
    displayName: "Ethan",
    pronouns: "he/him",
    location: "San Diego, CA",
    ageRange: "30-33",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/ethan-b.svg",
    memberType: "individual",
    profile_tagline: "Healing my relationship with my body",
    interests: ["embodiment", "spirituality", "community", "intimacy"],
    whatBroughtYouHere:
      "I grew up thinking my body was shameful. I'm learning to love and honor it.",
    connectionHoping: "To feel safe exploring my sexuality and body",
    pairingComfortLevel: "Somewhat comfortable",
    quizResult: "The Transformer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "embodiment", "touch-and-affection"],
    joinedAt: new Date("2026-05-08"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-08"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-liam-s",
    displayName: "Liam",
    pronouns: "he/him",
    location: "Phoenix, AZ",
    ageRange: "40-43",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/liam-s.svg",
    memberType: "individual",
    profile_tagline: "Learning to ask for what I need",
    interests: ["communication", "spirituality", "masculinity", "intimacy"],
    whatBroughtYouHere:
      "I realized I've spent my whole life not asking for anything. Time to change that.",
    connectionHoping: "Men who are willing to have difficult conversations",
    pairingComfortLevel: "Learning",
    quizResult: "The Awakening",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "masculinity-sexuality", "touch-and-affection"],
    joinedAt: new Date("2026-04-25"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-25"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-mason-h",
    displayName: "Mason",
    pronouns: "he/him",
    location: "Washington, DC",
    ageRange: "35-38",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/mason-h.svg",
    memberType: "individual",
    profile_tagline: "Blending spirituality with sexuality",
    interests: ["spirituality", "sexuality", "couples work", "embodiment"],
    whatBroughtYouHere:
      "My partner and I practice tantra. We wanted to meet others exploring sacred sexuality.",
    connectionHoping: "A community that honors sex as spiritual practice",
    pairingComfortLevel: "Very comfortable",
    quizResult: "The Mystic",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "spirituality-sexuality", "couples-closeness"],
    joinedAt: new Date("2026-04-12"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-12"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-lucas-j",
    displayName: "Lucas",
    pronouns: "he/him",
    location: "Nashville, TN",
    ageRange: "27-29",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/lucas-j.svg",
    memberType: "individual",
    profile_tagline: "Finding my queerness beyond sex",
    interests: ["identity", "community", "spirituality", "embodiment"],
    whatBroughtYouHere:
      "Growing up, gay only meant sex. I wanted to explore what being gay could really mean.",
    connectionHoping: "Men exploring the fullness of queer identity",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Seeker",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "spirituality-sexuality"],
    joinedAt: new Date("2026-05-03"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-03"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-oliver-f",
    displayName: "Oliver",
    pronouns: "he/him",
    location: "Portland, ME",
    ageRange: "44-47",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/oliver-f.svg",
    memberType: "individual",
    profile_tagline: "What now? Life after 40",
    interests: ["meaning", "spirituality", "masculinity", "community"],
    whatBroughtYouHere:
      "Questioning what life is about at this stage. Ready for depth I couldn't access before.",
    connectionHoping: "Men asking the big questions about meaning and purpose",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Philosopher",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "spirituality-sexuality", "masculinity-sexuality"],
    joinedAt: new Date("2026-04-20"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-20"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-aiden-n",
    displayName: "Aiden",
    pronouns: "he/him",
    location: "Salt Lake City, UT",
    ageRange: "32-35",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/aiden-n.svg",
    memberType: "individual",
    profile_tagline: "Navigating religion and sexuality",
    interests: ["spirituality", "faith", "couples work", "community"],
    whatBroughtYouHere:
      "Coming from a conservative background, integrating my faith with my sexuality has been hard.",
    connectionHoping: "Other men bridging faith and sexuality authentically",
    pairingComfortLevel: "Learning",
    quizResult: "The Bridge Builder",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "spirituality-sexuality", "couples-closeness"],
    joinedAt: new Date("2026-05-07"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-07"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-isaac-b",
    displayName: "Isaac",
    pronouns: "he/him",
    location: "Philadelphia, PA",
    ageRange: "28-31",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/isaac-b.svg",
    memberType: "individual",
    profile_tagline: "Pleasure without shame",
    interests: ["sexuality", "embodiment", "spirituality", "community"],
    whatBroughtYouHere:
      "I want to experience pleasure in my body without the guilt and shame from growing up.",
    connectionHoping: "Men deconditioning from sex-shame together",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Liberator",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "embodiment", "dating-desire"],
    joinedAt: new Date("2026-04-29"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-29"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-michael-p",
    displayName: "Michael",
    pronouns: "he/him",
    location: "Atlanta, GA",
    ageRange: "36-39",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/michael-p.svg",
    memberType: "individual",
    profile_tagline: "Building better communication",
    interests: ["communication", "couples work", "intimacy", "community"],
    whatBroughtYouHere:
      "My partner and I were drifting. We wanted tools and community to rebuild connection.",
    connectionHoping: "Practical skills for relationship health",
    pairingComfortLevel: "Somewhat comfortable",
    quizResult: "The Harmonizer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "couples-closeness", "touch-and-affection"],
    joinedAt: new Date("2026-05-04"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-04"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-william-r",
    displayName: "William",
    pronouns: "he/him",
    location: "Houston, TX",
    ageRange: "41-44",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/william-r.svg",
    memberType: "individual",
    profile_tagline: "Reclaiming desire at midlife",
    interests: ["sexuality", "intimacy", "embodiment", "community"],
    whatBroughtYouHere:
      "My sexuality felt dead. I wanted to reconnect with that part of myself.",
    connectionHoping: "Men bringing desire back to life with consciousness",
    pairingComfortLevel: "Learning",
    quizResult: "The Awakening",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "embodiment"],
    joinedAt: new Date("2026-04-24"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-24"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-benjamin-m",
    displayName: "Benjamin",
    pronouns: "he/him",
    location: "Dallas, TX",
    ageRange: "25-27",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/benjamin-m.svg",
    memberType: "individual",
    profile_tagline: "Learning what healthy looks like",
    interests: ["relationships", "community", "embodiment", "spirituality"],
    whatBroughtYouHere:
      "My parents had a toxic relationship. I want to learn what healthy love looks like.",
    connectionHoping: "Modeling and learning healthy relationship patterns",
    pairingComfortLevel: "New to this",
    quizResult: "The Seeker",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "intimacy-patterns"],
    joinedAt: new Date("2026-05-09"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-09"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-jacob-d",
    displayName: "Jacob",
    pronouns: "he/him",
    location: "San Antonio, TX",
    ageRange: "38-41",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/jacob-d.svg",
    memberType: "individual",
    profile_tagline: "Grief and growth in the same breath",
    interests: ["spirituality", "community", "vulnerability", "embodiment"],
    whatBroughtYouHere:
      "Lost my partner to AIDS in the 90s. Finally ready to engage with intimacy again.",
    connectionHoping: "Safe space to grieve and learn to love again",
    pairingComfortLevel: "Very careful",
    quizResult: "The Healer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "touch-and-affection", "spirituality-sexuality"],
    joinedAt: new Date("2026-04-17"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-17"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-henry-c",
    displayName: "Henry",
    pronouns: "he/him",
    location: "Austin, TX",
    ageRange: "29-32",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/henry-c.svg",
    memberType: "individual",
    profile_tagline: "Healing from a bad breakup",
    interests: ["community", "spirituality", "embodiment", "intimacy"],
    whatBroughtYouHere:
      "A 7-year relationship ended badly. I need to figure out what I want next.",
    connectionHoping: "To rebuild trust in love and connection",
    pairingComfortLevel: "Wounded but hopeful",
    quizResult: "The Transformer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "spirituality-sexuality"],
    joinedAt: new Date("2026-05-06"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-06"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-tyler-w",
    displayName: "Tyler",
    pronouns: "he/him",
    location: "Fort Worth, TX",
    ageRange: "43-46",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/tyler-w.svg",
    memberType: "individual",
    profile_tagline: "Learning to receive love",
    interests: ["intimacy", "couples work", "spirituality", "embodiment"],
    whatBroughtYouHere:
      "I'm good at giving but terrible at receiving. Wanted to learn to let my partner in.",
    connectionHoping: "Understanding vulnerability as strength, not weakness",
    pairingComfortLevel: "Somewhat comfortable",
    quizResult: "The Nurturer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "couples-closeness", "touch-and-affection"],
    joinedAt: new Date("2026-04-19"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-19"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-gabriel-h",
    displayName: "Gabriel",
    pronouns: "he/him",
    location: "Las Vegas, NV",
    ageRange: "30-33",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/gabriel-h.svg",
    memberType: "individual",
    profile_tagline: "Intimacy beyond the club",
    interests: ["connection", "spirituality", "embodiment", "community"],
    whatBroughtYouHere:
      "The gay scene felt empty. I wanted to meet men looking for actual connection.",
    connectionHoping: "Depth beyond apps and bars",
    pairingComfortLevel: "Comfortable",
    quizResult: "The Seeker",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "touch-and-affection", "dating-desire"],
    joinedAt: new Date("2026-05-02"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-02"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
];
