import { Profile } from "@/lib/data/profiles";

// Helper to extract first and last name from display name
function getNameParts(displayName: string) {
  const parts = displayName.trim().split(/\s+/);
  return {
    firstName: parts[0] || "Member",
    lastName: parts.slice(1).join(" ") || "",
  };
}

export const demoMembers: Profile[] = [
  {
    id: "demo-marcus-h",
    firstName: "Marcus",
    lastName: "Harrison",
    displayName: "Marcus",
    pronouns: "he/him",
    location: "Los Angeles, CA",
    ageRange: "35-44",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-01.png",
    memberType: "individual",
    profile_tagline: "Learning to be vulnerable",
    interests: ["intimacy", "spirituality", "embodiment", "community"],
    whatBroughtYouHere:
      "Spent a decade chasing achievement—the house, the status, the 'right' partner. But I kept waking up empty. This year I had a therapy breakthrough: I don't know how to actually let people see me. I'm here to learn that, maybe for the first time.",
    connectionHoping: "Men who are doing their own inner work and aren't afraid to bring their whole selves to the table",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Nurturer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "touch-affection", "intimacy-patterns"],
    joinedAt: new Date("2026-04-15"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-15"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-daniel-r",
    firstName: "Daniel",
    lastName: "Rivera",
    displayName: "Daniel",
    pronouns: "he/him",
    location: "San Francisco, CA",
    ageRange: "28-34",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-02.png",
    memberType: "individual",
    profile_tagline: "Exploring desire with intention",
    interests: ["sexuality", "couples work", "embodiment", "dating"],
    whatBroughtYouHere:
      "My partner and I opened up about some fantasies we'd been sitting with for years. It scared us both—not the desires themselves, but the vulnerability required to share them. We wanted a space where that felt safe, where sexuality isn't just transaction but sacred conversation.",
    connectionHoping: "Real couples who understand that desire grows through honesty, not hiding",
    connectionComfortLevel: "Somewhat comfortable",
    quizResult: "The Explorer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "couples"],
    joinedAt: new Date("2026-05-02"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-02"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-james-t",
    firstName: "James",
    lastName: "Torres",
    displayName: "James",
    pronouns: "he/him",
    location: "Portland, OR",
    ageRange: "42-50",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-03.png",
    memberType: "individual",
    profile_tagline: "Looking for depth in my 40s",
    interests: ["spirituality", "masculinity", "community", "intimacy"],
    whatBroughtYouHere:
      "I felt alone even in a city full of gay men. For years I thought I was past the point of real connection—figured I'd missed my window. Then I realized I was just looking in the wrong places. This community feels different. People are actually asking *who am I?* instead of just *what do you do?*",
    connectionHoping: "Real friendships with men brave enough to question themselves",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Philosopher",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "spirituality-sexuality", "masculinity-sex-sexuality", "sacred-sexuality", "workshops"],
    joinedAt: new Date("2026-04-28"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-28"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-alex-m",
    firstName: "Alex",
    lastName: "Martinez",
    displayName: "Alex",
    pronouns: "he/him",
    location: "Austin, TX",
    ageRange: "25-27",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-04.png",
    memberType: "individual",
    profile_tagline: "Just starting to understand myself",
    interests: ["embodiment", "dating", "community", "connection"],
    whatBroughtYouHere:
      "I came out at 22. Everyone assumed that was the hard part. But honestly, I still don't know who I am as a sexual or intimate being—I just know what I'm *not*. Dating apps gave me options but left me confused. I wanted actual conversation about desire, not just photos and hookups.",
    connectionHoping: "To explore what I actually want without judgment, and find people on the same journey",
    connectionComfortLevel: "New to this",
    quizResult: "The Seeker",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "embodiment"],
    joinedAt: new Date("2026-05-10"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-10"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-chris-w",
    firstName: "Chris",
    lastName: "Williams",
    displayName: "Chris",
    pronouns: "he/him",
    location: "Seattle, WA",
    ageRange: "38-41",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-05.png",
    memberType: "individual",
    profile_tagline: "Opening up my relationship",
    interests: ["couples work", "communication", "spirituality", "intimacy"],
    whatBroughtYouHere:
      "My partner and I opened up our relationship last year. It was necessary—we both needed more than what we could give each other. But we were fumbling through it, creating rules and restrictions instead of understanding what we were actually looking for. We needed help from people who've done this well.",
    connectionHoping: "Couples who've learned to expand love without losing connection",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Bridge Builder",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "couples", "spirituality-sexuality", "workshops"],
    joinedAt: new Date("2026-04-05"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-05"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-jordan-k",
    firstName: "Jordan",
    lastName: "Kinney",
    displayName: "Jordan",
    pronouns: "he/him",
    location: "Denver, CO",
    ageRange: "31-34",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-06.png",
    memberType: "individual",
    profile_tagline: "Healing touch and closeness",
    interests: ["touch", "intimacy", "embodiment", "spirituality"],
    whatBroughtYouHere:
      "My partner grew up in a house where touch was either absent or violent. He's spent years rebuilding his relationship with his body. I wanted to understand how to support his healing and learn what touch can really mean beyond sex—tenderness as language, skin as conversation.",
    connectionHoping: "To understand the spiritual side of physical intimacy and what safe touch actually creates",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Healer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "touch-affection", "couples"],
    joinedAt: new Date("2026-04-22"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-22"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-david-l",
    firstName: "David",
    lastName: "Lincoln",
    displayName: "David",
    pronouns: "he/him",
    location: "Boston, MA",
    ageRange: "45-50",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-07.png",
    memberType: "individual",
    profile_tagline: "What does real masculinity look like?",
    interests: ["masculinity", "vulnerability", "community", "spirituality"],
    whatBroughtYouHere:
      "I spent 30 years hiding my feelings, thinking that was what being a man meant. My therapist finally said, 'What if the strongest thing you could do is actually feel?' That broke something open in me. Now I'm terrified and curious—what's real masculinity if not this armor I've been wearing?",
    connectionHoping: "Other men asking the same hard questions and willing to find new answers together",
    connectionComfortLevel: "Learning",
    quizResult: "The Awakening",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "masculinity-sex-sexuality", "embodiment"],
    joinedAt: new Date("2026-05-01"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-01"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-ryan-p",
    firstName: "Ryan",
    lastName: "Patterson",
    displayName: "Ryan",
    pronouns: "he/him",
    location: "Chicago, IL",
    ageRange: "29-32",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-08.png",
    memberType: "individual",
    profile_tagline: "Finding joy in connection",
    interests: ["dating", "community", "spirituality", "fun"],
    whatBroughtYouHere:
      "I grew up thinking gay relationships were impossible. I've dated, hooked up, had the apps. But somewhere along the way it all started to feel empty—like I was performing a version of gay life instead of living it. I want to remember why connection excited me in the first place.",
    connectionHoping: "Authentic relationships where both people can actually be themselves, not curated versions",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Romantic",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "intimacy-patterns"],
    joinedAt: new Date("2026-04-30"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-30"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-sammy-c",
    firstName: "Sammy",
    lastName: "Chen",
    displayName: "Sammy",
    pronouns: "he/him",
    location: "New York, NY",
    ageRange: "26-28",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-09.png",
    memberType: "individual",
    profile_tagline: "Consent and communication matter",
    interests: ["sexuality", "communication", "community", "embodiment"],
    whatBroughtYouHere:
      "I watched friends suffer through relationships built on assumptions instead of actual conversation. I wanted to be different—more conscious, more intentional. That means understanding not just what I want, but why I want it, and being able to actually *say* that to another person.",
    connectionHoping: "To understand sexuality as something spiritual and relational, not just physical",
    connectionComfortLevel: "Very comfortable",
    quizResult: "The Conscious",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "spirituality-sexuality"],
    joinedAt: new Date("2026-05-05"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-05"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-noah-g",
    firstName: "Noah",
    lastName: "",
    displayName: "Noah",
    pronouns: "he/him",
    location: "Miami, FL",
    ageRange: "33-36",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-10.png",
    memberType: "individual",
    profile_tagline: "Rekindling desire with my husband",
    interests: ["couples work", "intimacy", "spirituality", "sexuality"],
    whatBroughtYouHere:
      "After 5 years together, we fell into routine. Sex became scheduled, predictable, something we did because we 'should.' We still love each other, but the aliveness went somewhere. We wanted to remember why we chose each other in the first place—to reignite not just sex but the *desire* behind it.",
    connectionHoping: "Practical wisdom from couples who've navigated the long game and kept romance alive",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Harmonizer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "couples", "dating-desire"],
    joinedAt: new Date("2026-04-18"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-18"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-ethan-b",
    firstName: "Ethan",
    lastName: "",
    displayName: "Ethan",
    pronouns: "he/him",
    location: "San Diego, CA",
    ageRange: "30-33",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-11.png",
    memberType: "individual",
    profile_tagline: "Healing my relationship with my body",
    interests: ["embodiment", "spirituality", "community", "intimacy"],
    whatBroughtYouHere:
      "Catholic school taught me my body was shameful. It took years of therapy to even touch myself without guilt. But I'm still working through the messages—the idea that pleasure is something to earn rather than something I deserve. I wanted a community where that healing feels possible.",
    connectionHoping: "To feel safe exploring sexuality without the old scripts playing in my head",
    connectionComfortLevel: "Somewhat comfortable",
    quizResult: "The Transformer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "embodiment", "touch-affection"],
    joinedAt: new Date("2026-05-08"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-08"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-liam-s",
    firstName: "Liam",
    lastName: "",
    displayName: "Liam",
    pronouns: "he/him",
    location: "Phoenix, AZ",
    ageRange: "40-43",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-12.png",
    memberType: "individual",
    profile_tagline: "Learning to ask for what I need",
    interests: ["communication", "spirituality", "masculinity", "intimacy"],
    whatBroughtYouHere:
      "I realized I've spent my whole life being accommodating, not asking for anything, thinking that made me 'easy' or 'good.' But it left me empty and resentful. Now I'm learning that vulnerability includes wanting things, needing things, asking for things. It's harder than I thought.",
    connectionHoping: "Men willing to have difficult conversations and honor their own needs",
    connectionComfortLevel: "Learning",
    quizResult: "The Awakening",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "masculinity-sex-sexuality", "touch-affection"],
    joinedAt: new Date("2026-04-25"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-25"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-mason-h",
    firstName: "Mason",
    lastName: "",
    displayName: "Mason",
    pronouns: "he/him",
    location: "Washington, DC",
    ageRange: "35-38",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-13.png",
    memberType: "individual",
    profile_tagline: "Blending spirituality with sexuality",
    interests: ["spirituality", "sexuality", "couples work", "embodiment"],
    whatBroughtYouHere:
      "My partner and I practice tantra. For us, sex is a spiritual practice—it's meditation, it's prayer. But we felt isolated in that perspective. The gay community often treats sexuality one way, and spiritual communities treat it another. We wanted to find others who understood that integration.",
    connectionHoping: "A community that honors sex as spiritual practice, not something to hide or apologize for",
    connectionComfortLevel: "Very comfortable",
    quizResult: "The Mystic",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "spirituality-sexuality", "couples", "sacred-sexuality", "workshops"],
    joinedAt: new Date("2026-04-12"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-12"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-lucas-j",
    firstName: "Lucas",
    lastName: "",
    displayName: "Lucas",
    pronouns: "he/him",
    location: "Nashville, TN",
    ageRange: "27-29",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-14.png",
    memberType: "individual",
    profile_tagline: "Finding my queerness beyond sex",
    interests: ["identity", "community", "spirituality", "embodiment"],
    whatBroughtYouHere:
      "Growing up, the only gay thing I could access was sex—it's all media showed, all friends talked about. Coming out was sexual. But I wanted to know: who am I as a queer person beyond that? What does queerness mean spiritually, relationally, as a way of being in the world?",
    connectionHoping: "Men exploring the fullness of queer identity, not just sexual identity",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Seeker",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "spirituality-sexuality", "sacred-sexuality"],
    joinedAt: new Date("2026-05-03"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-03"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-oliver-f",
    firstName: "Oliver",
    lastName: "",
    displayName: "Oliver",
    pronouns: "he/him",
    location: "Portland, ME",
    ageRange: "44-47",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-15.png",
    memberType: "individual",
    profile_tagline: "What now? Life after 40",
    interests: ["meaning", "spirituality", "masculinity", "community"],
    whatBroughtYouHere:
      "I had the career, the apartment, the lovers. Then I turned 45 and realized none of it was answering the questions that actually matter. I wanted to meet men in the second half of their lives asking the same thing: what's actually important? What does a good life actually look like?",
    connectionHoping: "Men asking big questions about meaning and purpose in midlife and beyond",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Philosopher",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "spirituality-sexuality", "masculinity-sex-sexuality", "sacred-sexuality", "workshops"],
    joinedAt: new Date("2026-04-20"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-20"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-aiden-n",
    firstName: "Aiden",
    lastName: "",
    displayName: "Aiden",
    pronouns: "he/him",
    location: "Salt Lake City, UT",
    ageRange: "32-35",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-16.png",
    memberType: "individual",
    profile_tagline: "Navigating religion and sexuality",
    interests: ["spirituality", "faith", "couples work", "community"],
    whatBroughtYouHere:
      "I grew up in a conservative faith tradition. Being gay felt like a betrayal. But I couldn't deny it, and I couldn't deny my faith either. My partner and I spent years keeping those parts separate. Now we're trying to integrate them—to find a spirituality that actually honors both who we are and what we believe.",
    connectionHoping: "Other men bridging faith and sexuality authentically, without having to choose",
    connectionComfortLevel: "Learning",
    quizResult: "The Bridge Builder",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "spirituality-sexuality", "couples"],
    joinedAt: new Date("2026-05-07"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-07"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-isaac-b",
    firstName: "Isaac",
    lastName: "",
    displayName: "Isaac",
    pronouns: "he/him",
    location: "Philadelphia, PA",
    ageRange: "28-31",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-17.png",
    memberType: "individual",
    profile_tagline: "Pleasure without shame",
    interests: ["sexuality", "embodiment", "spirituality", "community"],
    whatBroughtYouHere:
      "I want to experience pleasure in my body without the voice in my head saying I'm dirty or wrong. Growing up I learned that my sexuality was something to be ashamed of—and intellectually I know that's not true, but my body hasn't caught up yet. I wanted to be around people deconditioning from the same messages.",
    connectionHoping: "Men working together to reclaim pleasure as a birthright, not something to earn or hide",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Liberator",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "embodiment", "dating-desire"],
    joinedAt: new Date("2026-04-29"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-29"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-michael-p",
    firstName: "Michael",
    lastName: "",
    displayName: "Michael",
    pronouns: "he/him",
    location: "Atlanta, GA",
    ageRange: "36-39",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-18.png",
    memberType: "individual",
    profile_tagline: "Building better communication",
    interests: ["communication", "couples work", "intimacy", "community"],
    whatBroughtYouHere:
      "My partner and I were drifting. We'd have the same fights over and over. We still love each other but we lost the skills to actually *talk*. We needed to learn how to have the hard conversations—to understand each other instead of defend ourselves.",
    connectionHoping: "Practical skills and wisdom from couples who've learned to communicate through conflict",
    connectionComfortLevel: "Somewhat comfortable",
    quizResult: "The Harmonizer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "couples", "touch-affection"],
    joinedAt: new Date("2026-05-04"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-04"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-william-r",
    firstName: "William",
    lastName: "",
    displayName: "William",
    pronouns: "he/him",
    location: "Houston, TX",
    ageRange: "41-44",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-19.png",
    memberType: "individual",
    profile_tagline: "Reclaiming desire at midlife",
    interests: ["sexuality", "intimacy", "embodiment", "community"],
    whatBroughtYouHere:
      "My sexuality felt like it died somewhere in my 30s. I thought it was just what happens—you get older, desire goes away. But a friend suggested maybe it was something else: maybe I'd learned to numb myself, maybe desire was still there but buried. I wanted to dig it back up and feel alive again.",
    connectionHoping: "Men bringing consciousness and intention back to desire at any age",
    connectionComfortLevel: "Learning",
    quizResult: "The Awakening",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "embodiment"],
    joinedAt: new Date("2026-04-24"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-24"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-benjamin-m",
    firstName: "Benjamin",
    lastName: "",
    displayName: "Benjamin",
    pronouns: "he/him",
    location: "Dallas, TX",
    ageRange: "25-27",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-20.png",
    memberType: "individual",
    profile_tagline: "Learning what healthy looks like",
    interests: ["relationships", "community", "embodiment", "spirituality"],
    whatBroughtYouHere:
      "My parents had a toxic relationship—a lot of drama, manipulation, infidelity. I swore I'd do it differently but I don't actually know what different looks like. I watch healthy couples and I'm like 'how?' There's no script for this. I wanted to be around people modeling what actual health feels like.",
    connectionHoping: "Modeling and learning what healthy relationships actually look like in practice",
    connectionComfortLevel: "New to this",
    quizResult: "The Seeker",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "intimacy-patterns"],
    joinedAt: new Date("2026-05-09"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-09"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-jacob-d",
    firstName: "Jacob",
    lastName: "",
    displayName: "Jacob",
    pronouns: "he/him",
    location: "San Antonio, TX",
    ageRange: "38-41",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-21.png",
    memberType: "individual",
    profile_tagline: "Grief and growth in the same breath",
    interests: ["spirituality", "community", "vulnerability", "embodiment"],
    whatBroughtYouHere:
      "I lost my partner to AIDS in 1994. For 30 years I've kept myself closed off—it felt safer than risking that pain again. But I'm tired of living small. I realized I'd rather have 10 beautiful years with someone than 40 years of nothing. I'm here to learn how to open up again.",
    connectionHoping: "Safe space to grieve what was lost and learn to love again without rushing",
    connectionComfortLevel: "Very careful",
    quizResult: "The Healer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "touch-affection", "spirituality-sexuality"],
    joinedAt: new Date("2026-04-17"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-17"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-henry-c",
    firstName: "Henry",
    lastName: "",
    displayName: "Henry",
    pronouns: "he/him",
    location: "Austin, TX",
    ageRange: "29-32",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-22.png",
    memberType: "individual",
    profile_tagline: "Healing from a bad breakup",
    interests: ["community", "spirituality", "embodiment", "intimacy"],
    whatBroughtYouHere:
      "A 7-year relationship ended badly. For the first time I'm asking: was it *him*, or was I just not capable of showing up? I don't want to repeat this. I want to understand myself—what patterns I bring, where I check out, how I protect myself in ways that end relationships.",
    connectionHoping: "To rebuild trust in love and learn from my own patterns",
    connectionComfortLevel: "Wounded but hopeful",
    quizResult: "The Transformer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "dating-desire", "spirituality-sexuality"],
    joinedAt: new Date("2026-05-06"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-06"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-tyler-w",
    firstName: "Tyler",
    lastName: "",
    displayName: "Tyler",
    pronouns: "he/him",
    location: "Fort Worth, TX",
    ageRange: "43-46",
    relationshipStatus: "In a relationship",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-23.png",
    memberType: "individual",
    profile_tagline: "Learning to receive love",
    interests: ["intimacy", "couples work", "spirituality", "embodiment"],
    whatBroughtYouHere:
      "I'm good at giving but terrible at receiving. My partner gives and gives, and I find ways to prove I don't need it—I deflect with jokes, I stay busy. Somehow I've learned that needing people is weakness. But my partner is exhausted from one-sided giving. We wanted help unlearning that.",
    connectionHoping: "Understanding vulnerability as strength, not weakness, and practicing receiving love",
    connectionComfortLevel: "Somewhat comfortable",
    quizResult: "The Nurturer",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "couples", "touch-affection"],
    joinedAt: new Date("2026-04-19"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-04-19"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
  {
    id: "demo-gabriel-h",
    firstName: "Gabriel",
    lastName: "",
    displayName: "Gabriel",
    pronouns: "he/him",
    location: "Las Vegas, NV",
    ageRange: "30-33",
    relationshipStatus: "Single",
    orientation: "Gay",
    profilePhoto: "/demo-members/seed-man-24.png",
    memberType: "individual",
    profile_tagline: "Intimacy beyond the club",
    interests: ["connection", "spirituality", "embodiment", "community"],
    whatBroughtYouHere:
      "I grew up here. The gay scene is clubs and apps and hookups. That's the menu. But I wanted something different—actual conversation, actual vulnerability. I felt like I was the only person asking for that until I found this space. Turns out a lot of men are hungry for the same thing.",
    connectionHoping: "Real depth and connection beyond the surface-level interactions apps and bars offer",
    connectionComfortLevel: "Comfortable",
    quizResult: "The Seeker",
    completedOnboarding: true,
    spacesJoined: ["commons", "start-here", "touch-affection", "dating-desire"],
    joinedAt: new Date("2026-05-02"),
    photo_confirmed: true,
    photo_confirmed_at: new Date("2026-05-02"),
    show_in_member_lists: true,
    profile_visibility: "space_members",
    show_general_location: true,
    show_recent_posts: true,
    is_demo_profile: true,
  },
];
