-- Seed 24 demo members into profiles table
-- All marked as is_seeded = TRUE so they can be cleaned up after launch

-- Make user_id nullable so demo profiles don't require auth users
ALTER TABLE profiles ALTER COLUMN user_id DROP NOT NULL;

INSERT INTO profiles (
  id, user_id, display_name, pronouns, location, age_range,
  relationship_status, orientation, profile_photo, member_type,
  interests, what_brought_you_here, connection_hoping,
  pairing_comfort_level, quiz_result, completed_onboarding,
  spaces_joined, created_at, role, is_seeded
) VALUES
('e7b2200d-72fd-5287-a323-495f920feb11', NULL, 'Marcus', 'he/him', 'Los Angeles, CA', '35-44', 'Single', 'Gay', '/demo-members/seed-man-01.png', 'individual', '["intimacy","spirituality","embodiment","community"]'::jsonb, 'Spent a decade chasing achievement—the house, the status, the ''right'' partner. But I kept waking up empty. This year I had a therapy breakthrough: I don''t know how to actually let people see me. I''m here to learn that, maybe for the first time.', 'Men who are doing their own inner work and aren''t afraid to bring their whole selves to the table', 'Comfortable', 'The Nurturer', true, '["commons","start-here","touch-affection","intimacy-patterns"]'::jsonb, '2026-04-15'::date, 'member', true),
('c379b143-22c1-5f5e-be42-9c87643d7ce7', NULL, 'Daniel', 'he/him', 'San Francisco, CA', '28-34', 'In a relationship', 'Gay', '/demo-members/seed-man-02.png', 'individual', '["sexuality","couples work","embodiment","dating"]'::jsonb, 'My partner and I opened up about some fantasies we''d been sitting with for years. It scared us both—not the desires themselves, but the vulnerability required to share them. We wanted a space where that felt safe, where sexuality isn''t just transaction but sacred conversation.', 'Real couples who understand that desire grows through honesty, not hiding', 'Somewhat comfortable', 'The Explorer', true, '["commons","start-here","dating-desire","couples"]'::jsonb, '2026-05-02'::date, 'member', true),
('1b5b8159-311f-5a1d-bce2-779e916fb2ae', NULL, 'James', 'he/him', 'Portland, OR', '42-50', 'Single', 'Gay', '/demo-members/seed-man-03.png', 'individual', '["spirituality","masculinity","community","intimacy"]'::jsonb, 'I felt alone even in a city full of gay men. For years I thought I was past the point of real connection—figured I''d missed my window. Then I realized I was just looking in the wrong places. This community feels different. People are actually asking *who am I?* instead of just *what do you do?*', 'Real friendships with men brave enough to question themselves', 'Comfortable', 'The Philosopher', true, '["commons","start-here","spirituality-sexuality","masculinity-sex-sexuality","sacred-sexuality","workshops"]'::jsonb, '2026-04-28'::date, 'member', true),
('e95c38a7-e68d-5be5-a424-ccb8dceb8407', NULL, 'Alex', 'he/him', 'Austin, TX', '25-27', 'Single', 'Gay', '/demo-members/seed-man-04.png', 'individual', '["embodiment","dating","community","connection"]'::jsonb, 'I came out at 22. Everyone assumed that was the hard part. But honestly, I still don''t know who I am as a sexual or intimate being—I just know what I''m *not*. Dating apps gave me options but left me confused. I wanted actual conversation about desire, not just photos and hookups.', 'To explore what I actually want without judgment, and find people on the same journey', 'New to this', 'The Seeker', true, '["commons","start-here","dating-desire","embodiment"]'::jsonb, '2026-05-10'::date, 'member', true),
('ec9a5d9f-cdb7-54af-9b12-6e501a3799ea', NULL, 'Chris', 'he/him', 'Seattle, WA', '38-41', 'In a relationship', 'Gay', '/demo-members/seed-man-05.png', 'individual', '["couples work","communication","spirituality","intimacy"]'::jsonb, 'My partner and I opened up our relationship last year. It was necessary—we both needed more than what we could give each other. But we were fumbling through it, creating rules and restrictions instead of understanding what we were actually looking for. We needed help from people who''ve done this well.', 'Couples who''ve learned to expand love without losing connection', 'Comfortable', 'The Bridge Builder', true, '["commons","start-here","couples","spirituality-sexuality","workshops"]'::jsonb, '2026-04-05'::date, 'member', true),
('4dae961b-e913-5575-bc7f-0086846e09f4', NULL, 'Jordan', 'he/him', 'Denver, CO', '31-34', 'In a relationship', 'Gay', '/demo-members/seed-man-06.png', 'individual', '["touch","intimacy","embodiment","spirituality"]'::jsonb, 'My partner grew up in a house where touch was either absent or violent. He''s spent years rebuilding his relationship with his body. I wanted to understand how to support his healing and learn what touch can really mean beyond sex—tenderness as language, skin as conversation.', 'To understand the spiritual side of physical intimacy and what safe touch actually creates', 'Comfortable', 'The Healer', true, '["commons","start-here","touch-affection","couples"]'::jsonb, '2026-04-22'::date, 'member', true),
('ba0405b6-2c51-5543-ac54-7715a9131e11', NULL, 'David', 'he/him', 'Boston, MA', '45-50', 'Single', 'Gay', '/demo-members/seed-man-07.png', 'individual', '["masculinity","vulnerability","community","spirituality"]'::jsonb, 'I spent 30 years hiding my feelings, thinking that was what being a man meant. My therapist finally said, ''What if the strongest thing you could do is actually feel?'' That broke something open in me. Now I''m terrified and curious—what''s real masculinity if not this armor I''ve been wearing?', 'Other men asking the same hard questions and willing to find new answers together', 'Learning', 'The Awakening', true, '["commons","start-here","masculinity-sex-sexuality","embodiment"]'::jsonb, '2026-05-01'::date, 'member', true),
('95b3c9b4-17f7-58c6-8efb-c3ff5543daee', NULL, 'Ryan', 'he/him', 'Chicago, IL', '29-32', 'Single', 'Gay', '/demo-members/seed-man-08.png', 'individual', '["dating","community","spirituality","fun"]'::jsonb, 'I grew up thinking gay relationships were impossible. I''ve dated, hooked up, had the apps. But somewhere along the way it all started to feel empty—like I was performing a version of gay life instead of living it. I want to remember why connection excited me in the first place.', 'Authentic relationships where both people can actually be themselves, not curated versions', 'Comfortable', 'The Romantic', true, '["commons","start-here","dating-desire","intimacy-patterns"]'::jsonb, '2026-04-30'::date, 'member', true),
('c7a454c6-37f0-5463-ab48-56ddbc86ef5a', NULL, 'Sammy', 'he/him', 'New York, NY', '26-28', 'Single', 'Gay', '/demo-members/seed-man-09.png', 'individual', '["sexuality","communication","community","embodiment"]'::jsonb, 'I watched friends suffer through relationships built on assumptions instead of actual conversation. I wanted to be different—more conscious, more intentional. That means understanding not just what I want, but why I want it, and being able to actually *say* that to another person.', 'To understand sexuality as something spiritual and relational, not just physical', 'Very comfortable', 'The Conscious', true, '["commons","start-here","dating-desire","spirituality-sexuality"]'::jsonb, '2026-05-05'::date, 'member', true),
('05ed4220-bee4-5b29-b997-cacd87f35707', NULL, 'Noah', 'he/him', 'Miami, FL', '33-36', 'In a relationship', 'Gay', '/demo-members/seed-man-10.png', 'individual', '["couples work","intimacy","spirituality","sexuality"]'::jsonb, 'After 5 years together, we fell into routine. Sex became scheduled, predictable, something we did because we ''should.'' We still love each other, but the aliveness went somewhere. We wanted to remember why we chose each other in the first place—to reignite not just sex but the *desire* behind it.', 'Practical wisdom from couples who''ve navigated the long game and kept romance alive', 'Comfortable', 'The Harmonizer', true, '["commons","start-here","couples","dating-desire"]'::jsonb, '2026-04-18'::date, 'member', true),
('23cb1313-162b-5826-9417-0e4a6e6d8c4e', NULL, 'Ethan', 'he/him', 'San Diego, CA', '30-33', 'Single', 'Gay', '/demo-members/seed-man-11.png', 'individual', '["embodiment","spirituality","community","intimacy"]'::jsonb, 'Catholic school taught me my body was shameful. It took years of therapy to even touch myself without guilt. But I''m still working through the messages—the idea that pleasure is something to earn rather than something I deserve. I wanted a community where that healing feels possible.', 'To feel safe exploring sexuality without the old scripts playing in my head', 'Somewhat comfortable', 'The Transformer', true, '["commons","start-here","embodiment","touch-affection"]'::jsonb, '2026-05-08'::date, 'member', true),
('487d090f-29c1-54d1-a7e2-6eca52995a99', NULL, 'Liam', 'he/him', 'Phoenix, AZ', '40-43', 'Single', 'Gay', '/demo-members/seed-man-12.png', 'individual', '["communication","spirituality","masculinity","intimacy"]'::jsonb, 'I realized I''ve spent my whole life being accommodating, not asking for anything, thinking that made me ''easy'' or ''good.'' But it left me empty and resentful. Now I''m learning that vulnerability includes wanting things, needing things, asking for things. It''s harder than I thought.', 'Men willing to have difficult conversations and honor their own needs', 'Learning', 'The Awakening', true, '["commons","start-here","masculinity-sex-sexuality","touch-affection"]'::jsonb, '2026-04-25'::date, 'member', true),
('fa28c983-8e63-5b1c-8a9c-d64a2634c666', NULL, 'Mason', 'he/him', 'Washington, DC', '35-38', 'In a relationship', 'Gay', '/demo-members/seed-man-13.png', 'individual', '["spirituality","sexuality","couples work","embodiment"]'::jsonb, 'My partner and I practice tantra. For us, sex is a spiritual practice—it''s meditation, it''s prayer. But we felt isolated in that perspective. The gay community often treats sexuality one way, and spiritual communities treat it another. We wanted to find others who understood that integration.', 'A community that honors sex as spiritual practice, not something to hide or apologize for', 'Very comfortable', 'The Mystic', true, '["commons","start-here","spirituality-sexuality","couples","sacred-sexuality","workshops"]'::jsonb, '2026-04-12'::date, 'member', true),
('2f54beb7-85a5-53cd-937e-0bc0e7992ab3', NULL, 'Lucas', 'he/him', 'Nashville, TN', '27-29', 'Single', 'Gay', '/demo-members/seed-man-14.png', 'individual', '["identity","community","spirituality","embodiment"]'::jsonb, 'Growing up, the only gay thing I could access was sex—it''s all media showed, all friends talked about. Coming out was sexual. But I wanted to know: who am I as a queer person beyond that? What does queerness mean spiritually, relationally, as a way of being in the world?', 'Men exploring the fullness of queer identity, not just sexual identity', 'Comfortable', 'The Seeker', true, '["commons","start-here","dating-desire","spirituality-sexuality","sacred-sexuality"]'::jsonb, '2026-05-03'::date, 'member', true),
('44f967f2-9aab-50d7-9c68-e4cb35762597', NULL, 'Oliver', 'he/him', 'Portland, ME', '44-47', 'Single', 'Gay', '/demo-members/seed-man-15.png', 'individual', '["meaning","spirituality","masculinity","community"]'::jsonb, 'I had the career, the apartment, the lovers. Then I turned 45 and realized none of it was answering the questions that actually matter. I wanted to meet men in the second half of their lives asking the same thing: what''s actually important? What does a good life actually look like?', 'Men asking big questions about meaning and purpose in midlife and beyond', 'Comfortable', 'The Philosopher', true, '["commons","start-here","spirituality-sexuality","masculinity-sex-sexuality","sacred-sexuality","workshops"]'::jsonb, '2026-04-20'::date, 'member', true),
('8f962177-7d04-5bd1-bfa1-7bbac175c678', NULL, 'Aiden', 'he/him', 'Salt Lake City, UT', '32-35', 'In a relationship', 'Gay', '/demo-members/seed-man-16.png', 'individual', '["spirituality","faith","couples work","community"]'::jsonb, 'I grew up in a conservative faith tradition. Being gay felt like a betrayal. But I couldn''t deny it, and I couldn''t deny my faith either. My partner and I spent years keeping those parts separate. Now we''re trying to integrate them—to find a spirituality that actually honors both who we are and what we believe.', 'Other men bridging faith and sexuality authentically, without having to choose', 'Learning', 'The Bridge Builder', true, '["commons","start-here","spirituality-sexuality","couples"]'::jsonb, '2026-05-07'::date, 'member', true),
('c44cb01b-7ca4-5b38-a0bf-962d6b7055eb', NULL, 'Isaac', 'he/him', 'Philadelphia, PA', '28-31', 'Single', 'Gay', '/demo-members/seed-man-17.png', 'individual', '["sexuality","embodiment","spirituality","community"]'::jsonb, 'I want to experience pleasure in my body without the voice in my head saying I''m dirty or wrong. Growing up I learned that my sexuality was something to be ashamed of—and intellectually I know that''s not true, but my body hasn''t caught up yet. I wanted to be around people deconditioning from the same messages.', 'Men working together to reclaim pleasure as a birthright, not something to earn or hide', 'Comfortable', 'The Liberator', true, '["commons","start-here","embodiment","dating-desire"]'::jsonb, '2026-04-29'::date, 'member', true),
('e9cd008e-ae67-5513-9059-9c41c12d0e9a', NULL, 'Michael', 'he/him', 'Atlanta, GA', '36-39', 'In a relationship', 'Gay', '/demo-members/seed-man-18.png', 'individual', '["communication","couples work","intimacy","community"]'::jsonb, 'My partner and I were drifting. We''d have the same fights over and over. We still love each other but we lost the skills to actually *talk*. We needed to learn how to have the hard conversations—to understand each other instead of defend ourselves.', 'Practical skills and wisdom from couples who''ve learned to communicate through conflict', 'Somewhat comfortable', 'The Harmonizer', true, '["commons","start-here","couples","touch-affection"]'::jsonb, '2026-05-04'::date, 'member', true),
('77aa6831-5894-57dd-b1fd-22727cc31bfe', NULL, 'William', 'he/him', 'Houston, TX', '41-44', 'Single', 'Gay', '/demo-members/seed-man-19.png', 'individual', '["sexuality","intimacy","embodiment","community"]'::jsonb, 'My sexuality felt like it died somewhere in my 30s. I thought it was just what happens—you get older, desire goes away. But a friend suggested maybe it was something else: maybe I''d learned to numb myself, maybe desire was still there but buried. I wanted to dig it back up and feel alive again.', 'Men bringing consciousness and intention back to desire at any age', 'Learning', 'The Awakening', true, '["commons","start-here","dating-desire","embodiment"]'::jsonb, '2026-04-24'::date, 'member', true),
('6f35c3d0-218b-5157-9684-e3ab2bfe6203', NULL, 'Benjamin', 'he/him', 'Dallas, TX', '25-27', 'Single', 'Gay', '/demo-members/seed-man-20.png', 'individual', '["relationships","community","embodiment","spirituality"]'::jsonb, 'My parents had a toxic relationship—a lot of drama, manipulation, infidelity. I swore I''d do it differently but I don''t actually know what different looks like. I watch healthy couples and I''m like ''how?'' There''s no script for this. I wanted to be around people modeling what actual health feels like.', 'Modeling and learning what healthy relationships actually look like in practice', 'New to this', 'The Seeker', true, '["commons","start-here","dating-desire","intimacy-patterns"]'::jsonb, '2026-05-09'::date, 'member', true),
('1ade3b0a-2acb-546c-9e7d-df822b687287', NULL, 'Jacob', 'he/him', 'San Antonio, TX', '38-41', 'Single', 'Gay', '/demo-members/seed-man-21.png', 'individual', '["spirituality","community","vulnerability","embodiment"]'::jsonb, 'I lost my partner to AIDS in 1994. For 30 years I''ve kept myself closed off—it felt safer than risking that pain again. But I''m tired of living small. I realized I''d rather have 10 beautiful years with someone than 40 years of nothing. I''m here to learn how to open up again.', 'Safe space to grieve what was lost and learn to love again without rushing', 'Very careful', 'The Healer', true, '["commons","start-here","touch-affection","spirituality-sexuality"]'::jsonb, '2026-04-17'::date, 'member', true),
('6adfab21-7a94-5b0d-bad4-cf4eb597cfff', NULL, 'Henry', 'he/him', 'Austin, TX', '29-32', 'Single', 'Gay', '/demo-members/seed-man-22.png', 'individual', '["community","spirituality","embodiment","intimacy"]'::jsonb, 'A 7-year relationship ended badly. For the first time I''m asking: was it *him*, or was I just not capable of showing up? I don''t want to repeat this. I want to understand myself—what patterns I bring, where I check out, how I protect myself in ways that end relationships.', 'To rebuild trust in love and learn from my own patterns', 'Wounded but hopeful', 'The Transformer', true, '["commons","start-here","dating-desire","spirituality-sexuality"]'::jsonb, '2026-05-06'::date, 'member', true),
('81a0eec8-c23c-5f3e-9592-55680e913b9d', NULL, 'Tyler', 'he/him', 'Fort Worth, TX', '43-46', 'In a relationship', 'Gay', '/demo-members/seed-man-23.png', 'individual', '["intimacy","couples work","spirituality","embodiment"]'::jsonb, 'I''m good at giving but terrible at receiving. My partner gives and gives, and I find ways to prove I don''t need it—I deflect with jokes, I stay busy. Somehow I''ve learned that needing people is weakness. But my partner is exhausted from one-sided giving. We wanted help unlearning that.', 'Understanding vulnerability as strength, not weakness, and practicing receiving love', 'Somewhat comfortable', 'The Nurturer', true, '["commons","start-here","couples","touch-affection"]'::jsonb, '2026-04-19'::date, 'member', true),
('5cd99095-456b-591e-bd90-0b5cec6221ed', NULL, 'Gabriel', 'he/him', 'Las Vegas, NV', '30-33', 'Single', 'Gay', '/demo-members/seed-man-24.png', 'individual', '["connection","spirituality","embodiment","community"]'::jsonb, 'I grew up here. The gay scene is clubs and apps and hookups. That''s the menu. But I wanted something different—actual conversation, actual vulnerability. I felt like I was the only person asking for that until I found this space. Turns out a lot of men are hungry for the same thing.', 'Real depth and connection beyond the surface-level interactions apps and bars offer', 'Comfortable', 'The Seeker', true, '["commons","start-here","touch-affection","dating-desire"]'::jsonb, '2026-05-02'::date, 'member', true)
ON CONFLICT (id) DO NOTHING;

-- Verify the seeding worked
SELECT COUNT(*) as seeded_members_count FROM profiles WHERE is_seeded = TRUE;
