-- 073: Weekly "Question of the Week" auto-posting for every space.
--
-- Requested feature: post one prompt per week per space automatically,
-- pinned prominently at the top with room to comment (comments/reactions
-- already work on any post -- no new mechanism needed there).
--
-- space_weekly_prompts: the 16-week script per space, seeded below with
-- the drafted content. week_number is a real, meaningful sequence (not
-- decorative) -- it's literally "which week of the program."
--
-- space_prompt_schedule: one row per space tracking progress
-- independently, "elapsed >= 7 days" rather than a fixed weekday, so a
-- late/missed cron run still catches up correctly on its next run
-- (matches the same pattern already used by the drip-emails cron).
--
-- posts.pinned: a space has at most one pinned post at a time -- the
-- current week's prompt. Posting a new week's prompt unpins the previous
-- one (still visible in normal post history, just no longer pinned).
CREATE TABLE IF NOT EXISTS space_weekly_prompts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  space_id TEXT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  week_number INT NOT NULL CHECK (week_number BETWEEN 1 AND 16),
  prompt_text TEXT NOT NULL,
  UNIQUE (space_id, week_number)
);

CREATE TABLE IF NOT EXISTS space_prompt_schedule (
  space_id TEXT PRIMARY KEY REFERENCES spaces(id) ON DELETE CASCADE,
  next_week INT NOT NULL DEFAULT 1,
  last_posted_at TIMESTAMPTZ
);

ALTER TABLE posts ADD COLUMN IF NOT EXISTS pinned BOOLEAN NOT NULL DEFAULT false;
CREATE INDEX IF NOT EXISTS idx_posts_space_pinned ON posts (space_id, pinned);

-- Service-role only (matches sent_emails/drip_emails_sent/broadcast_drafts):
-- written and read exclusively by the weekly-prompts cron route and, if
-- ever needed, an admin-only API route -- never a direct client policy.
ALTER TABLE space_weekly_prompts ENABLE ROW LEVEL SECURITY;
ALTER TABLE space_prompt_schedule ENABLE ROW LEVEL SECURITY;

INSERT INTO space_weekly_prompts (space_id, week_number, prompt_text) VALUES
  ('start-here', 1, 'Introduce yourself: your name, where you''re from, and one word for how you''re feeling about being here.'),
  ('start-here', 2, 'What''s one small thing you''re hoping this community gives you?'),
  ('start-here', 3, 'Who or what first pointed you toward The Connection Room?'),
  ('start-here', 4, 'Share a moment recently when you felt truly seen by another man.'),
  ('start-here', 5, 'What does “connection” mean to you right now, in one sentence?'),
  ('start-here', 6, 'What''s a quality you appreciate in yourself that you don''t say out loud often?'),
  ('start-here', 7, 'What''s one thing you wish more men talked about openly?'),
  ('start-here', 8, 'Share a memory of a place where you feel most like yourself.'),
  ('start-here', 9, 'What''s a boundary you''re proud of setting?'),
  ('start-here', 10, 'Name one person who shaped how you show up in relationships.'),
  ('start-here', 11, 'What''s something you''re curious about but haven''t asked anyone yet?'),
  ('start-here', 12, 'What does “showing up fully” look like for you this week?'),
  ('start-here', 13, 'Share one thing you''re grateful for about your body today.'),
  ('start-here', 14, 'What''s a fear you have about being part of a community like this?'),
  ('start-here', 15, 'What would it mean for you to actually belong here?'),
  ('start-here', 16, 'Look back at your first post here — has anything shifted since then?'),
  ('commons', 1, 'What''s bringing you joy this week, big or small?'),
  ('commons', 2, 'Ask the room a question you''re genuinely curious about.'),
  ('commons', 3, 'What''s a hobby or interest outside “the work” that lights you up?'),
  ('commons', 4, 'Share a recent win, however small.'),
  ('commons', 5, 'What''s a piece of advice that''s stuck with you?'),
  ('commons', 6, 'If you could have coffee with anyone in this community, who and why?'),
  ('commons', 7, 'What''s something you''re looking forward to this month?'),
  ('commons', 8, 'Share a book, show, or song that''s meant something to you lately.'),
  ('commons', 9, 'What''s a tradition — yours or borrowed — that grounds you?'),
  ('commons', 10, 'What''s one thing that made you laugh this week?'),
  ('commons', 11, 'Where do you go, physically or mentally, when you need to reset?'),
  ('commons', 12, 'What''s a question you wish someone would ask you more often?'),
  ('commons', 13, 'Share something you made, built, or created recently.'),
  ('commons', 14, 'What''s a small act of kindness you gave or received recently?'),
  ('commons', 15, 'What''s one thing about this community you''d tell a friend?'),
  ('commons', 16, 'Looking back over the past few months here — what''s changed for you?'),
  ('couples', 1, 'What''s one way your partner makes you feel safe?'),
  ('couples', 2, 'Share a small ritual that keeps you two connected.'),
  ('couples', 3, 'What''s something you''ve learned about repair after conflict?'),
  ('couples', 4, 'When do you feel most “on the same team” with your partner?'),
  ('couples', 5, 'What''s a boundary that''s actually helped your relationship?'),
  ('couples', 6, 'Share a moment of closeness that surprised you recently.'),
  ('couples', 7, 'What does “showing up” for your partner look like on a hard day?'),
  ('couples', 8, 'What are you still learning about giving or receiving an apology?'),
  ('couples', 9, 'How do you and your partner handle needing space from each other?'),
  ('couples', 10, 'What''s a way you''ve grown as a partner over the last year?'),
  ('couples', 11, 'Share something your partner does that you don''t thank them for enough.'),
  ('couples', 12, 'What does emotional intimacy look like for you, day to day?'),
  ('couples', 13, 'What''s a conversation you''ve been avoiding having with your partner?'),
  ('couples', 14, 'How do you keep curiosity alive in a long relationship?'),
  ('couples', 15, 'What''s one thing you''d like your partner to understand about you right now?'),
  ('couples', 16, 'Looking back, what''s one repair you''re proud of?'),
  ('dating-desire', 1, 'What does vulnerability in dating look like for you?'),
  ('dating-desire', 2, 'Share a moment when honesty in dating paid off.'),
  ('dating-desire', 3, 'What''s a pattern in dating you''re trying to break?'),
  ('dating-desire', 4, 'What makes you feel desired?'),
  ('dating-desire', 5, 'What''s something you wish you could say on a first date but don''t?'),
  ('dating-desire', 6, 'How do you know when you actually feel safe with someone new?'),
  ('dating-desire', 7, 'What''s a “green flag” that matters more to you than most people realize?'),
  ('dating-desire', 8, 'Share a fear that shows up when you''re first getting close to someone.'),
  ('dating-desire', 9, 'What does taking things slow actually look like for you?'),
  ('dating-desire', 10, 'What''s something about your own desire you''re still figuring out?'),
  ('dating-desire', 11, 'How has your relationship with rejection changed over time?'),
  ('dating-desire', 12, 'What''s a boundary you''ve learned to hold while dating?'),
  ('dating-desire', 13, 'What does being pursued — or pursuing someone — honestly feel like for you?'),
  ('dating-desire', 14, 'Share a moment you let yourself be vulnerable and it went well.'),
  ('dating-desire', 15, 'What do you actually want more of in your dating life right now?'),
  ('dating-desire', 16, 'Looking back on this space, what''s shifted in how you approach vulnerability?'),
  ('embodiment', 1, 'Where in your body do you feel most at home?'),
  ('embodiment', 2, 'Try 60 seconds of slow breathing before you post — what did you notice?'),
  ('embodiment', 3, 'What''s a sensation you tend to ignore that deserves more attention?'),
  ('embodiment', 4, 'Share a movement practice — walk, stretch, dance — that brings you back to yourself.'),
  ('embodiment', 5, 'When do you feel most present in your body?'),
  ('embodiment', 6, 'What does tension in your body usually tell you?'),
  ('embodiment', 7, 'Share a moment this week you felt fully grounded.'),
  ('embodiment', 8, 'What''s one way you reconnect with your body after a stressful day?'),
  ('embodiment', 9, 'How does your breath change when you''re anxious versus calm?'),
  ('embodiment', 10, 'What''s a part of your body you''re learning to appreciate more?'),
  ('embodiment', 11, 'Try standing still for a minute — what do you notice first?'),
  ('embodiment', 12, 'What does “coming home to your body” mean to you?'),
  ('embodiment', 13, 'Share a physical sensation tied to a strong memory.'),
  ('embodiment', 14, 'What helps you feel safe in your body around others?'),
  ('embodiment', 15, 'What''s a practice you want to build more consistency with?'),
  ('embodiment', 16, 'Looking back, how has your relationship with your body shifted?'),
  ('intimacy-patterns', 1, 'What attachment pattern do you notice most in yourself?'),
  ('intimacy-patterns', 2, 'Share a moment you caught an old pattern playing out — and did something different.'),
  ('intimacy-patterns', 3, 'What does “secure” feel like in your body, when you notice it?'),
  ('intimacy-patterns', 4, 'What''s a pattern from your family of origin you still see in your relationships?'),
  ('intimacy-patterns', 5, 'When do you tend to pull away, and what usually triggers it?'),
  ('intimacy-patterns', 6, 'What helps you stay present instead of self-protecting?'),
  ('intimacy-patterns', 7, 'Share a relationship pattern you''re proud of changing.'),
  ('intimacy-patterns', 8, 'What does it feel like when you actually trust someone?'),
  ('intimacy-patterns', 9, 'What''s a fear that shows up when things start to get close?'),
  ('intimacy-patterns', 10, 'How do you tell the difference between anxiety and intuition in relationships?'),
  ('intimacy-patterns', 11, 'What''s one thing you need to feel safe getting close to someone?'),
  ('intimacy-patterns', 12, 'Share a moment you chose vulnerability over self-protection.'),
  ('intimacy-patterns', 13, 'What pattern do you want to understand better about yourself?'),
  ('intimacy-patterns', 14, 'How has therapy, coaching, or this community shifted your patterns?'),
  ('intimacy-patterns', 15, 'What does earned security look like for you personally?'),
  ('intimacy-patterns', 16, 'Looking back on these sixteen weeks, what pattern feels different now?'),
  ('masculinity-sex-sexuality', 1, 'What does masculinity mean to you today, versus growing up?'),
  ('masculinity-sex-sexuality', 2, 'Share a moment you felt fully expressed as yourself.'),
  ('masculinity-sex-sexuality', 3, 'What''s a message about being a man you''re still unlearning?'),
  ('masculinity-sex-sexuality', 4, 'When do you feel most confident in your own skin?'),
  ('masculinity-sex-sexuality', 5, 'What''s something about your sexuality you''re still exploring?'),
  ('masculinity-sex-sexuality', 6, 'Share a man who modeled a version of masculinity you admire.'),
  ('masculinity-sex-sexuality', 7, 'What does strength actually look like to you now?'),
  ('masculinity-sex-sexuality', 8, 'What''s a part of yourself you used to hide that you don''t anymore?'),
  ('masculinity-sex-sexuality', 9, 'How do you define being a “good man” for yourself?'),
  ('masculinity-sex-sexuality', 10, 'What''s something about your body or sexuality you''re learning to accept?'),
  ('masculinity-sex-sexuality', 11, 'Share a moment you chose authenticity over performance.'),
  ('masculinity-sex-sexuality', 12, 'What does emotional expression look like for you?'),
  ('masculinity-sex-sexuality', 13, 'What''s a stereotype about men you actively push back against?'),
  ('masculinity-sex-sexuality', 14, 'When do you feel most free to just be yourself?'),
  ('masculinity-sex-sexuality', 15, 'What''s one way you want to grow in how you express yourself?'),
  ('masculinity-sex-sexuality', 16, 'Looking back, what''s shifted in how you relate to your own masculinity?'),
  ('sacred-sexuality', 1, 'What does “sacred” mean to you in the context of sex and intimacy?'),
  ('sacred-sexuality', 2, 'Share a moment sex or touch felt like more than physical.'),
  ('sacred-sexuality', 3, 'What ritual or intention helps you feel present during intimacy?'),
  ('sacred-sexuality', 4, 'What''s something you''re learning about slowing down?'),
  ('sacred-sexuality', 5, 'How do presence and pleasure relate for you?'),
  ('sacred-sexuality', 6, 'Share a practice — breath, eye contact, stillness — that deepens intimacy for you.'),
  ('sacred-sexuality', 7, 'What does reverence for your own body look like?'),
  ('sacred-sexuality', 8, 'What''s a belief about sex you inherited that you''re reconsidering?'),
  ('sacred-sexuality', 9, 'When have you felt intimacy as a spiritual experience?'),
  ('sacred-sexuality', 10, 'What helps you stay present with another person during vulnerable moments?'),
  ('sacred-sexuality', 11, 'What does surrender mean to you in intimacy?'),
  ('sacred-sexuality', 12, 'Share something you''re learning about giving and receiving pleasure.'),
  ('sacred-sexuality', 13, 'What''s a way you honor your own desire?'),
  ('sacred-sexuality', 14, 'How does intention change the experience of intimacy for you?'),
  ('sacred-sexuality', 15, 'What''s one thing you want more of in how you approach sacred sexuality?'),
  ('sacred-sexuality', 16, 'Looking back, how has your understanding of sacred sexuality deepened?'),
  ('spirituality-sexuality', 1, 'How do spirit and body show up together for you?'),
  ('spirituality-sexuality', 2, 'Share a practice that helps you feel integrated, not fragmented.'),
  ('spirituality-sexuality', 3, 'What part of yourself have you had to reconcile with your beliefs?'),
  ('spirituality-sexuality', 4, 'When do you feel most whole?'),
  ('spirituality-sexuality', 5, 'What does integration actually feel like in your daily life?'),
  ('spirituality-sexuality', 6, 'Share a moment you felt spiritually connected during something physical.'),
  ('spirituality-sexuality', 7, 'What''s a belief system you''re rebuilding on your own terms?'),
  ('spirituality-sexuality', 8, 'How has your spiritual practice changed how you relate to your body?'),
  ('spirituality-sexuality', 9, 'What''s a question about meaning you keep returning to?'),
  ('spirituality-sexuality', 10, 'Share a ritual — formal or informal — that grounds you spiritually.'),
  ('spirituality-sexuality', 11, 'What does living in alignment mean to you?'),
  ('spirituality-sexuality', 12, 'What part of your spiritual life feels most disconnected from your sexuality, and why?'),
  ('spirituality-sexuality', 13, 'How do you make space for both mystery and practicality in your life?'),
  ('spirituality-sexuality', 14, 'What''s a moment you felt fully integrated — mind, body, spirit?'),
  ('spirituality-sexuality', 15, 'What''s one thing you''re still working to reconcile?'),
  ('spirituality-sexuality', 16, 'Looking back, what does integration look like for you now?'),
  ('touch-affection', 1, 'What does non-sexual touch mean to you?'),
  ('touch-affection', 2, 'Share a memory of affection that stuck with you.'),
  ('touch-affection', 3, 'What''s a form of touch — a hug, a hand on the shoulder — that means the most to you?'),
  ('touch-affection', 4, 'When do you feel most comfortable receiving affection?'),
  ('touch-affection', 5, 'What''s something you''re learning about asking for touch?'),
  ('touch-affection', 6, 'Share a moment touch helped you feel less alone.'),
  ('touch-affection', 7, 'What''s a boundary around touch you''ve had to learn to hold?'),
  ('touch-affection', 8, 'How do you give affection to the people you care about?'),
  ('touch-affection', 9, 'What''s something about physical affection between men you wish was more normal?'),
  ('touch-affection', 10, 'When did you last receive a hug that you actually needed?'),
  ('touch-affection', 11, 'What does safe touch feel like in your body?'),
  ('touch-affection', 12, 'Share a way you show care without words.'),
  ('touch-affection', 13, 'What''s a barrier you''ve had to work through around giving or receiving affection?'),
  ('touch-affection', 14, 'What''s one way you want to be more affectionate this week?'),
  ('touch-affection', 15, 'How has your comfort with touch changed over time?'),
  ('touch-affection', 16, 'Looking back, what''s shifted in how you give or receive affection?'),
  ('workshops', 1, 'What''s one thing you''re hoping to get out of a future workshop or retreat?'),
  ('workshops', 2, 'If you''ve attended one before, share a takeaway that stuck with you.'),
  ('workshops', 3, 'What topic would you love to see covered in an upcoming workshop?'),
  ('workshops', 4, 'What''s holding you back, if anything, from signing up for an event?'),
  ('workshops', 5, 'Share a moment from a past retreat that changed how you see something.'),
  ('workshops', 6, 'What format do you learn best in — small group, one-on-one, or a big room?'),
  ('workshops', 7, 'What''s a skill or practice you''d like a workshop to help you build?'),
  ('workshops', 8, 'If you could design a session yourself, what would it focus on?'),
  ('workshops', 9, 'What''s one thing you''d tell someone considering their first retreat?'),
  ('workshops', 10, 'Share how a workshop experience showed up in your life afterward.'),
  ('workshops', 11, 'What questions do you have about how these events actually work?'),
  ('workshops', 12, 'What''s a takeaway from a workshop you still use regularly?'),
  ('workshops', 13, 'Who would you want to invite to attend with you, and why?'),
  ('workshops', 14, 'What''s a topic you didn''t expect to resonate with but did?'),
  ('workshops', 15, 'What would make a retreat feel truly worth the time and cost to you?'),
  ('workshops', 16, 'Looking back at any workshops you''ve joined, what''s the biggest shift you''ve noticed?')
ON CONFLICT (space_id, week_number) DO NOTHING;
